//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using DoubleGis.Erm.Platform.Model.Entities.Interfaces;
using DoubleGis.Erm.Platform.Model.Entities.Interfaces.Integration;

namespace DoubleGis.Erm.Platform.Model.Entities.Erm
{
    public sealed partial class ReleaseWithdrawal : 
        IEntity, 
        IEntityKey, 
        IAuditableEntity, 
        IStateTrackingEntity
    {
        public ReleaseWithdrawal()
        {
            this.ReleasesWithdrawalsPositions = new HashSet<ReleasesWithdrawalsPosition>();
        }
        public long Id { get; set; }
        public long OrderPositionId { get; set; }
        public int ReleaseNumber { get; set; }
        public System.DateTime ReleaseBeginDate { get; set; }
        public System.DateTime ReleaseEndDate { get; set; }
        public decimal AmountToWithdraw { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public decimal Vat { get; set; }
        public byte[] Timestamp { get; set; }
    
        public OrderPosition OrderPosition { get; set; }
        public ICollection<ReleasesWithdrawalsPosition> ReleasesWithdrawalsPositions { get; set; }
    
    	public override bool Equals(object obj)
        {
            if (obj == null)
            {
                return false;
            }
    
            if (GetType() != obj.GetType())
            {
                return false;
            }
    
            if (ReferenceEquals(this, obj))
            {
                return true;
            }
    
    		var entityKey = obj as IEntityKey;
    		if (entityKey != null)
    		{
    			return Id == entityKey.Id;
    		}
    		
    		return false;
        }
    
    	override public int GetHashCode()
    	{
    		return Id.GetHashCode();
    	}
    }
}
