#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoubleGis.Erm.BLCore.UI.Web.Mvc.Views.GroupOperation
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DoubleGis.Erm.BLCore.Resources.Server.Properties;
    using DoubleGis.Erm.BLCore.UI.Metadata.Confirmations;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Controllers;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Models;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Models.GroupOperation;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Settings;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Settings.ConfigurationDto;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.UserProfiles;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Utils;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.ViewModels;
    using DoubleGis.Erm.Platform.Common;
    using DoubleGis.Erm.Platform.Model.Entities;
    using DoubleGis.Erm.Platform.Model.Entities.Enums;
    using DoubleGis.Erm.Platform.Model.Metadata.Enums;
    using DoubleGis.Erm.Platform.UI.Web.Mvc;
    using DoubleGis.Erm.Platform.UI.Web.Mvc.Security;
    using DoubleGis.Erm.Platform.UI.Web.Mvc.Utils;
    using NuClear.Model.Common.Entities;
    using NuClear.Model.Common.Operations.Identity;
    using NuClear.Model.Common.Operations.Identity.Generic;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/GroupOperation/DeactivateTerritory.cshtml")]
    public partial class DeactivateTerritory : System.Web.Mvc.WebViewPage<DeactivateTerritoryViewModel>
    {
        public DeactivateTerritory()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\GroupOperation\DeactivateTerritory.cshtml"
  
    Layout = "../Shared/_DialogLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("Title", () => {

WriteLiteral(" ");

            
            #line 7 "..\..\Views\GroupOperation\DeactivateTerritory.cshtml"
            Write(BLResources.DeactivateConfirmation);

            
            #line default
            #line hidden
WriteLiteral(" ");

});

DefineSection("TopBarTitle", () => {

WriteLiteral(" ");

            
            #line 8 "..\..\Views\GroupOperation\DeactivateTerritory.cshtml"
                  Write(BLResources.DeactivateConfirmation);

            
            #line default
            #line hidden
WriteLiteral(" ");

});

DefineSection("TopBarMessage", () => {

WriteLiteral(" ");

            
            #line 9 "..\..\Views\GroupOperation\DeactivateTerritory.cshtml"
                    Write(string.Format(BLResources.GroupOperationTopBarMessage, Model.EntityTypeName.ToStringLocalized(EnumResources.ResourceManager, EnumResources.Culture)));

            
            #line default
            #line hidden
WriteLiteral(" ");

});

WriteLiteral("\r\n");

DefineSection("PageContent", () => {

WriteLiteral("\r\n    \r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 436), Tuple.Create("\"", 563)
, Tuple.Create(Tuple.Create("", 442), Tuple.Create("/Scripts/", 442), true)
            
            #line 14 "..\..\Views\GroupOperation\DeactivateTerritory.cshtml"
, Tuple.Create(Tuple.Create("", 451), Tuple.Create<System.Object, System.Int32>("Ext.LocalizedResources." + ViewData.GetUserLocaleInfo().TwoLetterISOLanguageName + ".js"
            
            #line default
            #line hidden
, 451), false)
, Tuple.Create(Tuple.Create("", 543), Tuple.Create("?", 543), true)
            
            #line 14 "..\..\Views\GroupOperation\DeactivateTerritory.cshtml"
                                        , Tuple.Create(Tuple.Create("", 544), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 544), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    \r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 647), Tuple.Create("\"", 695)
, Tuple.Create(Tuple.Create("", 654), Tuple.Create("/Content/Progress.css?", 654), true)
            
            #line 16 "..\..\Views\GroupOperation\DeactivateTerritory.cshtml"
, Tuple.Create(Tuple.Create("", 676), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 676), false)
);

WriteLiteral(" />\r\n    \r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 718), Tuple.Create("\"", 776)
, Tuple.Create(Tuple.Create("", 724), Tuple.Create("/Scripts/Ext.Ajax.syncRequest.js?", 724), true)
            
            #line 18 "..\..\Views\GroupOperation\DeactivateTerritory.cshtml"
, Tuple.Create(Tuple.Create("", 757), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 757), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 823), Tuple.Create("\"", 889)
, Tuple.Create(Tuple.Create("", 829), Tuple.Create("/Scripts/DoubleGis.UI.GroupOperations.js?", 829), true)
            
            #line 19 "..\..\Views\GroupOperation\DeactivateTerritory.cshtml"
, Tuple.Create(Tuple.Create("", 870), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 870), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 936), Tuple.Create("\"", 981)
, Tuple.Create(Tuple.Create("", 942), Tuple.Create("/Scripts/Tooltip.js?", 942), true)
            
            #line 20 "..\..\Views\GroupOperation\DeactivateTerritory.cshtml"
, Tuple.Create(Tuple.Create("", 962), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 962), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        Ext.namespace(\'Ext.DoubleGis.UI.Deactivate\');\r\n        Ext.DoubleGis.U" +
"I.Deactivate.DeactivateTerritoryProcessor = Ext.extend(Ext.DoubleGis.UI.GroupPro" +
"cessor, {\r\n            FailedEntitiesMessages: [],\r\n            OwnerCode: 0,\r\n " +
"           IsPartialAssign: false,\r\n            NewTerritoryIdLookup: { },\r\n    " +
"        constructor: function(config) {\r\n                Ext.apply(config, {\r\n  " +
"                  listeners: {\r\n                        configspecificcontrols: " +
"function() {\r\n                            this.ConfigCustomControls();\r\n        " +
"                },\r\n                        applyusersettings: function() {\r\n   " +
"                         this.ApplyUserSettings();\r\n                        }\r\n " +
"                   }\r\n                });\r\n                Ext.DoubleGis.UI.Deac" +
"tivate.DeactivateTerritoryProcessor.superclass.constructor.call(this, config);\r\n" +
"            },\r\n            ConfigCustomControls: function() {\r\n                " +
"this.NewTerritoryIdLookup = Ext.getCmp(\"NewTerritoryId\");\r\n            },\r\n     " +
"       IsUserSettingsValid: function() {\r\n                if (Ext.getDom(\"NewTer" +
"ritoryId\").value == \"\") {\r\n                    Ext.MessageBox.show({\r\n          " +
"              title: \'\',\r\n                        msg: Ext.LocalizedResources.De" +
"activateMustPickTerritory,\r\n                        buttons: window.Ext.MessageB" +
"ox.OK,\r\n                        width: 300,\r\n                        icon: windo" +
"w.Ext.MessageBox.ERROR\r\n                    });\r\n                    return fals" +
"e;\r\n                }\r\n\r\n                return true;\r\n            },\r\n         " +
"   ApplyUserSettings: function() {\r\n                this.OwnerCode = this.NewTer" +
"ritoryIdLookup.getValue().id;\r\n\r\n                this.NewTerritoryIdLookup.disab" +
"le();\r\n            },\r\n            CreateParamsForControllerCall: function(entit" +
"yId) {\r\n                return { entityId: entityId, ownerCode: this.OwnerCode }" +
";\r\n            }\r\n        });\r\n\r\n        Ext.onReady(function() {\r\n\r\n           " +
" var ids = !window.dialogArguments ? [] : (window.dialogArguments.Values ? windo" +
"w.dialogArguments.Values : window.dialogArguments);\r\n\r\n            Ext.getDom(\'P" +
"ageContentCell\').style[\"vertical-align\"] = \"top\";\r\n            var config = {\r\n " +
"               Entities: ids, // массив id сущностей\r\n                OperationN" +
"ame: \'");

            
            #line 76 "..\..\Views\GroupOperation\DeactivateTerritory.cshtml"
                           Write(Model.OperationName);

            
            #line default
            #line hidden
WriteLiteral(@"', // тип операции - Qualify, Assign, ChangeTerritory
                CloseButtonText: Ext.LocalizedResources.Close, // локализованная надпись для кнопки закрыть
                NeedToSelectOneOrMoreItemsMsg: Ext.LocalizedResources.NeedToSelectOneOrMoreItems, // локализованная надпись о том что нужно выбрать один или несколько элементов
                ResultMessageTitle: Ext.LocalizedResources.GroupOperationResultsTitle, // локализованная надпись - заголовок для результатов операции
                ResultMessageTemplate: Ext.LocalizedResources.GroupOperationResultsMessage // локализованная надпись - шаблон строки для результатов операции
            };
            var deactivateTerritoryProcessor = new Ext.DoubleGis.UI.Deactivate.DeactivateTerritoryProcessor(config);
            if (!deactivateTerritoryProcessor.CheckProcessingPossibility()) {
                return;
            }
            deactivateTerritoryProcessor.Process();
        });
    </script>
");

            
            #line 89 "..\..\Views\GroupOperation\DeactivateTerritory.cshtml"
    
            
            #line default
            #line hidden
            
            #line 89 "..\..\Views\GroupOperation\DeactivateTerritory.cshtml"
     using (Html.BeginForm(null, null, null, FormMethod.Post, new Dictionary<string, object> {{"id", "EntityForm"}}))
    {

            
            #line default
            #line hidden
WriteLiteral("        <table");

WriteLiteral(" cellspacing=\"5\"");

WriteLiteral(" cellpadding=\"5\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" height=\"100%\"");

WriteLiteral(" style=\"position: fixed\"");

WriteLiteral(">\r\n            <colgroup>\r\n                <col");

WriteLiteral(" width=\"26\"");

WriteLiteral(" />\r\n                <col />\r\n            </colgroup>\r\n            <tbody>\r\n     " +
"           <tr>\r\n                    <td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" style=\"height: 30px;\"");

WriteLiteral(" id=\"Notifications\"");

WriteAttribute("onmouseover", Tuple.Create(" \r\n                             onmouseover=\"", 4872), Tuple.Create("\"", 4944)
, Tuple.Create(Tuple.Create("", 4917), Tuple.Create("AddTooltip(", 4917), true)
            
            #line 100 "..\..\Views\GroupOperation\DeactivateTerritory.cshtml"
, Tuple.Create(Tuple.Create("", 4928), Tuple.Create<System.Object, System.Int32>(Model.Message
            
            #line default
            #line hidden
, 4928), false)
, Tuple.Create(Tuple.Create("", 4942), Tuple.Create(");", 4942), true)
);

WriteLiteral(" \r\n                             onmouseout=\"RemoveTooltip();\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 102 "..\..\Views\GroupOperation\DeactivateTerritory.cshtml"
                       Write(Model.Message);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </td>\r\n                </tr" +
">\r\n                <tr>\r\n                    <td>\r\n                        <labe" +
"l");

WriteLiteral(" style=\"font-weight: bold\"");

WriteLiteral(">");

            
            #line 108 "..\..\Views\GroupOperation\DeactivateTerritory.cshtml"
                                                    Write(BLResources.AssignToOtherTerritory);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <table");

WriteLiteral(" style=\"table-layout: fixed\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" cellpadding=\"0\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(">\r\n                            <tbody>\r\n                                <tr>\r\n   " +
"                                 <td>\r\n");

WriteLiteral("                                        ");

            
            #line 113 "..\..\Views\GroupOperation\DeactivateTerritory.cshtml"
                                   Write(Html.LookupFor(k => k.NewTerritoryId, new LookupSettings {EntityName = EntityType.Instance.Territory()}));

            
            #line default
            #line hidden
WriteLiteral(@"
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div");

WriteLiteral(" id=\"pbDiv\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" id=\"pbInner\"");

WriteLiteral(">\r\n                            </div>\r\n                        </div>\r\n          " +
"          </td>\r\n                </tr>\r\n            </tbody>\r\n        </table>\r\n" +
"");

            
            #line 130 "..\..\Views\GroupOperation\DeactivateTerritory.cshtml"
        
            
            #line default
            #line hidden
            
            #line 130 "..\..\Views\GroupOperation\DeactivateTerritory.cshtml"
   Write(Html.Hidden("EntityType", Model.EntityTypeName.Description));

            
            #line default
            #line hidden
            
            #line 130 "..\..\Views\GroupOperation\DeactivateTerritory.cshtml"
                                                                    
    }

            
            #line default
            #line hidden
});

        }
    }
}
#pragma warning restore 1591
