#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoubleGis.Erm.BLCore.UI.Web.Mvc.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DoubleGis.Erm.BLCore.Resources.Server.Properties;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Controllers;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Models;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Settings;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.UserProfiles;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Utils;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.ViewModels;
    using DoubleGis.Erm.Platform.Common;
    using DoubleGis.Erm.Platform.Model.Entities;
    using DoubleGis.Erm.Platform.Model.Entities.Enums;
    using DoubleGis.Erm.Platform.Model.Metadata.Enums;
    using DoubleGis.Erm.Platform.UI.Web.Mvc;
    using DoubleGis.Erm.Platform.UI.Web.Mvc.Security;
    using DoubleGis.Erm.Platform.UI.Web.Mvc.Utils;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_CardLayout.cshtml")]
    public partial class CardLayout : System.Web.Mvc.WebViewPage<EntityViewModelBase>
    {
        public CardLayout()
        {
        }
        public override void Execute()
        {
WriteLiteral("<html");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral(">\r\n<head>\r\n    <title></title>\r\n    <base");

WriteLiteral(" target=\"_self\"");

WriteLiteral(" />\r\n\r\n    <meta");

WriteLiteral(" id=\"meta_IsDebug\"");

WriteLiteral(" name=\"meta_IsDebug\"");

WriteAttribute("content", Tuple.Create(" content=\"", 182), Tuple.Create("\"", 231)
            
            #line 8 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 192), Tuple.Create<System.Object, System.Int32>(HttpContext.Current.IsDebuggingEnabled
            
            #line default
            #line hidden
, 192), false)
);

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" id=\"meta_Revision\"");

WriteLiteral(" name=\"meta_Revision\"");

WriteAttribute("content", Tuple.Create(" content=\"", 286), Tuple.Create("\"", 315)
            
            #line 9 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 296), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 296), false)
);

WriteLiteral(" />\r\n    \r\n    <link");

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" href=\"/favicon.ico\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" href=\"/favicon.ico\"");

WriteLiteral("/>\r\n    \r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 513), Tuple.Create("\"", 560)
, Tuple.Create(Tuple.Create("", 520), Tuple.Create("/Content/ext-all.css?", 520), true)
            
            #line 14 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 541), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 541), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 608), Tuple.Create("\"", 652)
, Tuple.Create(Tuple.Create("", 615), Tuple.Create("/Content/CRM4.css?", 615), true)
            
            #line 15 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 633), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 633), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 700), Tuple.Create("\"", 748)
, Tuple.Create(Tuple.Create("", 707), Tuple.Create("/Content/MainPage.css?", 707), true)
            
            #line 16 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 729), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 729), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 796), Tuple.Create("\"", 844)
, Tuple.Create(Tuple.Create("", 803), Tuple.Create("/Content/ext-mask.css?", 803), true)
            
            #line 17 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 825), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 825), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 892), Tuple.Create("\"", 943)
, Tuple.Create(Tuple.Create("", 899), Tuple.Create("/Content/LookupStyle.css?", 899), true)
            
            #line 18 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 924), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 924), false)
);

WriteLiteral(" />\r\n    \r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 997), Tuple.Create("\"", 1041)
, Tuple.Create(Tuple.Create("", 1004), Tuple.Create("/Content/Card.css?", 1004), true)
            
            #line 20 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 1022), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 1022), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1089), Tuple.Create("\"", 1139)
, Tuple.Create(Tuple.Create("", 1096), Tuple.Create("/Content/ext-extend.css?", 1096), true)
            
            #line 21 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 1120), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 1120), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1187), Tuple.Create("\"", 1242)
, Tuple.Create(Tuple.Create("", 1194), Tuple.Create("/Content/AsyncFileUpload.css?", 1194), true)
            
            #line 22 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 1223), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 1223), false)
);

WriteLiteral(" />\r\n\r\n");

            
            #line 24 "..\..\Views\Shared\_CardLayout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Shared\_CardLayout.cshtml"
     if (HttpContext.Current.IsDebuggingEnabled)
    {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1322), Tuple.Create("\"", 1374)
, Tuple.Create(Tuple.Create("", 1328), Tuple.Create("/Scripts/ext-base-debug.js?", 1328), true)
            
            #line 26 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 1355), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 1355), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1425), Tuple.Create("\"", 1487)
, Tuple.Create(Tuple.Create("", 1431), Tuple.Create("/Scripts/ext-all-debug-w-comments.js?", 1431), true)
            
            #line 27 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 1468), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 1468), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

            
            #line 28 "..\..\Views\Shared\_CardLayout.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1562), Tuple.Create("\"", 1608)
, Tuple.Create(Tuple.Create("", 1568), Tuple.Create("/Scripts/ext-base.js?", 1568), true)
            
            #line 31 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 1589), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 1589), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1659), Tuple.Create("\"", 1704)
, Tuple.Create(Tuple.Create("", 1665), Tuple.Create("/Scripts/ext-all.js?", 1665), true)
            
            #line 32 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 1685), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 1685), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

            
            #line 33 "..\..\Views\Shared\_CardLayout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    \r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1764), Tuple.Create("\"", 1891)
, Tuple.Create(Tuple.Create("", 1770), Tuple.Create("/Scripts/", 1770), true)
            
            #line 35 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 1779), Tuple.Create<System.Object, System.Int32>("Ext.LocalizedResources." + ViewData.GetUserLocaleInfo().TwoLetterISOLanguageName + ".js"
            
            #line default
            #line hidden
, 1779), false)
, Tuple.Create(Tuple.Create("", 1871), Tuple.Create("?", 1871), true)
            
            #line 35 "..\..\Views\Shared\_CardLayout.cshtml"
                                       , Tuple.Create(Tuple.Create("", 1872), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 1872), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        Ext.USER_ID = ");

            
            #line 38 "..\..\Views\Shared\_CardLayout.cshtml"
                 Write(ViewData.GetUserIdentityInfo().Code);

            
            #line default
            #line hidden
WriteLiteral(";\r\n        Ext.USER_NAME = ");

            
            #line 39 "..\..\Views\Shared\_CardLayout.cshtml"
                   Write(ViewData.GetUserIdentityDisplayName());

            
            #line default
            #line hidden
WriteLiteral(";\r\n        Ext.CultureInfo = ");

            
            #line 40 "..\..\Views\Shared\_CardLayout.cshtml"
                     Write(Html.WriteJson(ViewData.GetUserLocaleInfo()));

            
            #line default
            #line hidden
WriteLiteral(";\r\n        Ext.CultureInfo.NumberFormatInfo.CurrencySymbol = \'");

            
            #line 41 "..\..\Views\Shared\_CardLayout.cshtml"
                                                      Write(ViewData.GetErmBaseCurrencySymbol());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        Ext.CRM_URL = \'");

            
            #line 42 "..\..\Views\Shared\_CardLayout.cshtml"
                  Write(ViewData.GetMsCrmSettingsUrl());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        Ext.BasicOperationsServiceRestUrl = \'");

            
            #line 43 "..\..\Views\Shared\_CardLayout.cshtml"
                                        Write(ViewData.GetBasicOperationsServiceRestUrl());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        Ext.SpecialOperationsServiceRestUrl = \'");

            
            #line 44 "..\..\Views\Shared\_CardLayout.cshtml"
                                          Write(ViewData.GetSpecialOperationsServiceRestUrl());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n    </script>\r\n    \r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2545), Tuple.Create("\"", 2608)
, Tuple.Create(Tuple.Create("", 2551), Tuple.Create("/Scripts/DoubleGis.GlobalVariables.js?", 2551), true)
            
            #line 47 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 2589), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 2589), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2655), Tuple.Create("\"", 2712)
, Tuple.Create(Tuple.Create("", 2661), Tuple.Create("/Scripts/Common.ErrorHandler.js?", 2661), true)
            
            #line 48 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 2693), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 2693), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2759), Tuple.Create("\"", 2815)
, Tuple.Create(Tuple.Create("", 2765), Tuple.Create("/Scripts/Ext.ux.FitToParent.js?", 2765), true)
            
            #line 49 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 2796), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 2796), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2862), Tuple.Create("\"", 2926)
, Tuple.Create(Tuple.Create("", 2868), Tuple.Create("/Scripts/DoubleGis.MvcFormValidator.js?", 2868), true)
            
            #line 50 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 2907), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 2907), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2973), Tuple.Create("\"", 3038)
, Tuple.Create(Tuple.Create("", 2979), Tuple.Create("/Scripts/DoubleGis.DependencyHandler.js?", 2979), true)
            
            #line 51 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 3019), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 3019), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3085), Tuple.Create("\"", 3143)
, Tuple.Create(Tuple.Create("", 3091), Tuple.Create("/Scripts/Ext.Ajax.syncRequest.js?", 3091), true)
            
            #line 52 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 3124), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 3124), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3190), Tuple.Create("\"", 3246)
, Tuple.Create(Tuple.Create("", 3196), Tuple.Create("/Scripts/Ext.ux.LookupField.js?", 3196), true)
            
            #line 53 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 3227), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 3227), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3293), Tuple.Create("\"", 3353)
, Tuple.Create(Tuple.Create("", 3299), Tuple.Create("/Scripts/Ext.ux.AsyncFileUpload.js?", 3299), true)
            
            #line 54 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 3334), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 3334), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3400), Tuple.Create("\"", 3454)
, Tuple.Create(Tuple.Create("", 3406), Tuple.Create("/Scripts/Ext.ux.LinkField.js?", 3406), true)
            
            #line 55 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 3435), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 3435), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3501), Tuple.Create("\"", 3554)
, Tuple.Create(Tuple.Create("", 3507), Tuple.Create("/Scripts/Ext.ux.Calendar.js?", 3507), true)
            
            #line 56 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 3535), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 3535), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3601), Tuple.Create("\"", 3662)
, Tuple.Create(Tuple.Create("", 3607), Tuple.Create("/Scripts/Ext.ux.LookupFieldOwner.js?", 3607), true)
            
            #line 57 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 3643), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 3643), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3709), Tuple.Create("\"", 3763)
, Tuple.Create(Tuple.Create("", 3715), Tuple.Create("/Scripts/Ext.ux.NotePanel.js?", 3715), true)
            
            #line 58 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 3744), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 3744), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3810), Tuple.Create("\"", 3872)
, Tuple.Create(Tuple.Create("", 3816), Tuple.Create("/Scripts/Ext.ux.ActionsHistoryTab.js?", 3816), true)
            
            #line 59 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 3853), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 3853), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3919), Tuple.Create("\"", 3974)
, Tuple.Create(Tuple.Create("", 3925), Tuple.Create("/Scripts/DoubleGis.UI.Card.js?", 3925), true)
            
            #line 60 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 3955), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 3955), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4021), Tuple.Create("\"", 4073)
, Tuple.Create(Tuple.Create("", 4027), Tuple.Create("/Scripts/Ext.ux.IdField.js?", 4027), true)
            
            #line 61 "..\..\Views\Shared\_CardLayout.cshtml"
, Tuple.Create(Tuple.Create("", 4054), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 4054), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n\r\n");

WriteLiteral("    ");

            
            #line 63 "..\..\Views\Shared\_CardLayout.cshtml"
Write(RenderSection("CardScripts"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n</head>\r\n    <body>\r\n");

            
            #line 67 "..\..\Views\Shared\_CardLayout.cshtml"
        
            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\Shared\_CardLayout.cshtml"
         using (Html.BeginForm(null, null, null, FormMethod.Post, new Dictionary<string, object> { { "id", "EntityForm" }, { "autocomplete", "off" }, { "target", "_self" } }))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" style=\"display: none\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"ContentTab_holder\"");

WriteLiteral(" class=\"Holder\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" style=\"display: none; height: 24px;\"");

WriteLiteral(" id=\"Notifications\"");

WriteLiteral(" class=\"Notifications\"");

WriteLiteral(">\r\n                    </div>\r\n                    <div");

WriteLiteral(" id=\"MainTab_holder\"");

WriteLiteral(">\r\n                        \r\n");

WriteLiteral("                        ");

            
            #line 75 "..\..\Views\Shared\_CardLayout.cshtml"
                   Write(RenderSection("CardBody"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        \r\n");

            
            #line 77 "..\..\Views\Shared\_CardLayout.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 77 "..\..\Views\Shared\_CardLayout.cshtml"
                         if (Model is IEntityViewModelBase && Model.ViewConfig.CardSettings.HasAdminTab)
                        {
                            Html.RenderPartial("AdministrationTab");
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n\r\n");

WriteLiteral("                    ");

            
            #line 84 "..\..\Views\Shared\_CardLayout.cshtml"
               Write(Html.CheckBoxFor(x => x.ViewConfig.ReadOnly));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 85 "..\..\Views\Shared\_CardLayout.cshtml"
               Write(Html.HiddenFor(m => m.ViewConfig.EntityName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 86 "..\..\Views\Shared\_CardLayout.cshtml"
               Write(Html.HiddenFor(m => m.ViewConfig.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 87 "..\..\Views\Shared\_CardLayout.cshtml"
               Write(Html.HiddenFor(m => m.ViewConfig.PId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 88 "..\..\Views\Shared\_CardLayout.cshtml"
               Write(Html.HiddenFor(m => m.ViewConfig.PType));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 89 "..\..\Views\Shared\_CardLayout.cshtml"
               Write(Html.HiddenFor(m => m.ViewConfig.ExtendedInfo));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 90 "..\..\Views\Shared\_CardLayout.cshtml"
               Write(Html.HiddenFor(m => m.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 91 "..\..\Views\Shared\_CardLayout.cshtml"
               Write(Html.Hidden("EntityStatus", ViewData["EntityStatus"]));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 92 "..\..\Views\Shared\_CardLayout.cshtml"
               Write(Html.Hidden("ViewConfig_DependencyList", Model.ViewConfig.DependencyList));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 93 "..\..\Views\Shared\_CardLayout.cshtml"
               Write(Html.HiddenFor(m => m.EntityStateToken));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 94 "..\..\Views\Shared\_CardLayout.cshtml"
               Write(Html.HiddenFor(m => m.IsDeleted));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 95 "..\..\Views\Shared\_CardLayout.cshtml"
               Write(Html.HiddenFor(m => m.IsActive));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                    <div");

WriteLiteral(" id=\"MessageType\"");

WriteLiteral(">");

            
            #line 97 "..\..\Views\Shared\_CardLayout.cshtml"
                                     Write(Model.MessageType);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <div");

WriteLiteral(" id=\"Message\"");

WriteLiteral(">");

            
            #line 98 "..\..\Views\Shared\_CardLayout.cshtml"
                                 Write(Model.Message);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div>\r\n            </div>            \r\n");

            
            #line 101 "..\..\Views\Shared\_CardLayout.cshtml"
        }   

            
            #line default
            #line hidden
WriteLiteral("        \r\n");

            
            #line 103 "..\..\Views\Shared\_CardLayout.cshtml"
        
            
            #line default
            #line hidden
            
            #line 103 "..\..\Views\Shared\_CardLayout.cshtml"
         if (IsSectionDefined("CustomInit"))
        {
            
            
            #line default
            #line hidden
            
            #line 105 "..\..\Views\Shared\_CardLayout.cshtml"
       Write(RenderSection("CustomInit"));

            
            #line default
            #line hidden
            
            #line 105 "..\..\Views\Shared\_CardLayout.cshtml"
                                        ;
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n                Ext.onReady(function()\r\n                {\r\n                   " +
" \r\n                    var cardSettings = ");

            
            #line 113 "..\..\Views\Shared\_CardLayout.cshtml"
                                  Write(Html.WriteJson(Model.ViewConfig.CardSettings));

            
            #line default
            #line hidden
WriteLiteral(";\r\n                    window.Card = new window.Ext.DoubleGis.UI.SharableCard(car" +
"dSettings);\r\n                    window.Card.Build();\r\n                    \r\n   " +
"             });\r\n            </script>\r\n");

            
            #line 119 "..\..\Views\Shared\_CardLayout.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
