#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoubleGis.Erm.BLCore.UI.Web.Mvc.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\Error.cshtml"
    using DoubleGis.Erm.BLCore.Resources.Client.Properties;
    
    #line default
    #line hidden
    using DoubleGis.Erm.BLCore.Resources.Server.Properties;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Controllers;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Models;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Settings;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.UserProfiles;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Utils;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.ViewModels;
    using DoubleGis.Erm.Platform.Common;
    using DoubleGis.Erm.Platform.Model.Entities;
    using DoubleGis.Erm.Platform.Model.Entities.Enums;
    using DoubleGis.Erm.Platform.Model.Metadata.Enums;
    using DoubleGis.Erm.Platform.UI.Web.Mvc;
    using DoubleGis.Erm.Platform.UI.Web.Mvc.Security;
    using DoubleGis.Erm.Platform.UI.Web.Mvc.Utils;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Error.cshtml")]
    public partial class Error : System.Web.Mvc.WebViewPage<ErrorHandlerModel>
    {
        public Error()
        {
        }
        public override void Execute()
        {
WriteLiteral("<html>\r\n<head>\r\n    <title>");

            
            #line 6 "..\..\Views\Shared\Error.cshtml"
      Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=Edge\"");

WriteLiteral(" />\r\n    \r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 271), Tuple.Create("\"", 335)
, Tuple.Create(Tuple.Create("", 278), Tuple.Create("/Content/ErrorPage.css?", 278), true)
            
            #line 10 "..\..\Views\Shared\Error.cshtml"
, Tuple.Create(Tuple.Create("", 301), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 301), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 383), Tuple.Create("\"", 442)
, Tuple.Create(Tuple.Create("", 390), Tuple.Create("/Content/CRM4.css?", 390), true)
            
            #line 11 "..\..\Views\Shared\Error.cshtml"
, Tuple.Create(Tuple.Create("", 408), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 408), false)
);

WriteLiteral(" />\r\n    \r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 465), Tuple.Create("\"", 526)
, Tuple.Create(Tuple.Create("", 471), Tuple.Create("/Scripts/ext-base.js?", 471), true)
            
            #line 13 "..\..\Views\Shared\Error.cshtml"
, Tuple.Create(Tuple.Create("", 492), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 492), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 573), Tuple.Create("\"", 633)
, Tuple.Create(Tuple.Create("", 579), Tuple.Create("/Scripts/ext-all.js?", 579), true)
            
            #line 14 "..\..\Views\Shared\Error.cshtml"
, Tuple.Create(Tuple.Create("", 599), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 599), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 680), Tuple.Create("\"", 742)
, Tuple.Create(Tuple.Create("", 686), Tuple.Create("/Scripts/ErrorPage.js?", 686), true)
            
            #line 15 "..\..\Views\Shared\Error.cshtml"
, Tuple.Create(Tuple.Create("", 708), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 708), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n\r\n</head>\r\n<body>\r\n    <!-- Outer div -->\r\n    <div");

WriteLiteral(" class=\"errorPage\"");

WriteLiteral(">\r\n        <!-- Information outer div -->\r\n        <div>\r\n            <!-- Pictur" +
"e outer div -->\r\n            <div");

WriteLiteral(" class=\"imageOuter floatLeft icon_error\"");

WriteLiteral("></div>\r\n            <!-- Text outer div -->\r\n            <div");

WriteLiteral(" class=\"textOuter floatLeft\"");

WriteLiteral(">\r\n                <!-- Title div -->\r\n                <div");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 29 "..\..\Views\Shared\Error.cshtml"
               Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <!-- Title div -->\r\n                <di" +
"v");

WriteLiteral(" class=\"errorText\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 33 "..\..\Views\Shared\Error.cshtml"
               Write(Model.Text);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral(">\r\n            </div>\r\n        </div>\r\n        <!-- Button div -->\r\n        <div");

WriteLiteral(" style=\"padding-left: 300px\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"tryAgain();\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1574), Tuple.Create("\"", 1609)
            
            #line 41 "..\..\Views\Shared\Error.cshtml"
, Tuple.Create(Tuple.Create("", 1582), Tuple.Create<System.Object, System.Int32>(BLResources.RepeatAttempts
            
            #line default
            #line hidden
, 1582), false)
);

WriteLiteral(" />\r\n            &nbsp;\r\n            <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"goBack();\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1687), Tuple.Create("\"", 1711)
            
            #line 43 "..\..\Views\Shared\Error.cshtml"
, Tuple.Create(Tuple.Create("", 1695), Tuple.Create<System.Object, System.Int32>(Resources.Close
            
            #line default
            #line hidden
, 1695), false)
);

WriteLiteral(" />\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral(">\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
