#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoubleGis.Erm.BL.UI.Web.Mvc.Views.AdvertisementElement
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DoubleGis.Erm.BLCore.Resources.Server.Properties;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Controllers;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Models;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Utils;
    using DoubleGis.Erm.Platform.Common;
    using DoubleGis.Erm.Platform.Model.Entities;
    using DoubleGis.Erm.Platform.Model.Entities.Enums;
    using DoubleGis.Erm.Platform.Model.Metadata.Enums;
    using DoubleGis.Erm.Platform.UI.Web.Mvc;
    using DoubleGis.Erm.Platform.UI.Web.Mvc.Utils;
    
    #line 1 "..\..\Views\AdvertisementElement\TextViewPage.cshtml"
    using Newtonsoft.Json;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\AdvertisementElement\TextViewPage.cshtml"
    using Platform.Model.Entities.Enums;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/AdvertisementElement/TextViewPage.cshtml")]
    public partial class TextViewPage : System.Web.Mvc.WebViewPage<Models.AdvertisementElementViewModel>
    {
        public TextViewPage()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\AdvertisementElement\TextViewPage.cshtml"
 if (Model.TemplateRestrictionType == AdvertisementElementRestrictionType.FasComment)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 8 "..\..\Views\AdvertisementElement\TextViewPage.cshtml"
   Write(Html.TemplateField(m => m.FasComment, FieldFlex.lone, null, EnumResources.ResourceManager));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 9 "..\..\Views\AdvertisementElement\TextViewPage.cshtml"
   Write(Html.Hidden("FasCommentDisplayTextItems", Model.FasCommentDisplayTextItemsJson));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 11 "..\..\Views\AdvertisementElement\TextViewPage.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 13 "..\..\Views\AdvertisementElement\TextViewPage.cshtml"
Write(Html.HiddenFor(m => m.TemplateTextLengthRestriction));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 14 "..\..\Views\AdvertisementElement\TextViewPage.cshtml"
Write(Html.HiddenFor(m => m.TemplateMaxSymbolsInWord));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 15 "..\..\Views\AdvertisementElement\TextViewPage.cshtml"
Write(Html.HiddenFor(m => m.TemplateTextLineBreaksRestriction));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 17 "..\..\Views\AdvertisementElement\TextViewPage.cshtml"
 if (Model.TemplateFormattedText)
{
    
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\AdvertisementElement\TextViewPage.cshtml"
Write(Html.HiddenFor(m => m.PlainText));

            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\AdvertisementElement\TextViewPage.cshtml"
                                     

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"display-wrapper field-wrapper lone\"");

WriteLiteral(" id=\"Text-wrapper\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"label-wrapper\"");

WriteLiteral(">");

            
            #line 22 "..\..\Views\AdvertisementElement\TextViewPage.cshtml"
                                  Write(Html.LabelFor(m => m.FormattedText));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            <div");

WriteLiteral(" class=\"input-wrapper\"");

WriteLiteral(">\r\n                \r\n                ");

WriteLiteral("\r\n                <div");

WriteLiteral(" id=\"TxtContainer\"");

WriteLiteral(" style=\"width: 600px; padding-top: 5px\"");

WriteLiteral("></div>\r\n\r\n");

WriteLiteral("                ");

            
            #line 28 "..\..\Views\AdvertisementElement\TextViewPage.cshtml"
           Write(Html.ValidationMessageFor(m => m.FormattedText, null, new Dictionary<string, object> { { "class", "error" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                ");

WriteLiteral("\r\n                <div");

WriteLiteral(" id=\"ctnt\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">");

            
            #line 31 "..\..\Views\AdvertisementElement\TextViewPage.cshtml"
                                                 Write(Model.FormattedText);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 35 "..\..\Views\AdvertisementElement\TextViewPage.cshtml"
}
else if (Model.TemplateAdvertisementLink)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 39 "..\..\Views\AdvertisementElement\TextViewPage.cshtml"
   Write(Html.TemplateField(m => m.PlainText, FieldFlex.lone, null));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 41 "..\..\Views\AdvertisementElement\TextViewPage.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 45 "..\..\Views\AdvertisementElement\TextViewPage.cshtml"
   Write(Html.TemplateField(m => m.PlainText, FieldFlex.lone, new Dictionary<string, object> { { "rows", "15" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 47 "..\..\Views\AdvertisementElement\TextViewPage.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
