#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoubleGis.Erm.BLCore.UI.Web.Mvc.Views.Metadata
{
    using System;

    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Models;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Metadata/Services.cshtml")]
    public partial class Services : System.Web.Mvc.WebViewPage<ServicesViewModel>
    {
        public Services()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Metadata\Services.cshtml"
  
    Layout = "../Shared/_DialogLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("Title", () => {

WriteLiteral(" Состояние служб ERM ");

});

DefineSection("TopBarTitle", () => {

WriteLiteral(" Состояние служб ERM ");

});

WriteLiteral("\r\n");

DefineSection("PageScript", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 208), Tuple.Create("\"", 267)
, Tuple.Create(Tuple.Create("", 214), Tuple.Create("/Scripts/DoubleGis.UI.Services.js?", 214), true)
            
            #line 12 "..\..\Views\Metadata\Services.cshtml"
, Tuple.Create(Tuple.Create("", 248), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 248), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        Ext.onReady(function () {\r\n            var control = new Ext.DoubleGis" +
".UI.Services({\r\n                renderTo: \'placeholder\',\r\n                url: \'" +
"");

            
            #line 17 "..\..\Views\Metadata\Services.cshtml"
                 Write(Model.IntrospectionServiceAddress);

            
            #line default
            #line hidden
WriteLiteral("\' + \'/GetAvailableServices\',\r\n                maskPanel: \'PageContentCell\',\r\n    " +
"            errorImage: \'/Content/images/Erm/red.png\',\r\n                successI" +
"mage: \'/Content/images/Erm/green.png\'\r\n            });\r\n        });\r\n        \r\n " +
"   </script>\r\n");

});

WriteLiteral("\r\n");

DefineSection("PageContent", () => {

WriteLiteral("\r\n    <div");

WriteLiteral(" id=\"placeholder\"");

WriteLiteral("></div>\r\n");

});

WriteLiteral("\r\n");

DefineSection("PageButtons", () => {

WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
