#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoubleGis.Erm.BLCore.UI.Web.Mvc.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DoubleGis.Erm.BLCore.Resources.Server.Properties;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Controllers;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Models;
    
    #line 1 "..\..\Views\Shared\_DialogLayout.cshtml"
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Settings;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\_DialogLayout.cshtml"
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.UserProfiles;
    
    #line default
    #line hidden
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Utils;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.ViewModels;
    using DoubleGis.Erm.Platform.Common;
    using DoubleGis.Erm.Platform.Model.Entities;
    using DoubleGis.Erm.Platform.Model.Entities.Enums;
    using DoubleGis.Erm.Platform.Model.Metadata.Enums;
    using DoubleGis.Erm.Platform.UI.Web.Mvc;
    
    #line 3 "..\..\Views\Shared\_DialogLayout.cshtml"
    using DoubleGis.Erm.Platform.UI.Web.Mvc.Security;
    
    #line default
    #line hidden
    using DoubleGis.Erm.Platform.UI.Web.Mvc.Utils;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_DialogLayout.cshtml")]
    public partial class DialogLayout : WebViewPage<dynamic>
    {
        public DialogLayout()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<html");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral(">\r\n<head>\r\n    <base");

WriteLiteral(" target=\"_self\"");

WriteLiteral(" />\r\n\r\n    <meta");

WriteLiteral(" id=\"meta_IsDebug\"");

WriteLiteral(" name=\"meta_IsDebug\"");

WriteAttribute("content", Tuple.Create(" content=\"", 311), Tuple.Create("\"", 360)
            
            #line 11 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 321), Tuple.Create<System.Object, System.Int32>(HttpContext.Current.IsDebuggingEnabled
            
            #line default
            #line hidden
, 321), false)
);

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" id=\"meta_Revision\"");

WriteLiteral(" name=\"meta_Revision\"");

WriteAttribute("content", Tuple.Create(" content=\"", 415), Tuple.Create("\"", 444)
            
            #line 12 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 425), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 425), false)
);

WriteLiteral(" />\r\n    \r\n    <link");

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" href=\"/favicon.ico\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" href=\"/favicon.ico\"");

WriteLiteral("/>\r\n    \r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 642), Tuple.Create("\"", 689)
, Tuple.Create(Tuple.Create("", 649), Tuple.Create("/Content/ext-all.css?", 649), true)
            
            #line 17 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 670), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 670), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 737), Tuple.Create("\"", 781)
, Tuple.Create(Tuple.Create("", 744), Tuple.Create("/Content/CRM4.css?", 744), true)
            
            #line 18 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 762), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 762), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 829), Tuple.Create("\"", 877)
, Tuple.Create(Tuple.Create("", 836), Tuple.Create("/Content/MainPage.css?", 836), true)
            
            #line 19 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 858), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 858), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 925), Tuple.Create("\"", 973)
, Tuple.Create(Tuple.Create("", 932), Tuple.Create("/Content/ext-mask.css?", 932), true)
            
            #line 20 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 954), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 954), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1021), Tuple.Create("\"", 1072)
, Tuple.Create(Tuple.Create("", 1028), Tuple.Create("/Content/LookupStyle.css?", 1028), true)
            
            #line 21 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 1053), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 1053), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1120), Tuple.Create("\"", 1164)
, Tuple.Create(Tuple.Create("", 1127), Tuple.Create("/Content/Card.css?", 1127), true)
            
            #line 22 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 1145), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 1145), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1212), Tuple.Create("\"", 1268)
, Tuple.Create(Tuple.Create("", 1219), Tuple.Create("/Content/ext-ux-calendar2.css?", 1219), true)
            
            #line 23 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 1249), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 1249), false)
);

WriteLiteral(" />\r\n    \r\n");

            
            #line 25 "..\..\Views\Shared\_DialogLayout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Shared\_DialogLayout.cshtml"
     if (HttpContext.Current.IsDebuggingEnabled)
    {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1352), Tuple.Create("\"", 1404)
, Tuple.Create(Tuple.Create("", 1358), Tuple.Create("/Scripts/ext-base-debug.js?", 1358), true)
            
            #line 27 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 1385), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 1385), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1455), Tuple.Create("\"", 1517)
, Tuple.Create(Tuple.Create("", 1461), Tuple.Create("/Scripts/ext-all-debug-w-comments.js?", 1461), true)
            
            #line 28 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 1498), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 1498), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

            
            #line 29 "..\..\Views\Shared\_DialogLayout.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1592), Tuple.Create("\"", 1638)
, Tuple.Create(Tuple.Create("", 1598), Tuple.Create("/Scripts/ext-base.js?", 1598), true)
            
            #line 32 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 1619), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 1619), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1689), Tuple.Create("\"", 1734)
, Tuple.Create(Tuple.Create("", 1695), Tuple.Create("/Scripts/ext-all.js?", 1695), true)
            
            #line 33 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 1715), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 1715), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

            
            #line 34 "..\..\Views\Shared\_DialogLayout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1790), Tuple.Create("\"", 1917)
, Tuple.Create(Tuple.Create("", 1796), Tuple.Create("/Scripts/", 1796), true)
            
            #line 36 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 1805), Tuple.Create<System.Object, System.Int32>("Ext.LocalizedResources." + ViewData.GetUserLocaleInfo().TwoLetterISOLanguageName + ".js"
            
            #line default
            #line hidden
, 1805), false)
, Tuple.Create(Tuple.Create("", 1897), Tuple.Create("?", 1897), true)
            
            #line 36 "..\..\Views\Shared\_DialogLayout.cshtml"
                                       , Tuple.Create(Tuple.Create("", 1898), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 1898), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    \r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        Ext.USER_ID = ");

            
            #line 39 "..\..\Views\Shared\_DialogLayout.cshtml"
                 Write(ViewData.GetUserIdentityInfo().Code);

            
            #line default
            #line hidden
WriteLiteral(";\r\n        Ext.USER_NAME = ");

            
            #line 40 "..\..\Views\Shared\_DialogLayout.cshtml"
                   Write(ViewData.GetUserIdentityDisplayName());

            
            #line default
            #line hidden
WriteLiteral(";\r\n        Ext.CultureInfo = ");

            
            #line 41 "..\..\Views\Shared\_DialogLayout.cshtml"
                     Write(Html.WriteJson(ViewData.GetUserLocaleInfo()));

            
            #line default
            #line hidden
WriteLiteral(";\r\n        Ext.CultureInfo.NumberFormatInfo.CurrencySymbol = \'");

            
            #line 42 "..\..\Views\Shared\_DialogLayout.cshtml"
                                                      Write(ViewData.GetErmBaseCurrencySymbol());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        Ext.BasicOperationsServiceRestUrl = \'");

            
            #line 43 "..\..\Views\Shared\_DialogLayout.cshtml"
                                        Write(ViewData.GetBasicOperationsServiceRestUrl());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        Ext.SpecialOperationsServiceRestUrl = \'");

            
            #line 44 "..\..\Views\Shared\_DialogLayout.cshtml"
                                          Write(ViewData.GetSpecialOperationsServiceRestUrl());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n    </script>\r\n    \r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2517), Tuple.Create("\"", 2580)
, Tuple.Create(Tuple.Create("", 2523), Tuple.Create("/Scripts/DoubleGis.GlobalVariables.js?", 2523), true)
            
            #line 47 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 2561), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 2561), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2627), Tuple.Create("\"", 2684)
, Tuple.Create(Tuple.Create("", 2633), Tuple.Create("/Scripts/Common.ErrorHandler.js?", 2633), true)
            
            #line 48 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 2665), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 2665), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2731), Tuple.Create("\"", 2787)
, Tuple.Create(Tuple.Create("", 2737), Tuple.Create("/Scripts/Ext.ux.LookupField.js?", 2737), true)
            
            #line 49 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 2768), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 2768), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2834), Tuple.Create("\"", 2888)
, Tuple.Create(Tuple.Create("", 2840), Tuple.Create("/Scripts/Ext.ux.LinkField.js?", 2840), true)
            
            #line 50 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 2869), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 2869), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2935), Tuple.Create("\"", 2988)
, Tuple.Create(Tuple.Create("", 2941), Tuple.Create("/Scripts/Ext.ux.Calendar.js?", 2941), true)
            
            #line 51 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 2969), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 2969), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3035), Tuple.Create("\"", 3096)
, Tuple.Create(Tuple.Create("", 3041), Tuple.Create("/Scripts/Ext.ux.LookupFieldOwner.js?", 3041), true)
            
            #line 52 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 3077), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 3077), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3143), Tuple.Create("\"", 3207)
, Tuple.Create(Tuple.Create("", 3149), Tuple.Create("/Scripts/DoubleGis.MvcFormValidator.js?", 3149), true)
            
            #line 53 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 3188), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 3188), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3254), Tuple.Create("\"", 3319)
, Tuple.Create(Tuple.Create("", 3260), Tuple.Create("/Scripts/DoubleGis.DependencyHandler.js?", 3260), true)
            
            #line 54 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 3300), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 3300), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3366), Tuple.Create("\"", 3429)
, Tuple.Create(Tuple.Create("", 3372), Tuple.Create("/Scripts/DoubleGis.UI.DialogWindow.js?", 3372), true)
            
            #line 55 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 3410), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 3410), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    \r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3482), Tuple.Create("\"", 3538)
, Tuple.Create(Tuple.Create("", 3488), Tuple.Create("/Scripts/Ext.ux.MonthPicker.js?", 3488), true)
            
            #line 57 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 3519), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 3519), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3585), Tuple.Create("\"", 3639)
, Tuple.Create(Tuple.Create("", 3591), Tuple.Create("/Scripts/Ext.ux.MonthMenu.js?", 3591), true)
            
            #line 58 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 3620), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 3620), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3686), Tuple.Create("\"", 3740)
, Tuple.Create(Tuple.Create("", 3692), Tuple.Create("/Scripts/Ext.ux.Calendar2.js?", 3692), true)
            
            #line 59 "..\..\Views\Shared\_DialogLayout.cshtml"
, Tuple.Create(Tuple.Create("", 3721), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 3721), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n\r\n");

            
            #line 61 "..\..\Views\Shared\_DialogLayout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 61 "..\..\Views\Shared\_DialogLayout.cshtml"
     if (IsSectionDefined("PageScript")) { 
        
            
            #line default
            #line hidden
            
            #line 62 "..\..\Views\Shared\_DialogLayout.cshtml"
   Write(RenderSection("PageScript"));

            
            #line default
            #line hidden
            
            #line 62 "..\..\Views\Shared\_DialogLayout.cshtml"
                                    
    }

            
            #line default
            #line hidden
WriteLiteral("    \r\n    <title>\r\n");

WriteLiteral("        ");

            
            #line 66 "..\..\Views\Shared\_DialogLayout.cshtml"
   Write(RenderSection("Title"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </title>\r\n</head>\r\n    <body>\r\n");

            
            #line 70 "..\..\Views\Shared\_DialogLayout.cshtml"
        
            
            #line default
            #line hidden
            
            #line 70 "..\..\Views\Shared\_DialogLayout.cshtml"
         if (IsSectionDefined("RawContent"))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral(" id=\"TopBarTitle\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 73 "..\..\Views\Shared\_DialogLayout.cshtml"
           Write(RenderSection("TopBarTitle"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" id=\"raw-content\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 76 "..\..\Views\Shared\_DialogLayout.cshtml"
           Write(RenderSection("RawContent"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

            
            #line 78 "..\..\Views\Shared\_DialogLayout.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <table");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" height=\"100%\"");

WriteLiteral(" border=\"0\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(">\r\n                <tr>\r\n                    <td");

WriteLiteral(" height=\"50px\"");

WriteLiteral(">\r\n                        <table");

WriteLiteral(" class=\"topmnuBar\"");

WriteLiteral(" cellpadding=\"0\"");

WriteLiteral(" cellspacing=\"5\"");

WriteLiteral(">\r\n                            <tbody>\r\n                                <tr>\r\n   " +
"                                 <td");

WriteLiteral(" valign=\"middle\"");

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"title\"");

WriteLiteral(" id=\"TopBarTitle\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 89 "..\..\Views\Shared\_DialogLayout.cshtml"
                                       Write(RenderSection("TopBarTitle"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </span>\r\n                              " +
"      </td>\r\n                                </tr>\r\n");

            
            #line 93 "..\..\Views\Shared\_DialogLayout.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 93 "..\..\Views\Shared\_DialogLayout.cshtml"
                                 if (IsSectionDefined("TopBarMessage"))
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <tr>\r\n                                       " +
" <td");

WriteLiteral(" valign=\"top\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" class=\"regular\"");

WriteLiteral(" id=\"TopBarMessage\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                ");

            
            #line 98 "..\..\Views\Shared\_DialogLayout.cshtml"
                                           Write(RenderSection("TopBarMessage"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            </span>\r\n                          " +
"              </td>\r\n                                    </tr>\r\n");

            
            #line 102 "..\..\Views\Shared\_DialogLayout.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </tbody>\r\n                        </table>\r\n         " +
"           </td>\r\n                </tr>\r\n                <tr>\r\n                 " +
"   <td");

WriteLiteral(" id=\"PageContentCell\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 109 "..\..\Views\Shared\_DialogLayout.cshtml"
                   Write(RenderSection("PageContent"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n       " +
"             <td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(" align=\"right\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" class=\"ms-crm-Dialog-Footer\"");

WriteLiteral(">\r\n");

            
            #line 114 "..\..\Views\Shared\_DialogLayout.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 114 "..\..\Views\Shared\_DialogLayout.cshtml"
                         if (IsSectionDefined("PageButtons"))
                        {
                            
            
            #line default
            #line hidden
            
            #line 116 "..\..\Views\Shared\_DialogLayout.cshtml"
                       Write(RenderSection("PageButtons"));

            
            #line default
            #line hidden
            
            #line 116 "..\..\Views\Shared\_DialogLayout.cshtml"
                                                         
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <input");

WriteLiteral(" class=\"CrmButton\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"OK\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6179), Tuple.Create("\"", 6202)
            
            #line 120 "..\..\Views\Shared\_DialogLayout.cshtml"
  , Tuple.Create(Tuple.Create("", 6187), Tuple.Create<System.Object, System.Int32>(BLResources.OK
            
            #line default
            #line hidden
, 6187), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                            <input");

WriteLiteral(" class=\"CrmButton\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"Cancel\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6286), Tuple.Create("\"", 6313)
            
            #line 121 "..\..\Views\Shared\_DialogLayout.cshtml"
      , Tuple.Create(Tuple.Create("", 6294), Tuple.Create<System.Object, System.Int32>(BLResources.Cancel
            
            #line default
            #line hidden
, 6294), false)
);

WriteLiteral(" />\r\n");

            
            #line 122 "..\..\Views\Shared\_DialogLayout.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n                </tr>\r\n            </table>\r\n");

            
            #line 126 "..\..\Views\Shared\_DialogLayout.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
