#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoubleGis.Erm.BLCore.UI.Web.Mvc.Views.Shared
{
    using System;
#line 1 "..\..\Views\Shared\Error.cshtml"
    using DoubleGis.Erm.BLCore.Resources.Client.Properties;
    
    #line default
    #line hidden
    using DoubleGis.Erm.BLCore.Resources.Server.Properties;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.ViewModels;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Error.cshtml")]
    public partial class Error : System.Web.Mvc.WebViewPage<ErrorHandlerModel>
    {
        public Error()
        {
        }
        public override void Execute()
        {
WriteLiteral("<html>\r\n<head>\r\n    <title>");

            
            #line 6 "..\..\Views\Shared\Error.cshtml"
      Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=Edge\"");

WriteLiteral(" />\r\n    \r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 271), Tuple.Create("\"", 320)
, Tuple.Create(Tuple.Create("", 278), Tuple.Create("/Content/ErrorPage.css?", 278), true)
            
            #line 10 "..\..\Views\Shared\Error.cshtml"
, Tuple.Create(Tuple.Create("", 301), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 301), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 368), Tuple.Create("\"", 412)
, Tuple.Create(Tuple.Create("", 375), Tuple.Create("/Content/CRM4.css?", 375), true)
            
            #line 11 "..\..\Views\Shared\Error.cshtml"
, Tuple.Create(Tuple.Create("", 393), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 393), false)
);

WriteLiteral(" />\r\n    \r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 435), Tuple.Create("\"", 481)
, Tuple.Create(Tuple.Create("", 441), Tuple.Create("/Scripts/ext-base.js?", 441), true)
            
            #line 13 "..\..\Views\Shared\Error.cshtml"
, Tuple.Create(Tuple.Create("", 462), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 462), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 528), Tuple.Create("\"", 573)
, Tuple.Create(Tuple.Create("", 534), Tuple.Create("/Scripts/ext-all.js?", 534), true)
            
            #line 14 "..\..\Views\Shared\Error.cshtml"
, Tuple.Create(Tuple.Create("", 554), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 554), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 620), Tuple.Create("\"", 667)
, Tuple.Create(Tuple.Create("", 626), Tuple.Create("/Scripts/ErrorPage.js?", 626), true)
            
            #line 15 "..\..\Views\Shared\Error.cshtml"
, Tuple.Create(Tuple.Create("", 648), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 648), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n\r\n</head>\r\n<body>\r\n    <!-- Outer div -->\r\n    <div");

WriteLiteral(" class=\"errorPage\"");

WriteLiteral(">\r\n        <!-- Information outer div -->\r\n        <div>\r\n            <!-- Pictur" +
"e outer div -->\r\n            <div");

WriteLiteral(" class=\"imageOuter floatLeft icon_error\"");

WriteLiteral("></div>\r\n            <!-- Text outer div -->\r\n            <div");

WriteLiteral(" class=\"textOuter floatLeft\"");

WriteLiteral(">\r\n                <!-- Title div -->\r\n                <div");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 29 "..\..\Views\Shared\Error.cshtml"
               Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <!-- Title div -->\r\n                <di" +
"v");

WriteLiteral(" class=\"errorText\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 33 "..\..\Views\Shared\Error.cshtml"
               Write(Model.Text);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral(">\r\n            </div>\r\n        </div>\r\n        <!-- Button div -->\r\n        <div");

WriteLiteral(" style=\"padding-left: 300px\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"tryAgain();\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1499), Tuple.Create("\"", 1534)
            
            #line 41 "..\..\Views\Shared\Error.cshtml"
, Tuple.Create(Tuple.Create("", 1507), Tuple.Create<System.Object, System.Int32>(BLResources.RepeatAttempts
            
            #line default
            #line hidden
, 1507), false)
);

WriteLiteral(" />\r\n            &nbsp;\r\n            <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"goBack();\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1612), Tuple.Create("\"", 1636)
            
            #line 43 "..\..\Views\Shared\Error.cshtml"
, Tuple.Create(Tuple.Create("", 1620), Tuple.Create<System.Object, System.Int32>(Resources.Close
            
            #line default
            #line hidden
, 1620), false)
);

WriteLiteral(" />\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral(">\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
