// File updated : 20.01.2014 15:08:22
// Processed resource entry host types:
// DoubleGis.Erm.BLCore.Resources.Client.Properties.Resources
// DoubleGis.Erm.Platform.Resources.Client.ResPlatformUI
/* 
Processing resources report:
	Target culture: cs
	Resource entries count: 276

*/
Ext.LocalizedResources =
{
	AcquireOrderExtensionFailed : 'Nebylo možné získat počítané hodnoty.',
ActionsHistory : 'Historie změn',
ActionsHistoryTabGroupRenderer : 'Akce: {0}, Hotovo: {1} Dne: {2}',
ActionsHistoryTabGroupTemplate : '{group} ({[values.rs.length]} {[values.rs.length%10 == 1 ? "změna": values.rs.length%10>0 && values.rs.length%10<5?"změny":"změn"]})',
Active : 'Aktivní',
ActivityDaysAndHoursFormat : 'Dnů: {0}, hodin: {1}',
ActivityDaysFormat : 'Dnů: {0}',
AddCategory : 'Přidat rubriku',
AdditionalServicesDefault : 'Nezadáno',
AdditionalServicesDependsOnAddress : 'Závisí na adrese',
AdditionalServicesDisplay : 'Zobrazovat',
AdditionalServicesDisplayService : 'Zobrazovat službu',
AdditionalServicesDoNotDisplay : 'Nezobrazovat',
AdditionalServicesService : 'Služba',
AdditionalServicesValueNotFound : 'Chybná hodnota!',
Address : 'Adresa',
AddressIsNotLocatedOnTheMap : 'Adresa nemá vazbu na mapu',
AdsCheckTooLongWord : 'Ve slove "{0}" byl prekrocen maximalni pocet symbolu: {1} z moznych {2}.',
AdvertisementElements : 'Prvky reklamního materiálu',
AdvertisementElementTextContainsControlCharacters : 'Текст содержит управляющие символы, удалить их перед сохранением?',
AdvertisementElementTextContainsHtmlTags : 'Текст содержит потенциально опасные элементы (тэги HTML), текст не может быть сохранён.',
AdvertisementElementWasNotSaved : 'Элемент РМ не был сохранён.',
Advertisements : 'Reklamní materiály',
AfterPageText : 'z {0}',
Alert : 'Pozor!',
AllExistingBillsWillBeDeleted : 'Všechny stávající faktury budou odstraněny. Pokračovat?',
AllFieldsMustBeSetForPayment : 'U vyúčtování musí být vyplněna všechna pole',
ApplicationError : 'Chyba programu',
April : 'Duben',
AreYouSureWantToDeleteBargain : 'Odstranit smlouvu?',
AtLeastOneLinkingObjectMustBeSelected : 'Musí být vybrán alespoň jeden vázaný objekt',
AtLeastOneLinkingObjectMustBeSelectedForTheFollowingSubpositions : 'Musí být vybrán alespoň jeden vázaný objekt v následujících podpoložkách: ',
August : 'Srpen',
AvailableRecords : 'Dostupné záznamy',
BackColorText : 'Změna barvy pozadí pro vybraný text nebo odstavec.',
BackColorTitle : 'Vyplnění',
BargainCreation : 'Generování smlouvy',
BargainCreationIsInProgress : 'Smlouva se generuje. Počkejte, prosím...',
BargainIsCreated : 'Smlouva {entity} byla vytvořena',
BeforePageText : 'Stránka',
BeginDistributionDate : 'Začátek zveřejnění',
BillCreationApprovalNeeded : 'Je vyžadován souhlas!',
BillMassCreateConfirmMessage : 'Pozor! Pro vybranou skupinu objednávek budou vytvořeny faktury. Pokračovat?',
BillMassCreateOrderHasZeroPayablePlan : 'Není možné hromadně vystavit faktury se splátkami, jestliže pracujete s objednávkou, na které je částka k zaplacení rovna nule. V seznamu pro hromadné vystavení faktur nesmí být vybrané objednávky.',
BoldText : 'Použití tučného písma na vybraný text.',
BoldTitle : 'Tučné (Ctrl+B)',
Cancel : 'Zrušit',
CanNotSelectHiddenPosition : 'Je třeba vyměnit vázané objekty, které byly skryté, za aktuálně dostupné',
CardIsDirtyAlert : 'Tuto akci není možné provést, pokud existují neuložené změny. Před tím, než budete pokračovat, uložte prosím změny nebo aktualizujte kartu.',
CardIsNewAlert : 'Tuto akci bude možné provést až po uložení záznamu. Než budete pokračovat, uložte prosím záznam.',
CardIsReadOnly : 'Tato karta je otevřena v režimu „pouze pro čtení“.',
CardIsUndefined : 'Pro tuto entitu není deklarována karta pro úpravu.',
Category : 'Rubrika',
CategoryAlreasyExistsInTheList : 'Seznam již obsahuje rubriku "{0}".',
CategoryName : 'Název rubriky',
CheckClientsDebtsFailed : 'Nebylo možné zkontrolovat pohledávky vybraných klientů. Pravděpodobně někteří z vybraných klientů mají pohledávky.',
Checking : 'Kontrola',
CheckInProgressPleaseStandBy : 'Probíhá kontrola. Počkejte, prosím...',
CheckProducedTheFollowingErrors : 'Během kontroly byly zjištěny následující chyby:',
ClickHereToAddNote : 'Poznámku přidáte kliknutím zde...',
Close : 'Zavřít',
CloseBargains_CurrentBargainIsObsolete : 'Stávající smlouva je neaktuální. Za účelem zveřejnění objednávky v rámci smlouvy je třeba vytvořit novou smlouvu',
CloseCardConfirmation : 'Provedené změny nebyly uloženy. Stisknutím tlačítka „Zrušit“ zůstanete na této stránce a uložíte změny.',
ContentIsEmpty : 'Chybí obsah',
Continue : 'Pokračovat',
CopyCurrentOrder : 'Zkopírovat stávající objednávku',
CopyOrderWithTermination : 'Vytvořit novou objednávku místo zrušené objednávky',
Create : 'Vytvořit',
CreateLinkText : 'Vytvoření odkazu z vybraného textu.',
CreateLinkTitle : 'Vložit hypertextový odkaz',
CreateText : 'Vytvořit',
DatePickerMaxText : 'Toto datum nemůže být pozdější než maximální datum',
DatePickerMinText : 'Toto datum nemůže být dřívější než minimální datum',
DatePickerMonthYearText : 'Výběr měsíce (tlačítkem Control+šipkou nahoru/dolů vyberte rok)',
DatePickerNextText : 'Následující měsíc (tlačítko Control+šipka doprava)',
DatePickerPrevText : 'Předchozí měsíc (tlačítko Control+šipka doleva)',
DatePickerToday : 'Dnes',
DatePickerTodayTip : '{0} (mezera)',
December : 'Prosinec',
DecreaseFontSizeText : 'Zmenšit velikost písma.',
DecreaseFontSizeTitle : 'Zmenšit velikost',
Deleted : 'Odstraněna',
DeletedItem : '(skrytý navždy)',
DeleteText : 'Odstranit',
DeleteValue : 'Odstranit hodnotu',
DisabledDatesText : 'Toto datum není možné vybrat',
DisabledDaysText : 'Toto datum není možné vybrat',
DiscountResetWarning : 'Ze všech položek objednávky budou odstraněny informace o slevách! Pokračovat?',
DisplayMsg : 'Jsou zobrazeny záznamy od {0} do {1}, celkem {2}',
DummyValue : 'Zástupný symbol',
DummyValueWillBeApplied : 'Místo reklamního materiálu bude použit zástupný symbol.',
EmptyMsg : 'K zobrazení nejsou žádné údaje',
EndDistributionDate : 'Konec zveřejnění',
Error : 'Chyba',
ErrorDetectedWhenChangingUseCaseState : 'Během pokusu o změnu stavu relace došlo k chybě',
ErrorDuringOperation : 'Během provádění operace došlo k chybě',
ErrorRetrievingDataFromServer : 'Chyba při přijímání dat ze serveru',
February : 'Únor',
FieldInvalidText : 'Byla zadána nesprávná hodnota',
FileNameNotSpecified : 'není uveden název souboru',
FileUploadCompleteText : 'Stahování bylo dokončeno',
FileUploadText : 'Vyčkejte prosím, soubor se nahrává na server...',
FindMoreRecords : 'Vyhledat další záznamy',
FirstPageText : 'První strana',
ForeColorText : 'Změna barvy textu.',
Friday : 'Pátek',
GetDataError : 'Chyba přijmu dat ze serveru.',
GridDDText : '{0} vybraných řádků',
GridViewColumns : 'Sloupce',
GridViewSortAscText : 'Třídit vzestupně',
GridViewSortDescText : 'Třídit sestupně',
HiddenItem : '(skrytý, dokud nebude vyjasněno)',
IncreaseFontSizeText : 'Zvětšení velikosti textu.',
IncreaseFontSizeTitle : 'Zvětšit velikost',
IndicatorText : 'Načítání...',
Information : 'Informace',
InputValidationInvalidUrl : 'Hodnota pole „{0}“ neni spravnou URL adresou',
InsertOrderedListText : 'Začít číslovaný seznam.',
InsertOrderedListTitle : 'Číslování',
InsertUnorderedListText : 'Začít seznam s odrážkami.',
InsertUnorderedListTitle : 'Odrážky',
InvalidDateText : '{0} není správně uvedené datum - datum musí být uvedeno ve formátu {1}',
InvalidSelectedPositionsCount : 'Musí být vybrán následující počet položek: {0}',
IsNecessaryChooseLimitForStatusChange : 'Před provedením změny stavu je třeba vybrat ze seznamu limit',
IsWarmClientWarningFormat : 'Vzhledem k tomu, že tento klient má úlohu „{0}“ uzavřenou {1} s typem „Možný klient“, byl vydán důvod obchodní transakce „Možný klient“',
ItalicText : 'Použití kurzívy na vybraný text.',
ItalicTitle : 'Kurzíva (Ctrl+I)',
ItsReadOnlyMode : 'Tento seznam je zobrazen v režimu „Pouze pro čtení“. Není možné vytvořit entitu.',
January : 'Leden',
July : 'Červenec',
June : 'Červen',
JustifyCenterText : 'Zarovnání textu na střed.',
JustifyCenterTitle : 'Na střed',
JustifyLeftText : 'Zarovnání textu doleva.',
JustifyLeftTitle : 'Zarovnat text doleva',
JustifyRightText : 'Zarovnání textu doprava.',
JustifyRightTitle : 'Zarovnat text doprava.',
LastPageText : 'Poslední strana',
LegalPersonProfileIsAlreadyMain : 'Tento profil je již nastaven jako hlavní',
LimitStatusApproved : 'Schválená',
LimitStatusChangeIsNotSupportedAsTheGroupOperation : 'Operace změny stavu limitu nejsou podporovány jako hromadné operace. Provádějte změnu stavu u limitů po jednom.',
LimitStatusError : 'CHYBA',
LimitStatusOpened : 'Otevřená',
LimitStatusRejected : 'Zamítnutá',
LineBreaksLeft : 'Zbyvajicich radku {0}',
LinkFieldInvalidEmailMessage : 'Zadaná hodnota není správnou e-mailovou adresou',
LinkFieldInvalidWebsiteMessage : 'Zadaná hodnota není správnou adresou URL',
LinkingObject : 'Vázaný objekt',
LinkingParameters : 'Možnosti vazby',
ListDoesNotSupportAppend : 'Tento seznam nepodporuje operaci přidání.',
ListDoesNotSupportExcluding : 'Tento seznam nepodporuje operaci vyloučení z pododdílu.',
ListingCantGetResultForEntityList : 'Nebylo možné zobrazit náhled seznamu entit typu „{0}“',
ListSeparator : ', ',
LoadAdvertisementResults : 'Reklamní materiály',
LoadMask : 'Nahrávání...',
LookupEmptyValue : '<prázdná hodnota>',
March : 'Březen',
MatchesNotFound : 'Nebyly nalezeny žádné shody',
MaxDateText : 'Datum v tomto poli nesmí překročit {0}',
May : 'Květen',
MergeClientsAlert : 'Po dokončení operace sloučení zůstane v systému hlavní klient, podřízený bude skrytý. Operaci nebude možné zrušit. Pokračovat?',
MergeLegalPersonsAlert : 'Pozor! Po dokončení operace sloučení zůstane v systému pouze hlavní pr. osoba klienta, vedlejší pr. osoba klienta bude skrytá. Operaci nebude možné zrušit!',
MergeLegalPersonsSucceded : 'Operace sloučení proběhla úspěšně',
MessageNotProcessedCorrectly : 'Nebylo možné správně zpracovat zprávu {0}',
MessageText : 'Текст сообщения',
MessageType : 'Тип сообщения',
MinDateText : 'Datum v tomto poli musí být po {0}',
Modified : 'Změněno',
ModifiedValue : 'Stanovená hodnota',
Monday : 'Pondělí',
MonthlyLowerBoundText : 'Hodnota musí odpovídat prvnímu dni v měsíci',
MonthlyUpperBoundText : 'Hodnota musí odpovídat poslednímu dni v měsíci',
MultipleMatchesFound : 'Bylo nalezeno několik shod',
MultiSelectionListFromListEmptyText : 'Do pole „Vyhledat záznamy“ zadejte celý název záznamu nebo jeho část a stiskněte ikonu „Vyhledat záznamy“.',
MultiSelectionListSearchInstructions : 'Zadejte hledané údaje do pole „Hledat“ a stiskněte tlačítko „Najít“. Poté vyberte v seznamu „Dostupné záznamy“ požadované záznamy a přesuňte je do seznamu „Vybrané záznamy“.',
MultiSelectionListToListEmptyText : 'Nebyl vybrán žádný záznam.',
MultiSelectionListTooManyRecordsAlert : 'Nalezeno záznamů: více než 100. Pokud seznam neobsahuje požadovaný záznam, zkuste zadat jiné údaje pro vyhledávání.',
MustSelectOneOrMoreObject : 'Pro provedení této operace je třeba předem vybrat jeden nebo více záznamů',
MustSelectOnlyOneObject : 'Pro provedení této operace je třeba vybrat pouze jeden jediný záznam',
NeedToSelectOneItem : 'Pro provedení této operace je třeba vybrat jeden záznam.',
NeedToSelectOneOrTwoItems : 'Pro provedení této operace je třeba vybrat jeden nebo dva záznamy',
NextPageText : 'Následující strana',
No : 'Ne',
NoteCreated : 'Poznámka vytvořena',
Notes : 'Poznámky',
NotificationsContextualTitle : 'Kontextové',
NotificationsDescriptionTitle : 'Popis',
NotificationsSystemTitle : 'Systémové',
November : 'Listopad',
October : 'Říjen',
OK : 'OK',
OpenText : 'Otevřít',
OrderCheck : 'Kontrola objednávky',
OrderCheckFailed : 'Nebylo možné zkontrolovat objednávku',
OrderCheckProducedTheFollowingWarnings : 'Objednávka je správná, během kontroly se však vyskytla následující upozornění:',
OrderCheckResults : 'Výsledky kontroly objednávky',
OrderCopying : 'Kopírování objednávky',
OrderCopyingCompleted : 'Kopírování dokončeno',
OrderCopyingFailure : 'Nebylo možné zkopírovat objednávku',
OrderCopyingInProgress : 'Objednávka se kopíruje. Počkejte, prosím...',
OrderCopyingSuccess : 'Objednávka byla zkopírována. Číslo nové objednávky - {entity}',
OrderCreation : 'Создание заказа',
OrderCreationIsInProgress : 'Идёт создание заказа. Пожалуйста, подождите...',
OrderIsCorrect : 'Objednávka je správná',
OrderIsCreated : 'Создан заказ {entity}',
OrderIsNotRelatedToAccount : 'Objednávka není propojena s žádným osobním účtem',
OrderProcessingRequestCancelled : 'Заявка отменена',
OrderRepairFailed : 'Nebylo možné upravit položky objednávky',
OrderRequestMessagesTabGroupRenderer : 'Выполнено: {0}    Дата: {1}',
OrderRequestMessagesTabGroupTemplate : '{group} ({[values.rs.length]} {[values.rs.length%10 == 1 ? "сообщение" : values.rs.length%10>0 && values.rs.length%10<5?"сообщения":"сообщений"]})',
OrderRequestMessagesTabTitle : 'Сообщения по заявке',
OrderState : 'Stav objednávky',
OrderUpgradeProducedTheFollowingWarnings : 'Po aktualizaci objednávky došlo k následujícím změnám:',
OrderValidationFailed : 'Nebylo možné provést kontrolu',
OriginalValue : 'Výchozí hodnota',
PayablePlan : 'K úhradě (plán.)',
Payment : 'Vyúčtování',
PaymentDatePlan : 'Splatnost do',
Payments : 'Vyúčtování',
PleaseWaitWhileCheckingClientDebts : 'Vyčkejte prosím. Právě probíhá kontrola stávajících pohledávek vybraných klientů.',
PrevPageText : 'Předcházející strana',
PriceForOrganizationUnitNotExists : 'V systému momentálně chybí zveřejněný ceník pro město {0}',
PrintText : 'Tisk',
ProcessMessagesConfirm : 'Skutečně si přejete zpracovat vybrané zprávy?',
Properties : 'Vlastnosti',
PropertyName : 'Měněné pole',
RefreshText : 'Aktualizovat seznam',
RelatedOrdersDestination : 'Cílové město',
RelatedOrdersIsSelected : 'Vybrat',
RelatedOrdersNoOrders : 'Neexistují objednávky, které by byly vhodné pro hromadné vystavení faktur',
RelatedOrdersNumber : 'Číslo',
RelatedOrdersSource : 'Výchozí město',
ReleaseCountPlanRangeMessage : 'Plánovaný počet vydání musí být v rozsahu [1-12]',
RepairInProgressPleaseStandBy : 'Probíhá oprava. Počkejte, prosím...',
RepairOutdatedOrderPositions : 'Aktualizovat objednávku dle aktuálního ceníku',
Reports : 'Výkazy/zprávy',
RequiredFieldMessage : 'Do pole „{0}“ je třeba zadat hodnotu',
Saturday : 'Sobota',
Search : 'Hledat:',
SearchInstructions : 'Do pole „Hledat“ zadejte požadované hledané údaje, poté stiskněte tlačítko „Najít“. Následně vyberte požadovaný záznam a stiskněte tlačítko OK.',
SearchRecords : 'Vyhledávání v záznamech',
SelectedRecords : 'Vybrané záznamy',
SelectObjectsToProcess : 'Vyberte zprávy pro zpracování',
SelectOneOrMoreRecords : 'Je třeba vybrat alespoň jeden záznam pro odstranění.',
SelectToWhiteList : 'Vybrat',
SelectToWhiteListMatherial : 'Výběr RM - seznam povolených',
SelectToWhiteListMatherialFailed : 'Při výběru RM do seznamu povolených se vyskytla chyba. Zkuste opakovat operaci',
September : 'Září',
SomeOfTheClientsHaveDebtsAlert : 'Pozor! Pokoušíte se vzít z rezervy klienta s úvěrovými závazky!',
SourceEditText : 'Přepnout na zdrojový kód.',
SourceEditTitle : 'Zdrojový kód',
StartSearch : 'Spustit vyhledávání',
StatusLabel : '<b>Stav: </b>',
SumRemainingMustBeNull : 'Zůstatek objednávky se nerovná nule. Zůstatek je třeba rozdělit mezi faktury',
Sunday : 'Neděle',
SymbolsLeft : 'Zbyvajici symboly: {0}',
TabPanelItemCloseText : 'Zavřít záložku',
Task : 'Úkol',
TextEditorLineBreaksOverflow : 'Pocet radku presahuje povoleny pocet {0} o {1}.',
TextEditorOverflow : 'Pocet symbolu presahuje povoleny pocet {0} symbolu o {1}.',
TheAdvertisement : 'Reklamní materiál',
Thursday : 'Čtvrtek',
TimeFormat : 'H:i:s',
Title : 'Nadpis',
Total : 'Celkem k zaplacení',
Tuesday : 'Úterý',
UnderlineText : 'Podtrhávání vybraného textu.',
UnderlineTitle : 'Podtržený (Ctrl+U)',
UnknownFileSize : 'Neznámá velikost',
UploadFileQuestion : 'Skutečně si přejete odeslat soubor „{0}“ na server?',
ValueCantBeEmpty : 'Hodnota nemůže být prázdná',
Wednesday : 'Středa',
WorkInProgressPleaseStandBy : 'Probíhá zpracování. Vyčkejte, prosím...',
Yes : 'Ano',
YouHaveToChooseLegalPersonToPrintOrder : 'Pro účely vytvoření výtisků je nezbytné uvést pr. osobu objednatele',
YouHaveToSaveOrderToPrint : 'Pro účely vytvoření výtisků je nezbytné uložit objednávku'
}
