// File updated : 26.12.2013 16:03:50
// Processed resource entry host types:
// DoubleGis.Erm.BL.Resources.Client.Properties.Resources
// DoubleGis.Erm.Platform.Resources.Client.ResPlatformUI
/* 
Processing resources report:
	Target culture: en
	Resource entries count: 276

*/
Ext.LocalizedResources =
{
	AcquireOrderExtensionFailed : 'Failed to obtain calculated values.',
ActionsHistory : 'Change history',
ActionsHistoryTabGroupRenderer : 'Action: {0}, Completed: {1} Date: {2}',
ActionsHistoryTabGroupTemplate : '{group} ({[values.rs.length]} {[values.rs.length%10 == 1 ? "change" : values.rs.length%10>0 && values.rs.length%10<5?"changes":"changes"]})',
Active : 'Active',
ActivityDaysAndHoursFormat : 'Days: {0}, hours: {1}',
ActivityDaysFormat : 'Days: {0}',
AddCategory : 'Add category',
AdditionalServicesDefault : 'Not set',
AdditionalServicesDependsOnAddress : 'Depend on address',
AdditionalServicesDisplay : 'Display',
AdditionalServicesDisplayService : 'Display service',
AdditionalServicesDoNotDisplay : 'Do not display',
AdditionalServicesService : 'Service',
AdditionalServicesValueNotFound : 'Invalid value!',
Address : 'Address',
AddressIsNotLocatedOnTheMap : 'Адрес не привязан к карте',
AdsCheckTooLongWord : 'Maximum permitted number of symbols in the word {0} is exceeded: {1} of {2} possible.',
AdvertisementElements : 'Components of advertising material',
AdvertisementElementTextContainsControlCharacters : 'Текст содержит управляющие символы, удалить их перед сохранением?',
AdvertisementElementTextContainsHtmlTags : 'Текст содержит потенциально опасные элементы (тэги HTML), текст не может быть сохранён.',
AdvertisementElementWasNotSaved : 'Элемент РМ не был сохранён.',
Advertisements : 'Advertising materials',
AfterPageText : 'of {0}',
Alert : 'Attention!',
AllExistingBillsWillBeDeleted : 'All existing payments will be deleted. Continue?',
AllFieldsMustBeSetForPayment : 'All payment fields should be filled in.',
ApplicationError : 'Program error',
April : 'April',
AreYouSureWantToDeleteBargain : 'Delete contract?',
AtLeastOneLinkingObjectMustBeSelected : 'At least one reference object should be selected',
AtLeastOneLinkingObjectMustBeSelectedForTheFollowingSubpositions : 'At least one reference object should be selected in the following subitems: ',
August : 'August',
AvailableRecords : 'Available records',
BackColorText : 'Change background color of selected text or abstract.',
BackColorTitle : 'Fill',
BargainCreation : 'Creating contract',
BargainCreationIsInProgress : 'Creating contract. Please wait…',
BargainIsCreated : 'Contract {entity} created',
BeforePageText : 'Page',
BeginDistributionDate : 'Start of placement',
BillCreationApprovalNeeded : 'Approval is required!',
BillMassCreateConfirmMessage : 'Attention! Payments will be created for the selected group of orders. Continue?',
BillMassCreateOrderHasZeroPayablePlan : 'Bulk creation of deferred payments cannot be performed if one of the orders has zero amount for payment. The list of payments for bulk creation should not contain selected orders.',
BoldText : 'Make selected text bold.',
BoldTitle : 'Bold (Ctrl+B)',
Cancel : 'Cancel',
CanNotSelectHiddenPosition : 'You have to change hidden reference objects to the objects available at present',
CardIsDirtyAlert : 'This action cannot be performed until all changes are saved. Please save changes or refresh the card to continue.',
CardIsNewAlert : 'This action cannot be completed until the record is saved. Please save the record to continue.',
CardIsReadOnly : 'This card is open in "read-only" mode.',
CardIsUndefined : 'There is no card to edit for this entity.',
Category : 'Category',
CategoryAlreasyExistsInTheList : 'Category {0} is already in the list.',
CategoryName : 'Category name',
CheckClientsDebtsFailed : 'Failed to check debts of the selected clients. Probably some of the selected clients have debts.',
Checking : 'Check',
CheckInProgressPleaseStandBy : 'Checking. Please wait...',
CheckProducedTheFollowingErrors : 'The following errors are detected during the check:',
ClickHereToAddNote : 'Click here to add notes...',
Close : 'Close',
CloseBargains_CurrentBargainIsObsolete : 'The current contract is out-of-date, to place an order under a contract, a new contract has to be created',
CloseCardConfirmation : 'Changes are not saved. To remain on the page and save changes, click "Cancel".',
ContentIsEmpty : 'Contents is unavailable',
Continue : 'Continue',
CopyCurrentOrder : 'Copy current order',
CopyOrderWithTermination : 'Create order instead of terminated one',
Create : 'Create',
CreateLinkText : 'Create link from the selected text.',
CreateLinkTitle : 'Insert hyperlink',
CreateText : 'Create',
DatePickerMaxText : 'This date is later than upper date limit',
DatePickerMinText : 'This date is earlier than lower date limit',
DatePickerMonthYearText : 'Month selection (Control+Up/Down to select a year)',
DatePickerNextText : 'Next month (Control+Right)',
DatePickerPrevText : 'Previous month (Control+Left)',
DatePickerToday : 'Today',
DatePickerTodayTip : '{0} (Space)',
December : 'December',
DecreaseFontSizeText : 'Decrease font size.',
DecreaseFontSizeTitle : 'Decrease size',
Deleted : 'Deleted',
DeletedItem : '(hidden forever)',
DeleteText : 'Delete',
DeleteValue : 'Delete value',
DisabledDatesText : 'This date cannot be selected',
DisabledDaysText : 'This date cannot be selected',
DiscountResetWarning : 'Information on discounts will be deleted for all order items! Continue?',
DisplayMsg : 'Records from {0} up to {1} are displayed, total of {2}',
DummyValue : 'Заглушка',
DummyValueWillBeApplied : 'Вместо рекламного материала будет применена заглушка.',
EmptyMsg : 'No data to display',
EndDistributionDate : 'End of placement',
Error : 'Error',
ErrorDetectedWhenChangingUseCaseState : 'Error encountered during changing of the session state',
ErrorDuringOperation : 'An error occurred during operation',
ErrorRetrievingDataFromServer : 'Failed to receive data from the server',
February : 'February',
FieldInvalidText : 'Incorrect value',
FileNameNotSpecified : 'file name is not specified',
FileUploadCompleteText : 'Download complete',
FileUploadText : 'Please wait until the file is uploaded to the server...',
FindMoreRecords : 'Search for additional records',
FirstPageText : 'The first page',
ForeColorText : 'Change text color.',
Friday : 'Friday',
GetDataError : 'Failed to receive data from server.',
GridDDText : '{0} selected strings',
GridViewColumns : 'Columns',
GridViewSortAscText : 'Sort ascending',
GridViewSortDescText : 'Sort descending',
HiddenItem : '(hidden till clarification)',
IncreaseFontSizeText : 'Increase font size.',
IncreaseFontSizeTitle : 'Increase size',
IndicatorText : 'Loading...',
Information : 'Main Information',
InputValidationInvalidUrl : 'Value of the field "{0}" is not a correct url-address',
InsertOrderedListText : 'Start a numbered list.',
InsertOrderedListTitle : 'Numbering',
InsertUnorderedListText : 'Start a bulleted list.',
InsertUnorderedListTitle : 'Bullets',
InvalidDateText : '{0} is an incorrect date. The date format should be {1}',
InvalidSelectedPositionsCount : 'Required number of selected items: {0}',
IsNecessaryChooseLimitForStatusChange : 'Before changing status, select a limit in the list',
IsWarmClientWarningFormat : 'Reason for opportunity is "Warm Lead", since there is a "{0}" task for this client, closed {1}, that has the "Warm Lead" type',
ItalicText : 'Make selected text italic.',
ItalicTitle : 'Italic(Ctrl+I)',
ItsReadOnlyMode : 'This list is viewed in "read-only" mode. Unable to create entity.',
January : 'January',
July : 'July',
June : 'June',
JustifyCenterText : 'Center text alignment.',
JustifyCenterTitle : 'Center',
JustifyLeftText : 'Left text alignment.',
JustifyLeftTitle : 'Align text left.',
JustifyRightText : 'Right text alignment.',
JustifyRightTitle : 'Align text right.',
LastPageText : 'The last page',
LegalPersonProfileIsAlreadyMain : 'This profile is already the main one',
LimitStatusApproved : 'Approved',
LimitStatusChangeIsNotSupportedAsTheGroupOperation : 'Change status operation cannot be performed for a group. Please change limit status one by one.',
LimitStatusError : 'Error',
LimitStatusOpened : 'Opened',
LimitStatusRejected : 'Rejected',
LineBreaksLeft : 'Number of lines left {0}',
LinkFieldInvalidEmailMessage : 'Entered value is not a correct e-mail address',
LinkFieldInvalidWebsiteMessage : 'Entered value is not a correct url address',
LinkingObject : 'Reference object',
LinkingParameters : 'Reference parameters',
ListDoesNotSupportAppend : 'This list does not support adding elements.',
ListDoesNotSupportExcluding : 'This list does not support the operation of excluding from a subdivision.',
ListingCantGetResultForEntityList : 'Can"t get listing view for entities of type "{0}"',
ListSeparator : ', ',
LoadAdvertisementResults : 'Advertising materials',
LoadMask : 'Loading...',
LookupEmptyValue : '<empty value>',
March : 'March',
MatchesNotFound : 'No matches are found',
MaxDateText : 'Date in this field should not be later than {0}',
May : 'May',
MergeClientsAlert : 'After merging, the main Client will remain in the system, while the subordinate client will be hidden. The operation cannon be undone. Continue?',
MergeLegalPersonsAlert : 'Attention! After merging, only the main legal entity of the Client will remain in the system, secondary legal entity of the Client will be hidden. The operation cannot be undone!',
MergeLegalPersonsSucceded : 'Merged successfully',
MessageNotProcessedCorrectly : 'Failed to correctly process message {0}',
MessageText : 'Текст сообщения',
MessageType : 'Тип сообщения',
MinDateText : 'Date in this field should be later than {0}',
Modified : 'Modified',
ModifiedValue : 'Set value',
Monday : 'Monday',
MonthlyLowerBoundText : 'The value should be the first date of month',
MonthlyUpperBoundText : 'The value should be the last date of month',
MultipleMatchesFound : 'Several matches are found',
MultiSelectionListFromListEmptyText : 'Enter name or its part in the "Record search" field and click the "Record search" icon.',
MultiSelectionListSearchInstructions : 'Enter desired data in the "Search" field and click the "Find" button. Then select required records in the "Available records" list and move them to the "Selected records" list.',
MultiSelectionListToListEmptyText : 'No record is selected.',
MultiSelectionListTooManyRecordsAlert : 'Records found: more than 100. If the required record is not in the list, try refining your search.',
MustSelectOneOrMoreObject : 'Select one or several records to perform this operation.',
MustSelectOnlyOneObject : 'Select only one record to perform this operation',
NeedToSelectOneItem : 'Select one record to perform this operation.',
NeedToSelectOneOrTwoItems : 'Select one or two records to complete this operation',
NextPageText : 'Next page',
No : 'No',
NoteCreated : 'Note has been created',
Notes : 'Notes',
NotificationsContextualTitle : 'Context',
NotificationsDescriptionTitle : 'Description',
NotificationsSystemTitle : 'System',
November : 'November',
October : 'October',
OK : 'OK',
OpenText : 'Open',
OrderCheck : 'Check of the order',
OrderCheckFailed : 'Failed to check the order.',
OrderCheckProducedTheFollowingWarnings : 'The order is correct, nevertheless the following warnings are found during the check:',
OrderCheckResults : 'Results of the order check',
OrderCopying : 'Copying order',
OrderCopyingCompleted : 'Copying completed',
OrderCopyingFailure : 'Failed to copy order',
OrderCopyingInProgress : 'Copying order. Please wait…',
OrderCopyingSuccess : 'Order copied. New order number is {entity}',
OrderCreation : 'Создание заказа',
OrderCreationIsInProgress : 'Идёт создание заказа. Пожалуйста, подождите...',
OrderIsCorrect : 'The order is correct',
OrderIsCreated : 'Создан заказ {entity}',
OrderIsNotRelatedToAccount : 'The order is not referenced to any personal account ',
OrderProcessingRequestCancelled : 'Заявка отменена',
OrderRepairFailed : 'Failed to correct items of the order',
OrderRequestMessagesTabGroupRenderer : 'Выполнено: {0}    Дата: {1}',
OrderRequestMessagesTabGroupTemplate : '{group} ({[values.rs.length]} {[values.rs.length%10 == 1 ? "сообщение" : values.rs.length%10>0 && values.rs.length%10<5?"сообщения":"сообщений"]})',
OrderRequestMessagesTabTitle : 'Сообщения по заявке',
OrderState : 'Order status',
OrderUpgradeProducedTheFollowingWarnings : 'Order update will produce the following changes:',
OrderValidationFailed : 'Failed to check',
OriginalValue : 'Initial value',
PayablePlan : 'Due for payment (planned)',
Payment : 'Payment',
PaymentDatePlan : 'Payment date, before',
Payments : 'Payments',
PleaseWaitWhileCheckingClientDebts : 'Please wait. Checking the selected clients for debts',
PrevPageText : 'Previous page',
PriceForOrganizationUnitNotExists : 'There is no published price-list for the city {0} in the system at present',
PrintText : 'Print',
ProcessMessagesConfirm : 'Do you really want to process selected messages?',
Properties : 'Properties',
PropertyName : 'Editable field',
RefreshText : 'Refresh the list',
RelatedOrdersDestination : 'Destination city',
RelatedOrdersIsSelected : 'Select',
RelatedOrdersNoOrders : 'No orders for bulk payment creation',
RelatedOrdersNumber : 'No.',
RelatedOrdersSource : 'Source city',
ReleaseCountPlanRangeMessage : 'Planned number of issues should be within the range [1-12]',
RepairInProgressPleaseStandBy : 'Correction is being made. Please wait...',
RepairOutdatedOrderPositions : 'Refresh the list with actual price-list informaion',
Reports : 'Reports',
RequiredFieldMessage : 'Specify value for the field "{0}"',
Saturday : 'Saturday',
Search : 'Search:',
SearchInstructions : 'Enter the search data into the "Search" field and click "Find". Then select the required record and click OK.',
SearchRecords : 'Record search',
SelectedRecords : 'Selected records',
SelectObjectsToProcess : 'Select messages to be processed',
SelectOneOrMoreRecords : 'You must select at least one record to be deleted.',
SelectToWhiteList : 'Select',
SelectToWhiteListMatherial : 'Select AM to the white list',
SelectToWhiteListMatherialFailed : 'An error occurred during AM white list selection. Try again',
September : 'September',
SomeOfTheClientsHaveDebtsAlert : 'Attention! You are trying to take a Client with a debt receivable!',
SourceEditText : 'Switch to the source code.',
SourceEditTitle : 'Source code',
StartSearch : 'Start search',
StatusLabel : '<b>Status: </b>',
SumRemainingMustBeNull : 'The remaining amount of the order is not equal to zero. The remaining amount needs to be distributed among payments',
Sunday : 'Sunday',
SymbolsLeft : 'Number of symbols remained: {0}',
TabPanelItemCloseText : 'Close the tab',
Task : 'Task',
TextEditorLineBreaksOverflow : 'Number of lines exceeds permitted {0} lines per {1}.',
TextEditorOverflow : 'Number of symbols exceeds permitted {0} symbols per {1}.',
TheAdvertisement : 'Advertising material',
Thursday : 'Thursday',
TimeFormat : 'H:i:s',
Title : 'Title',
Total : 'Total for payment',
Tuesday : 'Tuesday',
UnderlineText : 'Underline selected text.',
UnderlineTitle : 'Underlined (Ctrl+U)',
UnknownFileSize : 'The size is not known',
UploadFileQuestion : 'Do you really want to upload the "{0}" file to the server?',
ValueCantBeEmpty : 'The value cannot be empty',
Wednesday : 'Wednesday',
WorkInProgressPleaseStandBy : 'The job is being performed. Please wait...',
Yes : 'Yes',
YouHaveToChooseLegalPersonToPrintOrder : 'Legal entity of the customer must be specified to create a PF',
YouHaveToSaveOrderToPrint : 'Save order to create a PF'
}
