 

// File updated : 4/22/2015 3:10:40 PM
// Processed resource entry host types:
// DoubleGis.Erm.BL.Resources.Client.Properties.Resources
// DoubleGis.Erm.BLCore.Resources.Client.Properties.Resources
// DoubleGis.Erm.Platform.Resources.Client.ResPlatformUI
/* 

*/
Ext.LocalizedResources =
{
	AcquireOrderExtensionFailed : 'Не удалось получить вычисляемые значения.',
ActionIsNotAvailableSinceThereIsAnError : 'Действие недоступно, т.к. не все элементы являются валидными',
ActionsHistory : 'История изменений',
ActionsHistoryTabGroupRenderer : 'Действие: {0}, Выполнено: {1} Дата: {2}',
ActionsHistoryTabGroupTemplate : '{group} ({[values.rs.length]} {[values.rs.length%10 == 1 ? "изменение" : values.rs.length%10>0 && values.rs.length%10<5?"изменения":"изменений"]})',
Active : 'Активна',
ActivityDaysAndHoursFormat : 'Дней: {0}, часов: {1}',
ActivityDaysFormat : 'Дней: {0}',
AddCategory : 'Добавить рубрику',
AdditionalServicesDefault : 'Не задано',
AdditionalServicesDependsOnAddress : 'Зависит от адреса',
AdditionalServicesDisplay : 'Отображать',
AdditionalServicesDisplayService : 'Отображать услугу',
AdditionalServicesDoNotDisplay : 'Не отображать',
AdditionalServicesService : 'Услуга',
AdditionalServicesValueNotFound : 'Недопустимое значение!',
Address : 'Адрес',
AddressIsNotLocatedOnTheMap : 'Адрес не привязан к карте',
AdsCheckTooLongWord : 'В слове "{0}" превышено максимально допустимое количество символов: {1} из {2} возможных.',
AdvertisementElements : 'Элементы рекламного материала',
AdvertisementElementTextContainsControlCharacters : 'Текст содержит управляющие символы, удалить их перед сохранением?',
AdvertisementElementTextContainsHtmlTags : 'Текст содержит потенциально опасные элементы (тэги HTML), текст не может быть сохранён.',
AdvertisementElementWasNotSaved : 'Элемент РМ не был сохранён.',
Advertisements : 'Рекламные материалы',
AdvertisementTemplatePublishConfirmation : 'Вы действительно хотите опубликовать шаблон ракламного материала?',
AdvertisementTemplatePublishConfirmationLabel : 'Опубликовать шаблон рекламного материала',
AdvertisementTemplatePublishConfirmationWithDirtyForm : 'Вы действительно хотите опубликовать шаблон ракламного материала?<br/>На карточке есть изменения, которые будут утеряны при публикации.<br/>Если требуется их сохранить нажмите "нет" и сохраните карточку.',
AdvertisingElementAccept : 'Одобрить',
AdvertisingElementValidate : 'Выверка',
AfterPageText : 'из {0}',
Alert : 'Внимание!',
AllExistingBillsWillBeDeleted : 'Все существующие счета на оплату будут удалены. Продолжить?',
AllFieldsMustBeSetForPayment : 'Все поля должны быть заполнены для платежа',
ApplicationError : 'Ошибка программы',
April : 'Апрель',
AreYouSureWantToDeleteBargain : 'Удалить договор?',
AssignMustPickUser : 'Выбран режим "Назначить пользователю", но пользователь не указан.',
AtLeastOneLinkingObjectMustBeSelected : 'Должен быть выбран хотя бы один объект привязки',
AtLeastOneLinkingObjectMustBeSelectedForTheFollowingSubpositions : 'Должен быть выбран хотя бы один объект привязки в следующих подпозициях: ',
August : 'Август',
AvailableRecords : 'Доступные записи',
BackColorText : 'Изменение цвета фона для выделенного текста или абзаца.',
BackColorTitle : 'Заливка',
BargainCreation : 'Создание договора',
BargainCreationIsInProgress : 'Идёт создание договора. Пожалуйста, подождите...',
BargainIsCreated : 'Создан договор {entity}',
BeforePageText : 'Страница',
BeginDistributionDate : 'Начало размещения',
BillCreationApprovalNeeded : 'Требуется согласование!',
BillMassCreateConfirmMessage : 'Внимание! Будут созданы счета на оплату для выбранной группы заказов. Продолжить?',
BillMassCreateOrderHasZeroPayablePlan : 'Невозможно массовое создание счетов на оплату, с использованием рассрочки, используя заказ с нулевой суммой к оплате. Не должно быть выбранных заказов в списке для массового создания счетов на оплату.',
BillNumber : 'Номер',
BoldText : 'Применение полужирного начертания к выделенному тексту.',
BoldTitle : 'Полужирный (Ctrl+B)',
Cancel : 'Отмена',
CanNotSelectHiddenPosition : 'Нужно заменить объекты привязки, которые были скрыты, на доступные на текущий момент',
CannotSetDefaultTheme : 'Не удалось установить тематику по умолчанию',
CantUnpublishPriceWhenUnpublished : 'Нельзя отменить опубликование не опубликованного прайс-листа',
CardIsDirtyAlert : 'Данное действие невозможно выполнить при наличии несохранённых изменений. Пожалуйста, сохраните изменения или обновите карточку, прежде чем продолжить.',
CardIsNewAlert : 'Данное действие невозможно выполнить, пока запись не сохранена. Пожалуйста, сохраните запись, прежде чем продолжить.',
CardIsReadOnly : 'Данная карточка открыта в режиме "только для чтения".',
CardIsUndefined : 'Для данной сущности не объявлена карточка редактирования.',
Category : 'Рубрика',
CategoryAlreasyExistsInTheList : 'Рубрика "{0}" уже присутствует в списке.',
CategoryName : 'Название рубрики',
ChangeNeedToPickClient : 'Необходимо указать Клиента.',
CheckClientsDebtsFailed : 'Не удалось проверить долги выбранных клиентов. Возможно, у некоторых из выбранных клиентов имеются долги.',
Checking : 'Проверка',
CheckInProgressPleaseStandBy : 'Выполняется проверка. Пожалуйста, подождите...',
CheckProducedTheFollowingErrors : 'В ходе проверки были обнаружены следующие ошибки:',
ClickHereToAddNote : 'Щелкните здесь для добавления примечания...',
Close : 'Закрыть',
CloseBargains_CurrentBargainIsObsolete : 'Текущий договор устарел, для размещения заказа в рамках договора необходимо создать новый договор',
CloseCardConfirmation : 'Внесенные изменения не сохранены. Чтобы остаться на этой странице и сохранить изменения, нажмите кнопку "Отмена".',
ContentIsEmpty : 'Содержимое отсутствует',
Continue : 'Продолжить',
CopyCurrentOrder : 'Скопировать текущий заказ',
CopyOrderWithTermination : 'Создать заказ вместо расторгнутого',
Create : 'Создать',
CreateLinkText : 'Создание ссылки из выделенного текста.',
CreateLinkTitle : 'Вставить гиперссылку',
CreateText : 'Создать',
DatePickerMaxText : 'Эта дата позже максимальной даты',
DatePickerMinText : 'Эта дата раньше минимальной даты',
DatePickerMonthYearText : 'Выбор месяца (Control+Вверх/Вниз для выбора года)',
DatePickerNextText : 'Следующий месяц (Control+Вправо)',
DatePickerPrevText : 'Предыдущий месяц (Control+Влево)',
DatePickerToday : 'Сегодня',
DatePickerTodayTip : '{0} (Пробел)',
DeactivateMustPickTerritory : 'Необходимо указать территорию, на которую будут назначены клиенты и фирмы.',
DealMustPickOtherReason : 'Необходимо указать другую причину закрытия Сделки.',
December : 'Декабрь',
DecreaseFontSizeText : 'Уменьшение размера шрифта.',
DecreaseFontSizeTitle : 'Уменьшить размер',
Deleted : 'Удалена',
DeletedItem : '(скрыт навсегда)',
DeleteText : 'Удалить',
DeleteValue : 'Удалить значение',
DisabledDatesText : 'Данная дата недоступна для выбора',
DisabledDaysText : 'Данная дата недоступна для выбора',
DisabledFunctionality : 'Данный функционал временно недоступен',
DiscountResetWarning : 'По всем позициям заказа будет удалена информация о скидках! Продолжаем?',
DisplayErrorsList : 'Просмотреть список ошибок...',
DisplayMsg : 'Отображаются записи с {0} по {1}, всего {2}',
DummyValue : 'Заглушка',
DummyValueWillBeApplied : 'Вместо рекламного материала будет применена заглушка.',
EmptyMsg : 'Нет данных для отображения',
EndDistributionDate : 'Окончание размещения',
Error : 'Ошибка',
ErrorDetectedWhenChangingUseCaseState : 'Обнаружена ошибка при попытке изменить состояние сеанса',
ErrorDuringOperation : 'Во время выполнения операции произошла ошибка',
ErrorOnServiceAccess : 'Ошибка при обращении к сервису {0}. Обратитесь к разработчикам.',
ErrorRetrievingDataFromServer : 'Ошибка при получении данных с сервера',
February : 'Февраль',
FieldInvalidText : 'Указано неверное значение',
FileNameNotSpecified : 'имя файла не указано',
FileUploadCompleteText : 'Загрузка завершена',
FileUploadText : 'Пожалуйста, подождите, идет загрузка файла на сервер...',
FindMoreRecords : 'Поиск дополнительных записей',
FirstPageText : 'Первая страница',
ForeColorText : 'Измение цвета текста.',
Friday : 'Пятница',
GetDataError : 'Ошибка получения данных с сервера.',
GridDDText : '{0} выбранных строк',
GridViewColumns : 'Столбцы',
GridViewSortAscText : 'Сортировать по возрастанию',
GridViewSortDescText : 'Сортировать по убыванию',
GroupOperationResultsMessage : 'Успешно обработано:{0}.Не удалось обработать:{1}. ',
GroupOperationResultsTitle : 'Результаты выполнения операции',
HiddenItem : '(скрыт до выяснения)',
IncomingMessages : 'Входящие сообщения',
IncreaseFontSizeText : 'Увеличение размера шрифта.',
IncreaseFontSizeTitle : 'Увеличить размер',
IndicatorText : 'Идет загрузка...',
Information : 'Сведения',
InputValidationInvalidUrl : 'Значение поля "{0}" не является корректным url-адресом',
InsertOrderedListText : 'Начать нумерованный список.',
InsertOrderedListTitle : 'Нумерация',
InsertUnorderedListText : 'Начать маркированный список.',
InsertUnorderedListTitle : 'Маркеры',
InvalidDateText : '{0} не является правильной датой - дата должна быть указана в формате {1}',
InvalidDateTimeText : 'Некорректное значение. Используйте формат "ДД.MM.ГГГГ"',
InvalidSelectedPositionsCount : 'Должно быть выбрано позиций: {0}',
IsNecessaryChooseLimitForStatusChange : 'Перед выполнением операции смены статуса необходимо выбрать лимит в списке',
IsWarmClientWarningFormat : 'Выставлена причина сделки "Горячий клиент", т.к. для данного клиента существует задача "{0}", закрытая {1} с типом "Горячий клиент"',
ItalicText : 'Применение курсивного начертания к выделенному тексту.',
ItalicTitle : 'Курсив(Ctrl+I)',
ItsReadOnlyMode : 'Данный список просматривается в режиме "Только для чтения". Создание сущности невозможно.',
January : 'Январь',
July : 'Июль',
June : 'Июнь',
JustifyCenterText : 'Выравнивание текста по центру.',
JustifyCenterTitle : 'По центру',
JustifyLeftText : 'Выравнивание текста по левому краю.',
JustifyLeftTitle : 'Выровнять текст по левому краю',
JustifyRightText : 'Выравнивание текста по правому краю.',
JustifyRightTitle : 'Выровнять текст по правому краю.',
LastPageText : 'Последняя страница',
LegalPersonIsAlreadyMain : ' Данное юр. лицо уже является основным',
LegalPersonProfileIsAlreadyMain : 'Данный профиль уже является основным',
LimitIncreasingIsNotRequired : 'Увеличение лимита не требуется',
LimitStatusApproved : 'Одобрен',
LimitStatusChangeIsNotSupportedAsTheGroupOperation : 'Операции смены статуса лимита не поддерживаются как групповые операции. Пожалуйста изменяйте статус у лимитов по одному.',
LimitStatusError : 'ОШИБКА',
LimitStatusOpened : 'Открыт',
LimitStatusRejected : 'Отклонен',
LimitWillBeIncreased : 'Лимит будет увеличен на сумму {0}',
LineBreaksLeft : 'Строк осталось {0}',
LinkFieldInvalidEmailMessage : 'Введенное значение не является корректным e-mail адресом',
LinkFieldInvalidWebsiteMessage : 'Введенное значение не является корректным url адресом',
LinkingObject : 'Объект привязки',
LinkingParameters : 'Параметры привязки',
ListDoesNotSupportAppend : 'Данный список не поддерживает операцию добавления.',
ListDoesNotSupportExcluding : 'Данный список не поддерживает операцию исключения из подразделения.',
ListingCantGetResultForEntityList : 'Не удалось получить представление списка сущностей типа "{0}"',
ListSeparator : ', ',
LoadAdvertisementResults : 'Рекламные материалы',
LoadMask : 'Загрузка...',
LookupEmptyValue : '<пустое значение>',
March : 'Март',
MatchesNotFound : 'Совпадений не найдено',
MaxDateText : 'Дата в этом поле должна быть не больше {0}',
May : 'Май',
MergeClientsAlert : 'После завершения операции слияния в системе останется основной Клиент, подчиненный будет скрыт. Операцию нельзя будет отменить. Продолжить?',
MergeLegalPersonsAlert : 'Внимание! После завершения операции слияния в системе останется только основное Юр. лицо клиента, не основное Юр. лицо клиента будет скрыто. Операцию нельзя будет отменить!',
MergeLegalPersonsSucceded : 'Операция слияния проведена успешно',
MessageNotProcessedCorrectly : 'Сообщение {0} не удалось корректно обработать',
MessageText : 'Текст сообщения',
MessageType : 'Тип сообщения',
MinDateText : 'Дата в этом поле должна быть позже {0}',
Modified : 'Изменено',
ModifiedValue : 'Установленное значение',
Monday : 'Понедельник',
MonthlyLowerBoundText : 'Значение должно быть первым числом месяца',
MonthlyUpperBoundText : 'Значение должно быть последним числом месяца',
MultipleMatchesFound : 'Найдено несколько совпадений',
MultiSelectionListFromListEmptyText : 'Введите все или часть имени записи в поле "Поиск записей" и нажмите значок "Поиск записей".',
MultiSelectionListSearchInstructions : 'Введите искомые данные в поле "Искать" и нажмите кнопку "Найти". Затем в списке "Доступные записи" выберите требуемые записи и переместите их в список "Выбранные записи".',
MultiSelectionListToListEmptyText : 'Не выбрано ни одной записи.',
MultiSelectionListTooManyRecordsAlert : 'Найдено записей: более 100. Если требуемая запись отсутствует в списке, попробуйте ввести другие данные для поиска.',
MustSelectOneOrMoreObject : 'Для выполнения этой операции необходимо предварительно выбрать одну или несколько записей',
MustSelectOnlyOneObject : 'Для выполнения этой операции необходимо выбрать одну  и только одну запись',
NeedToSelectOneItem : 'Для выполнения данной операции необходимо выбрать одну запись.',
NeedToSelectOneOrMoreItems : 'Для выполнения данной операции необходимо выбрать одну или несколько записей.',
NeedToSelectOneOrTwoItems : 'Для выполнения данной операции необходимо выбрать одну или две записи',
NextPageText : 'Следующая страница',
No : 'Нет',
NoteCreated : 'Примечание создано',
Notes : 'Примечания',
NotificationsContextualTitle : 'Контекстные',
NotificationsDescriptionTitle : 'Описание',
NotificationsSystemTitle : 'Системные',
November : 'Ноябрь',
October : 'Октябрь',
OK : 'OK',
OpenText : 'Открыть',
OperationFailed : 'Ошибка выполнения операции',
OrderCheck : 'Проверка заказа',
OrderCheckFailed : 'Не удалось проверить заказ',
OrderCheckProducedTheFollowingWarnings : 'Заказ корректен, однако в ходе проверки были обнаружены следующие предупреждения:',
OrderCheckResults : 'Результаты проверки заказа',
OrderCopying : 'Копирование заказа',
OrderCopyingCompleted : 'Копирование завершено',
OrderCopyingFailure : 'Не удалось скопировать заказ',
OrderCopyingInProgress : 'Идёт копирование заказа. Пожалуйста, подождите...',
OrderCopyingSuccess : 'Заказ скопирован. Номер нового заказа - {entity}',
OrderCreation : 'Создание заказа',
OrderCreationIsInProgress : 'Идёт создание заказа. Пожалуйста, подождите...',
OrderIsCorrect : 'Заказ корректен',
OrderIsCreated : 'Создан заказ {entity}',
OrderIsNotRelatedToAccount : 'Заказ не связан ни с одним лицевым счётом',
OrderProcessingRequestCancelled : 'Заявка отменена',
OrderRepairFailed : 'Не удалось исправить позиции заказа',
OrderRequestMessagesTabGroupRenderer : 'Выполнено: {0}    Дата: {1}',
OrderRequestMessagesTabGroupTemplate : '{group} ({[values.rs.length]} {[values.rs.length%10 == 1 ? "сообщение" : values.rs.length%10>0 && values.rs.length%10<5?"сообщения":"сообщений"]})',
OrderRequestMessagesTabTitle : 'Сообщения по заявке',
OrderState : 'Статус заказа',
OrderUpgradeProducedTheFollowingWarnings : 'Обновление заказа привело к следующим изменениям:',
OrderValidationFailed : 'Не удалось выполнить проверку',
OriginalValue : 'Исходное значение',
OutgoingMessages : 'Исходящие сообщения',
PayablePlan : 'К оплате (план)',
Payment : 'Платеж',
PaymentDatePlan : 'Дата оплаты, до',
Payments : 'Платежи',
PleaseWaitWhileCheckingClientDebts : 'Пожалуйста, подождите - идет проверка на наличие задолженности у выбранных клиентов',
PrevPageText : 'Предыдущая страница',
PriceForOrganizationUnitNotExists : 'В системе на данный момент отсутствует опубликованный прайс-лист для города {0}',
PriceIsAlreadyPublished : 'Прайс-лист уже опубликован',
PrintText : 'Печать',
ProcessMessagesConfirm : 'Вы действительно хотите обработать выбранные сообщения?',
Properties : 'Свойства',
PropertyName : 'Изменяемое поле',
QualifyMustPickClient : 'Выбран режим "Указать клиента", но клиент не указан.',
QualifyMustPickUser : 'Выбран режим "Назначить другому пользователю", но пользователь не указан.',
RefreshText : 'Обновить список',
RelatedOrdersDestination : 'Город назначения',
RelatedOrdersIsSelected : 'Выбрать',
RelatedOrdersNoOrders : 'Нет заказов, подходящих для массового создания счетов на оплату',
RelatedOrdersNumber : 'Номер',
RelatedOrdersSource : 'Город источник',
ReleaseCountPlanRangeMessage : 'Планируемое число выпусков должно быть в диапазоне [1-12]',
RepairInProgressPleaseStandBy : 'Выполняется исправление. Пожалуйста, подождите...',
RepairOutdatedOrderPositions : 'Обновить заказ по актуальному прайс-листу',
Reports : 'Отчёты',
RequiredFieldMessage : 'Необходимо указать значение для поля "{0}"',
Saturday : 'Суббота',
SaveError : 'Ошибка при сохранении',
Search : 'Искать:',
SearchInstructions : 'Введите в поле "Искать" данные, которые требуется найти, и нажмите кнопку "Найти". Затем выберите требуемую запись, и нажмите кнопку OK.',
SearchRecords : 'Поиск в записях',
SelectedRecords : 'Выбранные записи',
SelectMessageToSave : 'Выберите сообщения для сохранения',
SelectObjectsToProcess : 'Выберите сообщения для обработки',
SelectOneOrMoreRecords : 'Необходимо выбрать по крайней мере одну запись для удаления.',
SelectToWhiteList : 'Выбрать',
SelectToWhiteListMatherial : 'Выбор РМ белый список',
SelectToWhiteListMatherialFailed : 'При выборе РМ в белый список произошла ошибка. Попробуйте повторить операцию',
September : 'Сентябрь',
SetLimitStatusDialogConfirmation : 'Вы действительно хотите изменить статус лимита на',
SomeOfTheClientsHaveDebtsAlert : 'Внимание! Вы пытаетесь взять из резерва Клиента с дебиторской задолженностью!',
SourceEditText : 'Переключиться на исходный код.',
SourceEditTitle : 'Исходный код',
StartCalling : 'Осуществляется звонок',
StartSearch : 'Начать поиск',
StatusLabel : '<b>Статус: </b>',
SumRemainingMustBeNull : 'Остаток суммы заказа не равен нулю. Необходимо распределить остаток по счетам',
Sunday : 'Воскресенье',
SymbolsLeft : 'Символов осталось: {0}',
TabPanelItemCloseText : 'Закрыть вкладку',
TextEditorLineBreaksOverflow : 'Количество строк превышает допустимые {0} на {1}.',
TextEditorOverflow : 'Количество символов превышает допустимые {0} символов на {1}.',
TheAdvertisement : 'Рекламный материал',
Thursday : 'Четверг',
TimeFormat : 'H:i:s',
Title : 'Заголовок',
Total : 'Итого к оплате',
Tuesday : 'Вторник',
UnderlineText : 'Подчёркивание выделенного текста.',
UnderlineTitle : 'Подчёркнутый (Ctrl+U)',
UnknownFileSize : 'Размер неизвестен',
UnpublishAdvertisementTemplateConfirmation : 'Вы действительно хотите отменить публикацию шаблона рекламного материала?',
UnpublishAdvertisementTemplateLabel : 'Отменить публикацию шаблона рекламного материала',
UploadFileQuestion : 'Вы действительно хотите загрузить файл "{0}" на сервер?',
ValueCantBeEmpty : 'Значение не может быть пустым',
Wednesday : 'Среда',
WorkInProgressPleaseStandBy : 'Работа выполняется. Пожалуйста, подождите...',
Yes : 'Да',
YouHaveToChooseLegalPersonToPrintOrder : 'Для формирования ПФ необходимо указать юр. лицо заказчика',
YouHaveToSaveOrderToPrint : 'Для формирования ПФ необходимо сохранить заказ'
}
