// File updated : 02.12.2014 16:13:25
// Processed resource entry host types:
// DoubleGis.Erm.BL.Resources.Client.Properties.Resources
// DoubleGis.Erm.BLCore.Resources.Client.Properties.Resources
// DoubleGis.Erm.Platform.Resources.Client.ResPlatformUI
/* 

*/
Ext.LocalizedResources =
{
	AcquireOrderExtensionFailed : 'No ha sido posible obtener los valores calculados.',
ActionIsNotAvailableSinceThereIsAnError : 'Acción no está disponible ya que no todos elementos son válidos',
ActionsHistory : 'Historial de cambios',
ActionsHistoryTabGroupRenderer : 'Acción: {0}, Completado: {1} Fecha: {2}',
ActionsHistoryTabGroupTemplate : '{group} ({[values.rs.length]} {[values.rs.length%10 == 1 ? "modificación": values.rs.length%10>0 && values.rs.length%10<5?"modificaciones":"modificaciones"]})',
Active : 'Activa',
ActivityDaysAndHoursFormat : 'Días: {0}, horas: {1}',
ActivityDaysFormat : 'Días: {0}',
AddCategory : 'Añadir categoría',
AdditionalServicesDefault : 'Ninguno',
AdditionalServicesDependsOnAddress : 'Depende de la dirección',
AdditionalServicesDisplay : 'Mostrar',
AdditionalServicesDisplayService : 'Mostrar servicio',
AdditionalServicesDoNotDisplay : 'No mostrar',
AdditionalServicesService : 'Servicio',
AdditionalServicesValueNotFound : '¡Valor no permitido!',
Address : 'Dirección',
AddressIsNotLocatedOnTheMap : 'La dirección no está enlazada con el mapa',
AdsCheckTooLongWord : 'En la palabra "{0}" se ha excedido el número máximo permitido de caracteres: {1} de {2} posibles.',
AdvertisementElements : 'Elementos del material publicitario',
AdvertisementElementTextContainsControlCharacters : 'El texto contiene caracteres de control, ¿desea eliminarlos antes de guardar?',
AdvertisementElementTextContainsControlList : 'Текст содержит вложенные списки,текст не может быть сохранен.',
AdvertisementElementTextContainsHtmlTags : 'El texto contiene elementos potencialmente peligrosos (etiquetas HTML), el texto no se podrá guardar.',
AdvertisementElementWasNotSaved : 'El elemento del material publicitario no se ha guardado.',
Advertisements : 'Materiales publicitarios',
AdvertisementTemplatePublishConfirmation : '¿Desea realmente publicar la plantilla de material publicitario?',
AdvertisementTemplatePublishConfirmationLabel : 'Publicar la plantilla de material publicitario',
AdvertisementTemplatePublishConfirmationWithDirtyForm : '¿Está seguro que quiere publicar la plantilla del material publicitario?<br/>En la ficha hay cambios que se perderán al publicar.<br/>Si hay que guardarlos, pulse "no" y guarde la ficha.',
AdvertisingElementAccept : 'Aprobar',
AdvertisingElementValidate : 'Verificación',
AfterPageText : 'de {0}',
Alert : '¡Atención!',
AllExistingBillsWillBeDeleted : 'Se eliminarán todas las facturas existentes. ¿Desea seguir?',
AllFieldsMustBeSetForPayment : 'Todos los campos deben completarse para el pago',
ApplicationError : 'Error del programa',
April : 'Abril',
AreYouSureWantToDeleteBargain : '¿Desea eliminar el contrato?',
AssignMustPickUser : 'Se ha seleccionado el modo de Designar al usuario, pero no se especifica el usuario.',
AtLeastOneLinkingObjectMustBeSelected : 'Se debe seleccionar al menos un enlace con el objeto',
AtLeastOneLinkingObjectMustBeSelectedForTheFollowingSubpositions : 'Se debe seleccionar al menos un enlace con el objeto en las siguientes subposiciones: ',
August : 'Agosto',
AvailableRecords : 'Registros disponibles',
BackColorText : 'Modificación de color del fondo del texto o párrafo seleccionado.',
BackColorTitle : 'Relleno',
BargainCreation : 'Creando contrato',
BargainCreationIsInProgress : 'Procesando la creación del contrato. Por favor, espere...',
BargainIsCreated : 'El contrato se ha creado {entity}',
BeforePageText : 'Página',
BeginDistributionDate : 'Inicio de la publicación',
BillCreationApprovalNeeded : '¡Se requiere confirmación!',
BillMassCreateConfirmMessage : '¡Atención! Se crearán facturas para el grupo seleccionado de órdenes. ¿Desea seguir?',
BillMassCreateOrderHasZeroPayablePlan : 'Imposible realizar la creación masiva de facturas para el pago a cuotas usando una orden con el importe cero. No debe haber órdenes seleccionadas en la lista para la creación masiva de facturas.',
BillNumber : 'Numero de factura',
BoldText : 'Aplicar el formato de seminegrita al texto seleccionado.',
BoldTitle : 'Seminegrita (Ctrl+B)',
Cancel : 'Cancelar',
CanNotSelectHiddenPosition : 'Se requiere reemplazar los enlaces con el objeto ocultos por los actualmente disponibles',
CannotSetDefaultTheme : 'No fue posible establecer la selección temática por defecto',
CantUnpublishPriceWhenUnpublished : 'No se puede cancelar la publicación de la lista de precios no publicada',
CardIsDirtyAlert : 'Esta acción no puede completarse debido a las modificaciones no guardadas. Guarde las modificaciones o actualice la ficha antes de continuar.',
CardIsNewAlert : 'Esta acción no puede completarse mientras el registro no se haya guardado. Guarde el registro antes de seguir.',
CardIsReadOnly : 'Esta ficha está abierta en modo de sólo lectura.',
CardIsUndefined : 'Para esta esencia no se ha declarado ninguna ficha de edición.',
Category : 'Categoría',
CategoryAlreasyExistsInTheList : 'La categoría "{0}" ya está en la lista.',
CategoryName : 'Nombre de categoría',
ChangeNeedToPickClient : 'Se requiere indicar el Cliente.',
CheckClientsDebtsFailed : 'No se han podido verificar las deudas de clientes seleccionados. Tal vez algunos clientes seleccionados tienen deudas.',
Checking : 'Validación',
CheckInProgressPleaseStandBy : 'Verificando. Por favor, espere...',
CheckProducedTheFollowingErrors : 'Durante la verificación se han encontrado los siguientes errores:',
ClickHereToAddNote : 'Haga clic aquí para agregar notas...',
Close : 'Cerrar',
CloseBargains_CurrentBargainIsObsolete : 'El contrato actual está obsoleto, para hacer una orden con arreglo al contrato se debe crear un contrato nuevo',
CloseCardConfirmation : 'No se han guardado las modificaciones realizadas. Para seguir en esta pagina y guardar las modificaciones, pulse el boton Cancelar.',
ContentIsEmpty : 'No hay contenido',
Continue : 'Seguir',
CopyCurrentOrder : 'Copiar la orden actual',
CopyOrderWithTermination : 'Crear nueva orden en base a la anulada',
Create : 'Crear',
CreateLinkText : 'Crear un enlace con el texto seleccionado.',
CreateLinkTitle : 'Insertar hipervínculo',
CreateText : 'Crear',
DatePickerMaxText : 'Esta fecha es posterior a la fecha máxima',
DatePickerMinText : 'Esta fecha es anterior a la fecha mínima',
DatePickerMonthYearText : 'Seleccionar mes (Control + Arriba / Abajo para seleccionar año)',
DatePickerNextText : 'Mes siguiente (Control+Flecha derecha)',
DatePickerPrevText : 'Mes anterior (Control+Flecha izquierda)',
DatePickerToday : 'Hoy',
DatePickerTodayTip : '{0} (Espacio)',
DeactivateMustPickTerritory : 'Hace falta especificar el territorio al que se designarán clientes y empresas.',
DealMustPickOtherReason : 'Se requiere indicar otro motivo del cierre de la Transacción.',
December : 'Diciembre',
DecreaseFontSizeText : 'Disminuir el tamaño de fuente.',
DecreaseFontSizeTitle : 'Disminuir tamaño',
Deleted : 'Eliminada',
DeletedItem : '(oculto permanentemente)',
DeleteText : 'Eliminar',
DeleteValue : 'Eliminar valor',
DisabledDatesText : 'Fecha no disponible para ser seleccionada',
DisabledDaysText : 'Fecha no disponible para ser seleccionada',
DisabledFunctionality : 'Esta funcionalidad no está disponible temporalmente',
DiscountResetWarning : '¡La información sobre descuentos se eliminará de todas las posiciones de la orden! ¿Seguimos?',
DisplayErrorsList : 'Visualizar la lista de errores...',
DisplayMsg : 'Se muestran los registros de {0} a {1}, en total {2}',
DummyValue : 'Stub',
DummyValueWillBeApplied : 'En lugar del material publicitario se aplicará el stub.',
EmptyMsg : 'No hay datos para mostrar',
EndDistributionDate : 'Finalización de la publicación',
Error : 'Error',
ErrorDetectedWhenChangingUseCaseState : 'Se ha producido un error al intentar modificar el estado de la sesión',
ErrorDuringOperation : 'Se ha producido un error durante la realización de la operación',
ErrorOnServiceAccess : 'Error al dirigirse al servidor {0}. Dirígense a los desarrolladores.',
ErrorRetrievingDataFromServer : 'Error al recibir los datos del servidor',
February : 'Febrero',
FieldInvalidText : 'Se ha indicado un valor incorrecto',
FileNameNotSpecified : 'no se ha indicado el nombre del archivo',
FileUploadCompleteText : 'Descarga completada',
FileUploadText : 'Por favor, espere, el archivo se está cargando en el servidor...',
FindMoreRecords : 'Buscar registros adicionales',
FirstPageText : 'Primera página',
ForeColorText : 'Modificar el color del texto.',
Friday : 'Viernes',
GetDataError : 'Error al recibir los datos del servidor.',
GridDDText : '{0} líneas seleccionadas',
GridViewColumns : 'Columnas',
GridViewSortAscText : 'Ordenar de menor a mayor',
GridViewSortDescText : 'Ordenar de mayor a menor',
GroupOperationResultsMessage : 'Procesado con éxito:{0}. No se ha podido procesar:{1}. ',
GroupOperationResultsTitle : 'Resultados de ejecución de la operación',
HiddenItem : '(oculto hasta validar)',
IncomingMessages : 'Mensajes entrantes',
IncreaseFontSizeText : 'Aumentar el tamaño de fuente.',
IncreaseFontSizeTitle : 'Aumentar tamaño',
IndicatorText : 'Descargando...',
Information : 'Información',
InputValidationInvalidUrl : 'El valor del campo "{0}" no es una dirección URL válida',
InsertOrderedListText : 'Iniciar lista numerada.',
InsertOrderedListTitle : 'Numeración',
InsertUnorderedListText : 'Iniciar lista con viñetas.',
InsertUnorderedListTitle : 'Viñetas',
InvalidDateText : '{0} no es una fecha válida, la fecha debe indicarse en formato {1}',
InvalidDateTimeText : 'Valor incorrecto. Use el formato  "DD-MM-XXXX"',
InvalidSelectedPositionsCount : 'Deben haber posiciones seleccionadas: {0}',
IsNecessaryChooseLimitForStatusChange : 'Antes de ejecutar la operacion de cambio de estado, debe seleccionar el limite de la lista',
IsWarmClientWarningFormat : 'Se muestra el motivo de la transacción Cliente interesado, ya que para dicho cliente existe la tarea "{0}", cerrada {1} con el tipo Cliente interesado',
ItalicText : 'Aplicar el formato de cursiva al texto seleccionado.',
ItalicTitle : 'Cursiva (Ctrl+I)',
ItsReadOnlyMode : 'Esta lista se ha abierto en modo de sólo lectura. Imposible crear la esencia.',
January : 'Enero',
July : 'Julio',
June : 'Junio',
JustifyCenterText : 'Alineación central del texto.',
JustifyCenterTitle : 'Central',
JustifyLeftText : 'Alineación del texto a la izquierda.',
JustifyLeftTitle : 'Alinear texto a la izquierda',
JustifyRightText : 'Alineación del texto a la derecha.',
JustifyRightTitle : 'Alinear texto a la derecha.',
LastPageText : 'Última página',
LegalPersonIsAlreadyMain : ' Esta razón social ya figura como principal',
LegalPersonProfileIsAlreadyMain : 'Este perfil ya es el principal',
LimitIncreasingIsNotRequired : 'No es necesario aumentar la línea de crédito',
LimitStatusApproved : 'Aprobado',
LimitStatusChangeIsNotSupportedAsTheGroupOperation : 'Las operaciones de cambio de estado del límite no se admiten como operaciones de grupo. Cambie el estado de límites uno por uno.',
LimitStatusError : 'ERROR',
LimitStatusOpened : 'Abierto',
LimitStatusRejected : 'Rechazado',
LimitWillBeIncreased : 'La línea de crédito será aumentada por el monto de {0}',
LineBreaksLeft : 'Líneas restantes {0}',
LinkFieldInvalidEmailMessage : 'El valor introducido no es una dirección válida de correo electrónico',
LinkFieldInvalidWebsiteMessage : 'El valor introducido no es una dirección URL válida',
LinkingObject : 'Enlace con el objeto',
LinkingParameters : 'Parámetros de enlace',
ListDoesNotSupportAppend : 'Esta lista no es compatible con la operación de adición.',
ListDoesNotSupportExcluding : 'Esta lista no es compatible con la operación de exclusión de la sucursal.',
ListingCantGetResultForEntityList : 'No se ha logrado recuperar la lista de esencias de tipo "{0}"',
ListSeparator : ', ',
LoadAdvertisementResults : 'Materiales publicitarios',
LoadMask : 'Cargando...',
LookupEmptyValue : '<valor en blanco>',
March : 'Marzo',
MatchesNotFound : 'No se han encontrado coincidencias',
MaxDateText : 'La fecha en este campo no debe ser mayor que {0}',
May : 'Mayo',
MergeClientsAlert : 'Después de la operación de fusión, el Cliente principal seguirá en el sistema, se ocultará el subordinado. La operación no podrá ser cancelada. ¿Desea seguir?',
MergeLegalPersonsAlert : '¡Atencion!  Despues de la finalizacion  de la funcion de fichas,  en  el  sistema  estara disponible solamente la persona juridica principal del cliente, la persona juridica adicional  del cliente sera  oculta y  la operación  no podra ser anulada.',
MergeLegalPersonsSucceded : 'La operación de fusión se ha completado con éxito',
MessageNotProcessedCorrectly : 'El mensaje {0} no se ha podido procesar correctamente',
MessageText : 'Texto del mensaje',
MessageType : 'Tipo de mensaje',
MinDateText : 'La fecha en este campo debe ser posterior a {0}',
Modified : 'Modificado',
ModifiedValue : 'Valor establecido',
Monday : 'Lunes',
MonthlyLowerBoundText : 'El valor debe ser el primer día del mes',
MonthlyUpperBoundText : 'El valor debe ser el último día del mes',
MultipleMatchesFound : 'Se han encontrado múltiples coincidencias',
MultiSelectionListFromListEmptyText : 'Introduzca todo o parte del nombre de registro en el campo Buscar registros y pulse el icono Buscar registros.',
MultiSelectionListSearchInstructions : 'Introduzca los datos requeridos en el campo Buscar y pulse el botón Buscar. Después, en la lista de Registros disponibles seleccione los registros requeridos y desplácelos a la lista de Registros seleccionados.',
MultiSelectionListToListEmptyText : 'No se ha seleccionado ningún registro.',
MultiSelectionListTooManyRecordsAlert : 'Registros encontrados: más de 100. Si el registro requerido no aparece en la lista, intente introducir otros datos para la búsqueda.',
MustSelectOneOrMoreObject : 'Para ejecutar esta operación, se debe seleccionar uno o más registros',
MustSelectOnlyOneObject : 'Para ejecutar esta operación, se debe seleccionar un solo registro',
NeedToSelectOneItem : 'Para ejecutar esta operación, se debe seleccionar un registro.',
NeedToSelectOneOrMoreItems : 'Para ejecutar esta operación, se debe seleccionar uno o dos registros.',
NeedToSelectOneOrTwoItems : 'Para ejecutar esta operación, se debe seleccionar uno o dos registros',
NextPageText : 'Página siguiente',
No : 'No',
NoteCreated : 'Observación creada',
Notes : 'Observaciones',
NotificationsContextualTitle : 'Contextuales',
NotificationsDescriptionTitle : 'Descripción',
NotificationsSystemTitle : 'Del sistema',
November : 'Noviembre',
October : 'Octubre',
OK : 'OK',
OpenText : 'Abrir',
OperationFailed : 'Error al cumplir la operación',
OrderCheck : 'Verificación de la orden',
OrderCheckFailed : 'No se ha podido verificar la orden',
OrderCheckProducedTheFollowingWarnings : 'La orden es correcta, sin embargo, su verificación ha revelado las siguientes advertencias:',
OrderCheckResults : 'Resultados de verificación de la orden',
OrderCopying : 'Copia de la orden',
OrderCopyingCompleted : 'Se ha completado la copia',
OrderCopyingFailure : 'No se ha podido copiar la orden',
OrderCopyingInProgress : 'Procesando la copia de la orden. Por favor, espere...',
OrderCopyingSuccess : 'La orden se ha copiado. Número de la nueva orden: {entity}',
OrderCreation : 'Crear una orden',
OrderCreationIsInProgress : 'Procesando la creación de la orden. Por favor, espere...',
OrderIsCorrect : 'Orden valida',
OrderIsCreated : 'Se ha creado la orden {entity}',
OrderIsNotRelatedToAccount : 'La orden no está enlazada con ninguna cuenta personal',
OrderProcessingRequestCancelled : 'Petición rechazada',
OrderRepairFailed : 'No se han podido corregir las posiciones de la orden',
OrderRequestMessagesTabGroupRenderer : 'Completado: {0}   Fecha: {1}',
OrderRequestMessagesTabGroupTemplate : '{group} ({[values.rs.length]} {[values.rs.length%10 == 1 ? "mensaje": values.rs.length%10>0 && values.rs.length%10<5?"mensajes":"mensajes"]})',
OrderRequestMessagesTabTitle : 'Mensajes según la petición',
OrderState : 'Estado de la orden',
OrderUpgradeProducedTheFollowingWarnings : 'La actualización de la orden ha llevado a las siguientes modificaciones:',
OrderValidationFailed : 'No se ha podido completar la verificación',
OriginalValue : 'Valor inicial',
OutgoingMessages : 'Mensajes salientes',
PayablePlan : 'A pagar (planificado)',
Payment : 'Pago',
PaymentDatePlan : 'Fecha de pago, hasta',
Payments : 'Pagos',
PleaseWaitWhileCheckingClientDebts : 'Por favor, espere, comprobando la presencia de deudas de los clientes seleccionados',
PrevPageText : 'Página anterior',
PriceForOrganizationUnitNotExists : 'De momento, en el sistema no hay ninguna lista de precios publicada para la ciudad de {0}',
PriceIsAlreadyPublished : 'La lista de precios ya está publicada',
PrintText : 'Imprimir',
ProcessMessagesConfirm : '¿Desea realmente procesar los mensajes seleccionados?',
Properties : 'Propiedades',
PropertyName : 'Campo editable',
QualifyMustPickClient : 'Se ha seleccionado el modo de Indicar cliente, pero el cliente no ha sido especificado.',
QualifyMustPickUser : 'Se ha seleccionado el modo de Designar a otro usuario, pero no se ha especificado el usuario.',
RefreshText : 'Actualizar lista',
RelatedOrdersDestination : 'Ciudad de destino',
RelatedOrdersIsSelected : 'Seleccionar',
RelatedOrdersNoOrders : 'No hay ninguna orden adecuada para la creación masiva de facturas',
RelatedOrdersNumber : 'Número',
RelatedOrdersSource : 'Ciudad de origen',
ReleaseCountPlanRangeMessage : 'El número previsto de lanzamientos debe estar en el rango [1-12]',
RepairInProgressPleaseStandBy : 'Se está realizando la corrección. Por favor, espere...',
RepairOutdatedOrderPositions : 'Actualizar la orden según la lista de precios vigente',
Reports : 'Informes',
RequiredFieldMessage : 'Es necesario indicar un valor para el campo "{0}"',
Saturday : 'Sábado',
SaveError : 'Error al guardar',
Search : 'Buscar:',
SearchInstructions : 'Introduzca los datos que está buscando en el campo Buscar y pulse el botón Buscar. Después, seleccione el registro que desea y pulse OK.',
SearchRecords : 'Búsqueda en los registros',
SelectedRecords : 'Registros seleccionados',
SelectMessageToSave : 'Seleccione mensajes para guardar',
SelectObjectsToProcess : 'Seleccione mensajes a procesar',
SelectOneOrMoreRecords : 'Debe seleccionar al menos un registro para eliminar.',
SelectToWhiteList : 'Seleccionar',
SelectToWhiteListMatherial : 'Seleccionar el material publicitario para la lista blanca',
SelectToWhiteListMatherialFailed : 'Ha ocurrido un error al seleccionar el material publicitario para la lista blanca. Intente volver a realizar la operación',
September : 'Septiembre',
SetLimitStatusDialogConfirmation : 'Desea realmente reemplazar el estado de límite por',
SomeOfTheClientsHaveDebtsAlert : '¡Atención! ¡Está intentando tomar de la reserva a un Cliente con deudas!',
SourceEditText : 'Cambiar al código inicial.',
SourceEditTitle : 'Código inicial',
StartSearch : 'Comenzar la búsqueda',
StatusLabel : '<b>Estado: </b>',
SumRemainingMustBeNull : 'El resto del importe de la orden no es igual a cero. Es necesario distribuir el resto según las facturas',
Sunday : 'Domingo',
SymbolsLeft : 'Caracteres restantes: {0}',
TabPanelItemCloseText : 'Cerrar pestaña',
TextEditorLineBreaksOverflow : 'El número de líneas excede el permitido {0} en {1}.',
TextEditorOverflow : 'El número de caracteres excede el permitido {0} en {1} caracteres.',
TheAdvertisement : 'Material publicitario',
Thursday : 'Jueves',
TimeFormat : 'H:i:s',
Title : 'Título',
Total : 'Total a pagar',
Tuesday : 'Martes',
UnderlineText : 'Subrayar el texto seleccionado.',
UnderlineTitle : 'Subrayado (Ctrl+U)',
UnknownFileSize : 'Tamaño desconocido',
UnpublishAdvertisementTemplateConfirmation : '¿Desea realmente deshacer la publicación de la plantilla de material publicitario?',
UnpublishAdvertisementTemplateLabel : 'Deshacer la publicación de la plantilla de material publicitario',
UploadFileQuestion : '¿Desea realmente cargar el archivo "{0}" en el servidor?',
ValueCantBeEmpty : 'El valor no puede estar vacío',
Wednesday : 'Miércoles',
WorkInProgressPleaseStandBy : 'Realizando tarea. Por favor, espere...',
Yes : 'Sí',
YouHaveToChooseLegalPersonToPrintOrder : 'Para la preparación de los documentos para publicar es necesario especificar la Persona jurídica del contratante',
YouHaveToSaveOrderToPrint : 'Para la preparación de documentos para publicar es necesario guardar la orden'
}
