//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using DoubleGis.Erm.Platform.Model.Entities.Interfaces;
using DoubleGis.Erm.Platform.Model.Entities.Interfaces.Integration;

namespace DoubleGis.Erm.Platform.Model.Entities.Erm
{
    public sealed partial class DictionaryEntityPropertyInstance : 
        IEntity
    {
        public long EntityInstanceId { get; set; }
        public int PropertyId { get; set; }
        public string TextValue { get; set; }
        public Nullable<decimal> NumericValue { get; set; }
        public Nullable<System.DateTime> DateTimeValue { get; set; }
    
        public DictionaryEntityInstance DictionaryEntityInstance { get; set; }
    
    
    	override public int GetHashCode()
    	{
    		return base.GetHashCode();
    	}
    }
}
