#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoubleGis.Erm.BL.UI.Web.Mvc.Views.Order
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DoubleGis.Erm.BL.UI.Web.Mvc.Models;
    using DoubleGis.Erm.BLCore.Resources.Server.Properties;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Controllers;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Models;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Utils;
    using DoubleGis.Erm.Platform.Common;
    using DoubleGis.Erm.Platform.Model.Entities;
    using DoubleGis.Erm.Platform.Model.Entities.Enums;
    using DoubleGis.Erm.Platform.Model.Metadata.Enums;
    using DoubleGis.Erm.Platform.UI.Web.Mvc;
    using DoubleGis.Erm.Platform.UI.Web.Mvc.Utils;
    using NuClear.Model.Common.Entities;
    using NuClear.Model.Common.Operations.Identity;
    using NuClear.Model.Common.Operations.Identity.Generic;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Order/CheckOrdersReadinessForReleaseDialog.cshtml")]
    public partial class CheckOrdersReadinessForReleaseDialog : System.Web.Mvc.WebViewPage<CheckOrdersReadinessForReleaseDialogViewModel>
    {
        public CheckOrdersReadinessForReleaseDialog()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
  
    Layout = "../Shared/_DialogLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("Title", () => {

WriteLiteral(" ");

            
            #line 9 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
            Write(BLResources.OrdersReadinessForReleaseReportTitle);

            
            #line default
            #line hidden
WriteLiteral(" ");

});

DefineSection("TopBarTitle", () => {

WriteLiteral(" ");

            
            #line 10 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
                  Write(BLResources.OrdersReadinessForReleaseReportTitle);

            
            #line default
            #line hidden
WriteLiteral(" ");

});

DefineSection("TopBarMessage", () => {

WriteLiteral(" ");

            
            #line 11 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
                    Write(BLResources.OrdersReadinessForReleaseReportParametersInformation);

            
            #line default
            #line hidden
WriteLiteral(" ");

});

WriteLiteral("\r\n");

DefineSection("PageContent", () => {

WriteLiteral("\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 453), Tuple.Create("\"", 522)
, Tuple.Create(Tuple.Create("", 460), Tuple.Create("/Content/Ext.ux.DetailedProgressWindow.css?", 460), true)
            
            #line 15 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
             , Tuple.Create(Tuple.Create("", 503), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 503), false)
);

WriteLiteral(" />\r\n    \r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 545), Tuple.Create("\"", 612)
, Tuple.Create(Tuple.Create("", 551), Tuple.Create("/Scripts/Ext.ux.DetailedProgressWindow.js?", 551), true)
            
            #line 17 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
, Tuple.Create(Tuple.Create("", 593), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 593), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 659), Tuple.Create("\"", 731)
, Tuple.Create(Tuple.Create("", 665), Tuple.Create("/Scripts/Ext.ux.AsyncOperationClientManager.js?", 665), true)
            
            #line 18 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
, Tuple.Create(Tuple.Create("", 712), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 712), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    Ext.onReady(function ()
    {
        if (Ext.getDom('ErrorsLink'))
        {
            Ext.getDom('ErrorsLink').onclick = function ()
            {
                Ext.getDom('ErrorsForm').submit();
            };
        }

        //Show error messages
        if (Ext.getDom(""Notifications"").innerHTML.trim() != """")
        {
            Ext.get(""Notifications"").addClass(""Notifications"");
        }
        else
        {
            Ext.get(""Notifications"").removeClass(""Notifications"");
        }

        Ext.get(""Cancel"").on(""click"", function ()
        {
            window.close();
        });

        Ext.get(""OK"").on(""click"", function ()
        {
            if (Ext.DoubleGis.FormValidator.validate(EntityForm))
            {
                Ext.getDom(""OK"").disabled = true;
                EntityForm.submit();
            }
        });

        // Временно отключаем галку ""Включая подчинённых"", ERM-925
        var tt = new Ext.ToolTip({
            target: 'IncludeOwnerDescendants-wrapper',
            html: Ext.LocalizedResources.DisabledFunctionality
        });
    });

    </script>
    
");

            
            #line 64 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
    
            
            #line default
            #line hidden
            
            #line 64 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
     if(Model.HasErrors == true)
    {

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" style=\"height: 8px; padding-left: 5px;padding-top: 4px;position: fixed;\"");

WriteLiteral(" id=\"DivErrors\"");

WriteLiteral(">\r\n");

            
            #line 67 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
        
            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
         using(Html.BeginForm("GetOperationLog", "Operation", FormMethod.Post, new Dictionary<string, object> { { "target", "_blank" }, {"id", "ErrorsForm"} }))
        {

            
            #line default
            #line hidden
WriteLiteral("            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"operationId\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2335), Tuple.Create("\"", 2364)
            
            #line 69 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
, Tuple.Create(Tuple.Create("", 2343), Tuple.Create<System.Object, System.Int32>(Model.ErrorLogFileId
            
            #line default
            #line hidden
, 2343), false)
);

WriteLiteral(" />\r\n");

            
            #line 70 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 72 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 74 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
    
            
            #line default
            #line hidden
            
            #line 74 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
     using (Html.BeginForm(null, null, null, FormMethod.Post, new Dictionary<string, object> { { "id", "EntityForm" } }))
    {
        
            
            #line default
            #line hidden
            
            #line 76 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
   Write(Html.Hidden("now", DateTime.UtcNow.ToString(CultureInfo.InvariantCulture)));

            
            #line default
            #line hidden
            
            #line 76 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
                                                                                   

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"Tab\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" style=\"height: 18px;\"");

WriteLiteral(" id=\"Notifications\"");

WriteLiteral(" class=\"Notifications\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 79 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
       Write(Model.Message);

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 80 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
            
            
            #line default
            #line hidden
            
            #line 80 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
             if (Model.HasErrors == true)
            {

            
            #line default
            #line hidden
WriteLiteral("                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" id=\"ErrorsLink\"");

WriteLiteral("> Просмотреть ошибки...</a>\r\n");

            
            #line 83 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n        <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 86 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
       Write(Html.TemplateField(m => m.StartPeriodDate, FieldFlex.lone, new CalendarSettings { Store = CalendarSettings.StoreMode.Relative, Display = CalendarSettings.DisplayMode.Month }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 89 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
       Write(Html.TemplateField(m => m.OrganizationUnit, FieldFlex.lone, new LookupSettings { EntityName = EntityType.Instance.OrganizationUnit() }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 92 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
       Write(Html.TemplateField(m => m.Owner, FieldFlex.lone, new LookupSettings { EntityName = EntityType.Instance.User()}));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 95 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
       Write(Html.TemplateField(m => m.IncludeOwnerDescendants, FieldFlex.lone, new Dictionary<string, object> {{"disabled", "disabled"}}));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 98 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
       Write(Html.TemplateField(m => m.CheckAccountBalance, FieldFlex.lone));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

            
            #line 101 "..\..\Views\Order\CheckOrdersReadinessForReleaseDialog.cshtml"
    }

            
            #line default
            #line hidden
});

        }
    }
}
#pragma warning restore 1591
