#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoubleGis.Erm.BL.UI.Web.Mvc.Views.Order
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DoubleGis.Erm.BL.UI.Web.Mvc.Models;
    using DoubleGis.Erm.BLCore.Resources.Server.Properties;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Controllers;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Models;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Utils;
    using DoubleGis.Erm.Platform.Common;
    using DoubleGis.Erm.Platform.Model.Entities;
    using DoubleGis.Erm.Platform.Model.Entities.Enums;
    using DoubleGis.Erm.Platform.Model.Metadata.Enums;
    using DoubleGis.Erm.Platform.UI.Web.Mvc;
    using DoubleGis.Erm.Platform.UI.Web.Mvc.Utils;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Order/CloseWithDenial.cshtml")]
    public partial class CloseWithDenial : System.Web.Mvc.WebViewPage<CloseOrderWithDenialViewModel>
    {
        public CloseWithDenial()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Order\CloseWithDenial.cshtml"
  
    Layout = "../Shared/_DialogLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("Title", () => {

WriteLiteral(" ");

            
            #line 8 "..\..\Views\Order\CloseWithDenial.cshtml"
            Write(BLResources.CloseWithDenial);

            
            #line default
            #line hidden
WriteLiteral(" ");

});

DefineSection("TopBarTitle", () => {

WriteLiteral(" ");

            
            #line 9 "..\..\Views\Order\CloseWithDenial.cshtml"
                  Write(BLResources.CloseWithDenial);

            
            #line default
            #line hidden
WriteLiteral(" ");

});

DefineSection("TopBarMessage", () => {

WriteLiteral(" ");

            
            #line 10 "..\..\Views\Order\CloseWithDenial.cshtml"
                    Write(Model.Confirmation);

            
            #line default
            #line hidden
WriteLiteral(" ");

});

WriteLiteral("\r\n");

DefineSection("PageContent", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        Ext.onReady(function ()\r\n        {\r\n            var depList = window.E" +
"xt.getDom(\"ViewConfig_DependencyList\");\r\n            if (depList.value)\r\n       " +
"     {\r\n                this.DependencyHandler = new window.Ext.DoubleGis.Depend" +
"encyHandler();\r\n                this.DependencyHandler.register(window.Ext.decod" +
"e(depList.value), window.EntityForm);\r\n            }\r\n            depList.value " +
"= null;\r\n\r\n            if (Ext.getDom(\"Notifications\").innerHTML.trim() != \"\")\r\n" +
"            {\r\n                Ext.getDom(\"Notifications\").style.display = \"bloc" +
"k\";\r\n            }\r\n\r\n            Ext.get(\"Cancel\").on(\"click\", function () { wi" +
"ndow.close(); });\r\n\r\n            if (Ext.getDom(\"CanClose\").checked)\r\n          " +
"  {\r\n                Ext.get(\"OK\").on(\"click\", function ()\r\n                {\r\n " +
"                   if (Ext.DoubleGis.FormValidator.validate(window.EntityForm))\r" +
"\n                    {\r\n                        submitForm();\r\n                 " +
"   }\r\n                });\r\n            }\r\n            else\r\n            {\r\n     " +
"           Ext.getDom(\"Cancel\").value = Ext.getDom(\"OK\").value;\r\n               " +
" Ext.get(\"OK\").hide();\r\n            }\r\n        });\r\n\r\n        var submitForm = f" +
"unction ()\r\n        {\r\n            Ext.getDom(\"OK\").disabled = \"disabled\";\r\n    " +
"        Ext.getDom(\"Cancel\").disabled = \"disabled\";\r\n            window.Ext.get(" +
"\"Notifications\").removeClass(\"Notifications\");\r\n            Ext.getDom(\"Reason\")" +
".disabled = true;\r\n            Ext.get(\"Reason\").addClass(\"readonly\");\r\n\r\n      " +
"      var callLink = \"/Order/CloseWithDenial\";\r\n\r\n            window.Ext.Ajax.re" +
"quest({\r\n                timeout: 1200000,\r\n                url: callLink,\r\n    " +
"            params:\r\n                {\r\n                    orderId: Ext.getDom(" +
"\"OrderId\").value,\r\n                    reason: window.Ext.getDom(\"Reason\").value" +
"\r\n                },\r\n                method: \'POST\',\r\n                success: " +
"function ()\r\n                {\r\n                    window.returnValue = true;\r\n" +
"                    window.close();\r\n                },\r\n                failure" +
": fail\r\n            });\r\n        };\r\n\r\n        var fail = function (xmlHttpReque" +
"st)\r\n        {\r\n            window.Ext.getDom(\"Notifications\").innerHTML = xmlHt" +
"tpRequest.responseText;\r\n            window.Ext.get(\"Notifications\").addClass(\"N" +
"otifications\");\r\n            Ext.getDom(\"Notifications\").style.display = \"block\"" +
";\r\n\r\n            window.Ext.getDom(\"OK\").disabled = false;\r\n            window.E" +
"xt.getDom(\"Cancel\").disabled = false;\r\n\r\n            window.Ext.getDom(\"Reason\")" +
".disabled = false;\r\n            window.Ext.get(\"Reason\").removeClass(\"readonly\")" +
";\r\n        };\r\n    </script>\r\n");

            
            #line 90 "..\..\Views\Order\CloseWithDenial.cshtml"
    
            
            #line default
            #line hidden
            
            #line 90 "..\..\Views\Order\CloseWithDenial.cshtml"
     using (Html.BeginForm(null, null, null, FormMethod.Post, new Dictionary<string, object> { { "id", "EntityForm" } }))
    {

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"Tab\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" style=\"display: none; height: 20px;\"");

WriteLiteral(" id=\"Notifications\"");

WriteLiteral(" class=\"Notifications\"");

WriteLiteral(">");

            
            #line 93 "..\..\Views\Order\CloseWithDenial.cshtml"
                                                                                      Write(Model.Message);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("        ");

            
            #line 94 "..\..\Views\Order\CloseWithDenial.cshtml"
   Write(Html.HiddenFor(m => m.OrderId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 95 "..\..\Views\Order\CloseWithDenial.cshtml"
   Write(Html.Hidden("ViewConfig_DependencyList", Model.ViewConfig.DependencyList));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">");

            
            #line 96 "..\..\Views\Order\CloseWithDenial.cshtml"
                               Write(Html.CheckBoxFor(m => m.CanClose));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n        <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 99 "..\..\Views\Order\CloseWithDenial.cshtml"
       Write(Html.TemplateField(m => m.Reason, FieldFlex.lone, new Dictionary<string, object> { { "rows", "5" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n    </div>\r\n");

            
            #line 103 "..\..\Views\Order\CloseWithDenial.cshtml"
    }

            
            #line default
            #line hidden
});

        }
    }
}
#pragma warning restore 1591
