#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoubleGis.Erm.BLCore.UI.Web.Mvc.Views.GroupOperation
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DoubleGis.Erm.BLCore.Resources.Server.Properties;
    
    #line 1 "..\..\Views\GroupOperation\Delete.cshtml"
    using DoubleGis.Erm.BLCore.UI.Metadata.Confirmations;
    
    #line default
    #line hidden
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Controllers;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Models;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Settings;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.UserProfiles;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Utils;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.ViewModels;
    using DoubleGis.Erm.Platform.Common;
    
    #line 2 "..\..\Views\GroupOperation\Delete.cshtml"
    using DoubleGis.Erm.Platform.Common.Utils;
    
    #line default
    #line hidden
    using DoubleGis.Erm.Platform.Model.Entities;
    using DoubleGis.Erm.Platform.Model.Entities.Enums;
    
    #line 3 "..\..\Views\GroupOperation\Delete.cshtml"
    using DoubleGis.Erm.Platform.Model.Identities.Operations.Identity;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\GroupOperation\Delete.cshtml"
    using DoubleGis.Erm.Platform.Model.Identities.Operations.Identity.Generic;
    
    #line default
    #line hidden
    using DoubleGis.Erm.Platform.Model.Metadata.Enums;
    using DoubleGis.Erm.Platform.UI.Web.Mvc;
    using DoubleGis.Erm.Platform.UI.Web.Mvc.Security;
    using DoubleGis.Erm.Platform.UI.Web.Mvc.Utils;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/GroupOperation/Delete.cshtml")]
    public partial class Delete : System.Web.Mvc.WebViewPage<DoubleGis.Erm.BLCore.UI.Web.Mvc.Models.GroupOperation.GroupOperationViewModel>
    {
        public Delete()
        {
        }
        public override void Execute()
        {
            
            #line 7 "..\..\Views\GroupOperation\Delete.cshtml"
  
    Layout = "../Shared/_DialogLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("Title", () => {

WriteLiteral(" ");

            
            #line 11 "..\..\Views\GroupOperation\Delete.cshtml"
            Write(BLResources.DeleteConfirmation);

            
            #line default
            #line hidden
WriteLiteral(" ");

});

DefineSection("TopBarTitle", () => {

WriteLiteral(" ");

            
            #line 12 "..\..\Views\GroupOperation\Delete.cshtml"
                  Write(BLResources.DeleteConfirmation);

            
            #line default
            #line hidden
WriteLiteral(" ");

});

DefineSection("TopBarMessage", () => {

WriteLiteral(" ");

            
            #line 13 "..\..\Views\GroupOperation\Delete.cshtml"
                    Write(string.Format(BLResources.GroupOperationTopBarMessage, Model.EntityTypeName.ToStringLocalized(EnumResources.ResourceManager, EnumResources.Culture)));

            
            #line default
            #line hidden
WriteLiteral(" ");

});

WriteLiteral("\r\n");

DefineSection("PageContent", () => {

WriteLiteral("\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 745), Tuple.Create("\"", 793)
, Tuple.Create(Tuple.Create("", 752), Tuple.Create("/Content/Progress.css?", 752), true)
            
            #line 17 "..\..\Views\GroupOperation\Delete.cshtml"
, Tuple.Create(Tuple.Create("", 774), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 774), false)
);

WriteLiteral(" />\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 812), Tuple.Create("\"", 870)
, Tuple.Create(Tuple.Create("", 818), Tuple.Create("/Scripts/Ext.Ajax.syncRequest.js?", 818), true)
            
            #line 19 "..\..\Views\GroupOperation\Delete.cshtml"
, Tuple.Create(Tuple.Create("", 851), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 851), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 917), Tuple.Create("\"", 983)
, Tuple.Create(Tuple.Create("", 923), Tuple.Create("/Scripts/DoubleGis.UI.GroupOperations.js?", 923), true)
            
            #line 20 "..\..\Views\GroupOperation\Delete.cshtml"
, Tuple.Create(Tuple.Create("", 964), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 964), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1030), Tuple.Create("\"", 1075)
, Tuple.Create(Tuple.Create("", 1036), Tuple.Create("/Scripts/Tooltip.js?", 1036), true)
            
            #line 21 "..\..\Views\GroupOperation\Delete.cshtml"
, Tuple.Create(Tuple.Create("", 1056), Tuple.Create<System.Object, System.Int32>(ThisAssembly.Build
            
            #line default
            #line hidden
, 1056), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    \r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        Ext.namespace(\'Ext.DoubleGis.UI.Delete\');\r\n        Ext.DoubleGis.UI.De" +
"lete.DeleteProcessor = Ext.extend(Ext.DoubleGis.UI.GroupProcessor, {\r\n\t\t\tEntitie" +
"sToProcess: {},\r\n\t\t\tconstructor: function(config) {\r\n                Ext.DoubleG" +
"is.UI.Delete.DeleteProcessor.superclass.constructor.call(this, config);\r\n\t\t\t\tif " +
"(config.EntitiesToProcess) {\r\n\t\t\t\t\tvar entitiesToProcess = {};\r\n\t\t\t\t\tExt.each(co" +
"nfig.EntitiesToProcess, function (x) {\r\n\t\t\t\t\t\tentitiesToProcess[x.entityId] = x." +
"entityName;\r\n\t\t\t\t\t});\r\n\t\t\t\t\tthis.EntitiesToProcess = entitiesToProcess;\r\n\t\t\t\t}\r\n" +
"            },\r\n\t\t\tIsUserSettingsValid: function() {\r\n                return tru" +
"e;\r\n            },\r\n\t\t\tResolveEntityName: function(entityId) {\r\n\t\t\t\tif (this.Ent" +
"itiesToProcess.hasOwnProperty(entityId))\r\n\t\t\t\t\treturn this.EntitiesToProcess[ent" +
"ityId];\r\n\t\t\t\telse \r\n\t\t\t\t\treturn this.superclass().ResolveEntityName.call(this, e" +
"ntityId);\r\n\t\t\t},\r\n            CreateParamsForControllerCall: function (entityId)" +
" {\r\n                return { entityId: entityId };\r\n            }\r\n        });\r\n" +
"\t\tExt.onReady(function() {\r\n            Ext.getDom(\'PageContentCell\').style[\"ver" +
"tical-align\"] = \"top\";\r\n\r\n\t\t\tvar dialogArguments = !window.dialogArguments ? [] " +
": (window.dialogArguments.Values ? window.dialogArguments.Values : window.dialog" +
"Arguments);\r\n\t\t\tvar ids = dialogArguments;\r\n\r\n\t\t\tvar isExtendedMode = (dialogArg" +
"uments != null && dialogArguments.length > 0 && dialogArguments[0].hasOwnPropert" +
"y(\'entityId\'));\r\n\t\t\tif (isExtendedMode) {\r\n\t\t\t\tids = [];\r\n\t\t\t\tExt.each(dialogArg" +
"uments, function(x) { ids.push(x.entityId); });\r\n\t\t\t}\r\n\r\n            var config " +
"= {\r\n\t\t\t\tEntitiesToProcess: isExtendedMode ? dialogArguments : null,\r\n\t\t\t\tEntiti" +
"es: ids, // массив id сущностейsss\r\n                OperationName: \'");

            
            #line 65 "..\..\Views\GroupOperation\Delete.cshtml"
                           Write(Model.OperationName);

            
            #line default
            #line hidden
WriteLiteral(@"', // тип операции - Qualify, Assign, ChangeTerritory
                CloseButtonText: Ext.LocalizedResources.Close, // локализованная надпись для кнопки закрыть
                NeedToSelectOneOrMoreItemsMsg: Ext.LocalizedResources.NeedToSelectOneOrMoreItems, // локализованная надпись о том что нужно выбрать один или несколько элементов
                ResultMessageTitle: Ext.LocalizedResources.GroupOperationResultsTitle, // локализованная надпись - заголовок для результатов операции
                ResultMessageTemplate: Ext.LocalizedResources.GroupOperationResultsMessage // локализованная надпись - шаблон строки для результатов операции
            };
            var deleteProcessor = new Ext.DoubleGis.UI.Delete.DeleteProcessor(config);
            if (!deleteProcessor.CheckProcessingPossibility()) {
                return;
            }
            deleteProcessor.Process();
        });
    </script>
    <table");

WriteLiteral(" cellspacing=\"5\"");

WriteLiteral(" cellpadding=\"5\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" height=\"100px\"");

WriteLiteral(">\r\n        <tr>\r\n            <td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" style=\"height: 30px;\"");

WriteLiteral(" id=\"Notifications\"");

WriteAttribute("onmouseover", Tuple.Create(" \r\n\t\t\t\t     onmouseover=\"", 4028), Tuple.Create("\"", 4082)
, Tuple.Create(Tuple.Create(" ", 4053), Tuple.Create("AddTooltip(", 4054), true)
            
            #line 82 "..\..\Views\GroupOperation\Delete.cshtml"
, Tuple.Create(Tuple.Create("", 4065), Tuple.Create<System.Object, System.Int32>(Model.Message
            
            #line default
            #line hidden
, 4065), false)
, Tuple.Create(Tuple.Create("", 4079), Tuple.Create(");", 4079), true)
, Tuple.Create(Tuple.Create(" ", 4081), Tuple.Create("", 4081), true)
);

WriteLiteral(" \r\n\t\t\t\t     onmouseout=\" RemoveTooltip(); \"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 84 "..\..\Views\GroupOperation\Delete.cshtml"
               Write(Model.Message);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n       " +
"     <td>\r\n                <span");

WriteLiteral(" id=\"bodyMessage\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 91 "..\..\Views\GroupOperation\Delete.cshtml"
               Write(ConfirmationManager.GetConfirmation(new StrictOperationIdentity(DeleteIdentity.Instance, new EntitySet(Model.EntityTypeName))));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </span>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n      " +
"      <td>\r\n                <div");

WriteLiteral(" id=\"pbDiv\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"pbInner\"");

WriteLiteral(">\r\n                    </div>\r\n                </div>\r\n            </td>\r\n       " +
" </tr>\r\n    </table>\r\n");

WriteLiteral("    ");

            
            #line 104 "..\..\Views\GroupOperation\Delete.cshtml"
Write(Html.HiddenFor(x => x.EntityTypeName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
