#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoubleGis.Erm.BLFlex.UI.Web.Mvc.Global.Areas.MultiCulture.Views.ChangeBindingObjects
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DoubleGis.Erm.BL.UI.Web.Mvc.Models;
    using DoubleGis.Erm.BLCore.Resources.Server.Properties;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Controllers;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Models;
    
    #line 1 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Settings;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.UserProfiles;
    
    #line default
    #line hidden
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Utils;
    using DoubleGis.Erm.Platform.Common;
    using DoubleGis.Erm.Platform.Model.Entities;
    using DoubleGis.Erm.Platform.Model.Entities.Enums;
    using DoubleGis.Erm.Platform.Model.Metadata.Enums;
    using DoubleGis.Erm.Platform.UI.Web.Mvc;
    
    #line 3 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
    using DoubleGis.Erm.Platform.UI.Web.Mvc.Security;
    
    #line default
    #line hidden
    using DoubleGis.Erm.Platform.UI.Web.Mvc.Utils;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/MultiCulture/Views/ChangeBindingObjects/ChangeBindingObjects.cshtml")]
    public partial class ChangeBindingObjects : System.Web.Mvc.WebViewPage<DoubleGis.Erm.BLFlex.UI.Web.Mvc.Global.Models.MultiCultureOrderPositionViewModel>
    {
        public ChangeBindingObjects()
        {
        }
        public override void Execute()
        {
WriteLiteral("<html");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral(">\r\n    <head>\r\n        <base");

WriteLiteral(" target=\"_self\"");

WriteLiteral(" />\r\n\r\n        <meta");

WriteLiteral(" id=\"meta_IsDebug\"");

WriteLiteral(" name=\"meta_IsDebug\"");

WriteAttribute("content", Tuple.Create(" content=\"", 388), Tuple.Create("\"", 437)
            
            #line 10 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 398), Tuple.Create<System.Object, System.Int32>(HttpContext.Current.IsDebuggingEnabled
            
            #line default
            #line hidden
, 398), false)
);

WriteLiteral(" />\r\n        <meta");

WriteLiteral(" id=\"meta_Revision\"");

WriteLiteral(" name=\"meta_Revision\"");

WriteAttribute("content", Tuple.Create(" content=\"", 496), Tuple.Create("\"", 540)
            
            #line 11 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 506), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 506), false)
);

WriteLiteral(" />\r\n    \r\n        <link");

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" href=\"/favicon.ico\"");

WriteLiteral(" />\r\n        <link");

WriteLiteral(" rel=\"icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" href=\"/favicon.ico\"");

WriteLiteral("/>\r\n        \r\n");

            
            #line 16 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
        
            
            #line default
            #line hidden
            
            #line 16 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
         if (HttpContext.Current.IsDebuggingEnabled)
        {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 788), Tuple.Create("\"", 855)
, Tuple.Create(Tuple.Create("", 794), Tuple.Create("/Scripts/ext-base-debug.js?", 794), true)
            
            #line 18 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 821), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 821), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 906), Tuple.Create("\"", 983)
, Tuple.Create(Tuple.Create("", 912), Tuple.Create("/Scripts/ext-all-debug-w-comments.js?", 912), true)
            
            #line 19 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 949), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 949), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

            
            #line 20 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1070), Tuple.Create("\"", 1131)
, Tuple.Create(Tuple.Create("", 1076), Tuple.Create("/Scripts/ext-base.js?", 1076), true)
            
            #line 23 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 1097), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 1097), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1182), Tuple.Create("\"", 1242)
, Tuple.Create(Tuple.Create("", 1188), Tuple.Create("/Scripts/ext-all.js?", 1188), true)
            
            #line 24 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 1208), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 1208), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

            
            #line 25 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1306), Tuple.Create("\"", 1448)
, Tuple.Create(Tuple.Create("", 1312), Tuple.Create("/Scripts/", 1312), true)
            
            #line 27 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 1321), Tuple.Create<System.Object, System.Int32>("Ext.LocalizedResources." + ViewData.GetUserLocaleInfo().TwoLetterISOLanguageName + ".js"
            
            #line default
            #line hidden
, 1321), false)
, Tuple.Create(Tuple.Create("", 1413), Tuple.Create("?", 1413), true)
            
            #line 27 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                                           , Tuple.Create(Tuple.Create("", 1414), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 1414), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n            Ext.USER_ID = ");

            
            #line 30 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                     Write(ViewData.GetUserIdentityInfo().Code);

            
            #line default
            #line hidden
WriteLiteral(";\r\n            Ext.USER_NAME = ");

            
            #line 31 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                       Write(ViewData.GetUserIdentityDisplayName());

            
            #line default
            #line hidden
WriteLiteral(";\r\n            Ext.CultureInfo = ");

            
            #line 32 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                         Write(Html.WriteJson(ViewData.GetUserLocaleInfo()));

            
            #line default
            #line hidden
WriteLiteral(";\r\n            Ext.CultureInfo.NumberFormatInfo.CurrencySymbol = \'");

            
            #line 33 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                                                          Write(ViewData.GetErmBaseCurrencySymbol());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n            Ext.CRM_URL = \'");

            
            #line 34 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                      Write(ViewData.GetMsCrmSettingsUrl());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n            Ext.BasicOperationsServiceRestUrl = \'");

            
            #line 35 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                                            Write(ViewData.GetBasicOperationsServiceRestUrl());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n            Ext.SpecialOperationsServiceRestUrl = \'");

            
            #line 36 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                                              Write(ViewData.GetSpecialOperationsServiceRestUrl());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        </script>\r\n        \r\n        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2177), Tuple.Create("\"", 2239)
, Tuple.Create(Tuple.Create("", 2184), Tuple.Create("/Content/ext-all.css?", 2184), true)
            
            #line 39 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 2205), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 2205), false)
);

WriteLiteral(" />\r\n        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2291), Tuple.Create("\"", 2354)
, Tuple.Create(Tuple.Create("", 2298), Tuple.Create("/Content/ext-mask.css?", 2298), true)
            
            #line 40 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 2320), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 2320), false)
);

WriteLiteral(" />\r\n        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2406), Tuple.Create("\"", 2471)
, Tuple.Create(Tuple.Create("", 2413), Tuple.Create("/Content/ext-extend.css?", 2413), true)
            
            #line 41 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 2437), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 2437), false)
);

WriteLiteral(" />\r\n        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2523), Tuple.Create("\"", 2593)
, Tuple.Create(Tuple.Create("", 2530), Tuple.Create("/Content/ext-ux-treegrid.css?", 2530), true)
            
            #line 42 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
  , Tuple.Create(Tuple.Create("", 2559), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 2559), false)
);

WriteLiteral(" />\r\n        \r\n        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2655), Tuple.Create("\"", 2714)
, Tuple.Create(Tuple.Create("", 2662), Tuple.Create("/Content/CRM4.css?", 2662), true)
            
            #line 44 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 2680), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 2680), false)
);

WriteLiteral(" />\r\n        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2766), Tuple.Create("\"", 2825)
, Tuple.Create(Tuple.Create("", 2773), Tuple.Create("/Content/Card.css?", 2773), true)
            
            #line 45 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 2791), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 2791), false)
);

WriteLiteral(" />\r\n        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2877), Tuple.Create("\"", 2946)
, Tuple.Create(Tuple.Create("", 2884), Tuple.Create("/Content/order-position.css?", 2884), true)
            
            #line 46 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
 , Tuple.Create(Tuple.Create("", 2912), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 2912), false)
);

WriteLiteral(" />\r\n        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2998), Tuple.Create("\"", 3068)
, Tuple.Create(Tuple.Create("", 3005), Tuple.Create("/Content/AsyncFileUpload.css?", 3005), true)
            
            #line 47 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
  , Tuple.Create(Tuple.Create("", 3034), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 3034), false)
);

WriteLiteral(" />\r\n        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3120), Tuple.Create("\"", 3186)
, Tuple.Create(Tuple.Create("", 3127), Tuple.Create("/Content/LookupStyle.css?", 3127), true)
            
            #line 48 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 3152), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 3152), false)
);

WriteLiteral(" />\r\n        \r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3217), Tuple.Create("\"", 3295)
, Tuple.Create(Tuple.Create("", 3223), Tuple.Create("/Scripts/DoubleGis.GlobalVariables.js?", 3223), true)
            
            #line 50 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 3261), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 3261), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3346), Tuple.Create("\"", 3418)
, Tuple.Create(Tuple.Create("", 3352), Tuple.Create("/Scripts/Common.ErrorHandler.js?", 3352), true)
            
            #line 51 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 3384), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 3384), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3469), Tuple.Create("\"", 3540)
, Tuple.Create(Tuple.Create("", 3475), Tuple.Create("/Scripts/Ext.ux.LookupField.js?", 3475), true)
            
            #line 52 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 3506), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 3506), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3591), Tuple.Create("\"", 3660)
, Tuple.Create(Tuple.Create("", 3597), Tuple.Create("/Scripts/Ext.ux.LinkField.js?", 3597), true)
            
            #line 53 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 3626), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 3626), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3711), Tuple.Create("\"", 3779)
, Tuple.Create(Tuple.Create("", 3717), Tuple.Create("/Scripts/Ext.ux.Calendar.js?", 3717), true)
            
            #line 54 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 3745), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 3745), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3830), Tuple.Create("\"", 3906)
, Tuple.Create(Tuple.Create("", 3836), Tuple.Create("/Scripts/Ext.ux.LookupFieldOwner.js?", 3836), true)
            
            #line 55 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 3872), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 3872), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3957), Tuple.Create("\"", 4036)
, Tuple.Create(Tuple.Create("", 3963), Tuple.Create("/Scripts/DoubleGis.MvcFormValidator.js?", 3963), true)
            
            #line 56 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 4002), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 4002), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4087), Tuple.Create("\"", 4167)
, Tuple.Create(Tuple.Create("", 4093), Tuple.Create("/Scripts/DoubleGis.DependencyHandler.js?", 4093), true)
            
            #line 57 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 4133), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 4133), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4218), Tuple.Create("\"", 4296)
, Tuple.Create(Tuple.Create("", 4224), Tuple.Create("/Scripts/DoubleGis.UI.DialogWindow.js?", 4224), true)
            
            #line 58 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 4262), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 4262), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n        \r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4357), Tuple.Create("\"", 4431)
, Tuple.Create(Tuple.Create("", 4363), Tuple.Create("/Scripts/Ext.ux.TreeGridSorter.js?", 4363), true)
            
            #line 60 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 4397), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 4397), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4482), Tuple.Create("\"", 4563)
, Tuple.Create(Tuple.Create("", 4488), Tuple.Create("/Scripts/Ext.ux.TreeGridColumnResizer.js?", 4488), true)
            
            #line 61 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 4529), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 4529), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4614), Tuple.Create("\"", 4688)
, Tuple.Create(Tuple.Create("", 4620), Tuple.Create("/Scripts/Ext.ux.TreeGridNodeUI.js?", 4620), true)
            
            #line 62 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 4654), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 4654), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4739), Tuple.Create("\"", 4813)
, Tuple.Create(Tuple.Create("", 4745), Tuple.Create("/Scripts/Ext.ux.TreeGridLoader.js?", 4745), true)
            
            #line 63 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 4779), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 4779), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4864), Tuple.Create("\"", 4939)
, Tuple.Create(Tuple.Create("", 4870), Tuple.Create("/Scripts/Ext.ux.TreeGridColumns.js?", 4870), true)
            
            #line 64 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 4905), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 4905), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4990), Tuple.Create("\"", 5058)
, Tuple.Create(Tuple.Create("", 4996), Tuple.Create("/Scripts/Ext.ux.TreeGrid.js?", 4996), true)
            
            #line 65 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 5024), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 5024), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5109), Tuple.Create("\"", 5180)
, Tuple.Create(Tuple.Create("", 5115), Tuple.Create("/Scripts/Ext.ux.FitToParent.js?", 5115), true)
            
            #line 66 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 5146), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 5146), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n        \r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5241), Tuple.Create("\"", 5311)
, Tuple.Create(Tuple.Create("", 5247), Tuple.Create("/Scripts/DoubleGis.UI.Card.js?", 5247), true)
            
            #line 68 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 5277), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 5277), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5362), Tuple.Create("\"", 5445)
, Tuple.Create(Tuple.Create("", 5368), Tuple.Create("/Scripts/Ext.DoubleGis.UI.OrderPosition.js?", 5368), true)
            
            #line 69 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 5411), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 5411), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5496), Tuple.Create("\"", 5593)
, Tuple.Create(Tuple.Create("", 5502), Tuple.Create("/Scripts/Ext.DoubleGis.UI.OrderPosition.BusinessLogic.js?", 5502), true)
            
            #line 70 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 5559), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 5559), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5644), Tuple.Create("\"", 5741)
, Tuple.Create(Tuple.Create("", 5650), Tuple.Create("/Scripts/Ext.DoubleGis.UI.OrderPosition.LinkingObject.js?", 5650), true)
            
            #line 71 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 5707), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 5707), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5792), Tuple.Create("\"", 5899)
, Tuple.Create(Tuple.Create("", 5798), Tuple.Create("/Scripts/Ext.DoubleGis.UI.OrderPosition.AdvertisementController.js?", 5798), true)
            
            #line 72 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
        , Tuple.Create(Tuple.Create("", 5865), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 5865), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5950), Tuple.Create("\"", 6033)
, Tuple.Create(Tuple.Create("", 5956), Tuple.Create("/Scripts/Ext.DoubleGis.UI.BindingObject.js?", 5956), true)
            
            #line 73 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 5999), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 5999), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    \r\n        <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n            .display-wrapper .captionRadioDiv { padding-top: 0px; }\r\n         " +
"   div.label-wrapper { width: 140px; }\r\n            div.Tab { padding: 0px; }\r\n " +
"       </style>\r\n        \r\n        <title>");

            
            #line 81 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
          Write(BLResources.BindingObjectChange);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    </head>\r\n    <body>\r\n        <table");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" height=\"100%\"");

WriteLiteral(" border=\"0\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(">\r\n            <tr>\r\n                <td");

WriteLiteral(" id=\"PageContentCell\"");

WriteLiteral(">\r\n");

            
            #line 87 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 87 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                     using (Html.BeginForm(null, null, null, FormMethod.Post, new Dictionary<string, object> { { "id", "EntityForm" }, { "autocomplete", "off" }, { "target", "_self" } }))
                    {
                        
            
            #line default
            #line hidden
            
            #line 89 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                   Write(Html.HiddenFor(m => m.Id));

            
            #line default
            #line hidden
            
            #line 89 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                                                  
                        
            
            #line default
            #line hidden
            
            #line 90 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                   Write(Html.HiddenFor(m => m.OrderId));

            
            #line default
            #line hidden
            
            #line 90 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                                                       
                        
            
            #line default
            #line hidden
            
            #line 91 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                   Write(Html.HiddenFor(m => m.OrderFirmId));

            
            #line default
            #line hidden
            
            #line 91 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                                                           
                        
            
            #line default
            #line hidden
            
            #line 92 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                   Write(Html.HiddenFor(m => m.OrganizationUnitId));

            
            #line default
            #line hidden
            
            #line 92 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                                                                  
                        
            
            #line default
            #line hidden
            
            #line 93 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                   Write(Html.HiddenFor(m => m.IsLocked));

            
            #line default
            #line hidden
            
            #line 93 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                                                        
                        
            
            #line default
            #line hidden
            
            #line 94 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                   Write(Html.HiddenFor(m => m.DiscountSum));

            
            #line default
            #line hidden
            
            #line 94 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                                                           
                        
            
            #line default
            #line hidden
            
            #line 95 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                   Write(Html.HiddenFor(m => m.IsComposite));

            
            #line default
            #line hidden
            
            #line 95 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                                                           

                        
            
            #line default
            #line hidden
            
            #line 97 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                   Write(Html.HiddenFor(m => m.DiscountPercent));

            
            #line default
            #line hidden
            
            #line 97 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                                                               
                        
            
            #line default
            #line hidden
            
            #line 98 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                   Write(Html.HiddenFor(m => m.AdvertisementsJson));

            
            #line default
            #line hidden
            
            #line 98 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                                                                  
                        
            
            #line default
            #line hidden
            
            #line 99 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                   Write(Html.HiddenFor(m => m.PricePosition));

            
            #line default
            #line hidden
            
            #line 99 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                                                             
                        
            
            #line default
            #line hidden
            
            #line 100 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                   Write(Html.HiddenFor(m => m.PricePerUnit));

            
            #line default
            #line hidden
            
            #line 100 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                                                            
                        
            
            #line default
            #line hidden
            
            #line 101 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                   Write(Html.HiddenFor(m => m.PricePerUnitWithVat));

            
            #line default
            #line hidden
            
            #line 101 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                                                                   
                        
            
            #line default
            #line hidden
            
            #line 102 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                   Write(Html.HiddenFor(m => m.Amount));

            
            #line default
            #line hidden
            
            #line 102 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                                                      
                        
            
            #line default
            #line hidden
            
            #line 103 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                   Write(Html.HiddenFor(m => m.ShipmentPlan));

            
            #line default
            #line hidden
            
            #line 103 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                                                            
                        
            
            #line default
            #line hidden
            
            #line 104 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                   Write(Html.HiddenFor(m => m.PayablePrice));

            
            #line default
            #line hidden
            
            #line 104 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                                                            
                        
            
            #line default
            #line hidden
            
            #line 105 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                   Write(Html.HiddenFor(m => m.PayablePlan));

            
            #line default
            #line hidden
            
            #line 105 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                                                           
                        
            
            #line default
            #line hidden
            
            #line 106 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                   Write(Html.HiddenFor(m => m.CalculateDiscountViaPercent));

            
            #line default
            #line hidden
            
            #line 106 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                                                                           
                        
            
            #line default
            #line hidden
            
            #line 107 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                   Write(Html.HiddenFor(m => m.DiscountSum));

            
            #line default
            #line hidden
            
            #line 107 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                                                           
                        
            
            #line default
            #line hidden
            
            #line 108 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                   Write(Html.HiddenFor(m => m.Comment));

            
            #line default
            #line hidden
            
            #line 108 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                                                       

            
            #line default
            #line hidden
WriteLiteral("                        <table");

WriteLiteral(" style=\"height: 100%; table-layout: fixed\"");

WriteLiteral(">\r\n                            <tr>\r\n                                <td>\r\n      " +
"                              <div");

WriteLiteral(" id=\'linkingObjectContainer\'");

WriteLiteral(" style=\"height: 100%; margin: 0px 5px 5px 5px; overflow: hidden; width: 100%;\"");

WriteLiteral(">\r\n                                    </div>\r\n                                </" +
"td>\r\n                            </tr>\r\n                        </table>\r\n");

            
            #line 117 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
                    }   

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n            </tr>\r\n            <tr>\r\n                <td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(" align=\"right\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" class=\"ms-crm-Dialog-Footer\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" class=\"CrmButton\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"OK\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8592), Tuple.Create("\"", 8615)
            
            #line 122 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 8600), Tuple.Create<System.Object, System.Int32>(BLResources.OK
            
            #line default
            #line hidden
, 8600), false)
);

WriteLiteral(" />\r\n                    <input");

WriteLiteral(" class=\"CrmButton\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"Cancel\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8691), Tuple.Create("\"", 8718)
            
            #line 123 "..\..\Areas\MultiCulture\Views\ChangeBindingObjects\ChangeBindingObjects.cshtml"
, Tuple.Create(Tuple.Create("", 8699), Tuple.Create<System.Object, System.Int32>(BLResources.Cancel
            
            #line default
            #line hidden
, 8699), false)
);

WriteLiteral(" />\r\n                </td>\r\n            </tr>\r\n        </table>\r\n    </body>\r\n</h" +
"tml>");

        }
    }
}
#pragma warning restore 1591
