#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoubleGis.Erm.BLCore.UI.Web.Mvc.Views.CreateOrUpdate
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DoubleGis.Erm.BLCore.Resources.Server.Properties;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Controllers;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Models;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Utils;
    using DoubleGis.Erm.Platform.Common;
    using DoubleGis.Erm.Platform.Model.Entities;
    using DoubleGis.Erm.Platform.Model.Entities.Enums;
    using DoubleGis.Erm.Platform.Model.Metadata.Enums;
    using DoubleGis.Erm.Platform.UI.Web.Mvc;
    using DoubleGis.Erm.Platform.UI.Web.Mvc.Utils;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CreateOrUpdate/AdvertisementElementTemplate.cshtml")]
    public partial class AdvertisementElementTemplate : System.Web.Mvc.WebViewPage<AdvertisementElementTemplateViewModel>
    {
        public AdvertisementElementTemplate()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\CreateOrUpdate\AdvertisementElementTemplate.cshtml"
  
    Layout = "../Shared/_CardLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("CardScripts", () => {

WriteLiteral("\r\n<style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n    DIV.label-wrapper\r\n    {\r\n        width: 160px;\r\n    }\r\n</style>\r\n");

});

WriteLiteral("\r\n");

DefineSection("CardBody", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 20 "..\..\Views\CreateOrUpdate\AdvertisementElementTemplate.cshtml"
Write(Html.HiddenFor(m => m.IdentityServiceUrl));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"Tab\"");

WriteLiteral(" id=\"MainTab\"");

WriteAttribute("title", Tuple.Create(" title=\"", 329), Tuple.Create("\"", 365)
            
            #line 21 "..\..\Views\CreateOrUpdate\AdvertisementElementTemplate.cshtml"
, Tuple.Create(Tuple.Create("", 337), Tuple.Create<System.Object, System.Int32>(BLResources.GeneralTabTitle
            
            #line default
            #line hidden
, 337), false)
);

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 23 "..\..\Views\CreateOrUpdate\AdvertisementElementTemplate.cshtml"
   Write(Html.EditableId(m => m.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 26 "..\..\Views\CreateOrUpdate\AdvertisementElementTemplate.cshtml"
   Write(Html.TemplateField(m => m.Name, FieldFlex.lone));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 29 "..\..\Views\CreateOrUpdate\AdvertisementElementTemplate.cshtml"
   Write(Html.TemplateField(m => m.RestrictionType, FieldFlex.lone, null, EnumResources.ResourceManager));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 32 "..\..\Views\CreateOrUpdate\AdvertisementElementTemplate.cshtml"
   Write(Html.TemplateField(m => m.FileSizeRestriction, FieldFlex.twins));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 33 "..\..\Views\CreateOrUpdate\AdvertisementElementTemplate.cshtml"
   Write(Html.TemplateField(m => m.FileNameLengthRestriction, FieldFlex.twins));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 36 "..\..\Views\CreateOrUpdate\AdvertisementElementTemplate.cshtml"
   Write(Html.TemplateField(m => m.ImageDimensionRestriction, FieldFlex.lone));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 39 "..\..\Views\CreateOrUpdate\AdvertisementElementTemplate.cshtml"
   Write(Html.TemplateField(m => m.TextLengthRestriction, FieldFlex.twins));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 40 "..\..\Views\CreateOrUpdate\AdvertisementElementTemplate.cshtml"
   Write(Html.TemplateField(m => m.TextLineBreaksCountRestriction, FieldFlex.twins));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 43 "..\..\Views\CreateOrUpdate\AdvertisementElementTemplate.cshtml"
   Write(Html.TemplateField(m => m.MaxSymbolsInWord, FieldFlex.twins));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 44 "..\..\Views\CreateOrUpdate\AdvertisementElementTemplate.cshtml"
   Write(Html.TemplateField(m => m.FormattedText, FieldFlex.twins));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 47 "..\..\Views\CreateOrUpdate\AdvertisementElementTemplate.cshtml"
   Write(Html.TemplateField(m => m.IsRequired, FieldFlex.twins));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 48 "..\..\Views\CreateOrUpdate\AdvertisementElementTemplate.cshtml"
   Write(Html.TemplateField(m => m.IsAdvertisementLink, FieldFlex.twins));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 51 "..\..\Views\CreateOrUpdate\AdvertisementElementTemplate.cshtml"
   Write(Html.TemplateField(m => m.NeedsValidation, FieldFlex.lone));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

WriteLiteral("    ");

            
            #line 53 "..\..\Views\CreateOrUpdate\AdvertisementElementTemplate.cshtml"
Write(Html.SectionHead("supportedFilesHeader", @BLResources.AllowedFileExtensions));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 55 "..\..\Views\CreateOrUpdate\AdvertisementElementTemplate.cshtml"
   Write(Html.TemplateField(m => m.IsPngSupported, FieldFlex.lone));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 58 "..\..\Views\CreateOrUpdate\AdvertisementElementTemplate.cshtml"
   Write(Html.TemplateField(m => m.IsGifSupported, FieldFlex.lone));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 61 "..\..\Views\CreateOrUpdate\AdvertisementElementTemplate.cshtml"
   Write(Html.TemplateField(m => m.IsBmpSupported, FieldFlex.lone));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 64 "..\..\Views\CreateOrUpdate\AdvertisementElementTemplate.cshtml"
   Write(Html.TemplateField(m => m.IsChmSupported, FieldFlex.lone));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n");

});

        }
    }
}
#pragma warning restore 1591
