//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable ConvertNullableToShortForm

using System;
using System.Collections.Generic;
using DoubleGis.Erm.Platform.Model.Entities.Interfaces;
using DoubleGis.Erm.Platform.Model.Entities.Interfaces.Integration;

namespace DoubleGis.Erm.Platform.Model.Entities.Erm
{
    public sealed partial class Account : 
        IEntity, 
        IEntityKey, 
        ICuratedEntity, 
        IAuditableEntity, 
        IDeletableEntity, 
        IDeactivatableEntity, 
        IReplicableEntity, 
        IStateTrackingEntity
    {
        private long? _oldOwnerCode;
        long? ICuratedEntity.OldOwnerCode { get { return _oldOwnerCode; } }
    
        public Account()
        {
            this.AccountDetails = new HashSet<AccountDetail>();
            this.Limits = new HashSet<Limit>();
            this.Locks = new HashSet<Lock>();
            this.Orders = new HashSet<Order>();
        }
    
        public long Id { get; set; }
        public System.Guid ReplicationCode { get; set; }
        public Nullable<long> DgppId { get; set; }
        public long BranchOfficeOrganizationUnitId { get; set; }
        public long LegalPersonId { get; set; }
        public string LegalPesonSyncCode1C { get; set; }
        public decimal Balance { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public long OwnerCode 
    	{
    		get
    		{
    			return _ownerCode;
    		}
    				 
    		set
    		{
    			_oldOwnerCode = _ownerCode;
    			_ownerCode = value;
    		} 
    	}
    				
    	private long _ownerCode;
        public long CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] Timestamp { get; set; }
    
        public ICollection<AccountDetail> AccountDetails { get; set; }
        public ICollection<Limit> Limits { get; set; }
        public ICollection<Lock> Locks { get; set; }
        public ICollection<Order> Orders { get; set; }
        public BranchOfficeOrganizationUnit BranchOfficeOrganizationUnit { get; set; }
        public LegalPerson LegalPerson { get; set; }
    }
}

// ReSharper enable RedundantUsingDirective
// ReSharper enable InconsistentNaming
// ReSharper enable PartialTypeWithSinglePart
// ReSharper enable RedundantNameQualifier
// ReSharper enable ConvertNullableToShortForm


