//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable ConvertNullableToShortForm

using System;
using System.Collections.Generic;
using DoubleGis.Erm.Model.Entities.Interfaces;
using DoubleGis.Erm.Model.Entities.Interfaces.Integration;

namespace DoubleGis.Erm.Model.Entities.Erm
{
    public sealed partial class FirmsForPostIntegrationActivity : IEntityKey
    {
        public long FirmId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool ExportOrders { get; set; }
        public bool SyncFirmAddresses { get; set; }
        public long Id { get; set; }
    
        public Firm Firm { get; set; }
    }
}

// ReSharper enable RedundantUsingDirective
// ReSharper enable InconsistentNaming
// ReSharper enable PartialTypeWithSinglePart
// ReSharper enable RedundantNameQualifier
// ReSharper enable ConvertNullableToShortForm


