//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable ConvertNullableToShortForm

using System;
using System.Collections.Generic;
using DoubleGis.Erm.Platform.Model.Entities.Interfaces;
using DoubleGis.Erm.Platform.Model.Entities.Interfaces.Integration;

namespace DoubleGis.Erm.Platform.Model.Entities.Erm
{
    public sealed partial class RegionalAdvertisingSharing : 
        IEntity, 
        IEntityKey, 
        IAuditableEntity, 
        IStateTrackingEntity
    {
        public RegionalAdvertisingSharing()
        {
            this.OrdersRegionalAdvertisingSharings = new HashSet<OrdersRegionalAdvertisingSharing>();
        }
    
        public long Id { get; set; }
        public System.DateTime BeginDistributionDate { get; set; }
        public long SourceOrganizationUnitId { get; set; }
        public long DestOrganizationUnitId { get; set; }
        public long SourceBranchOfficeOrganizationUnitId { get; set; }
        public long DestBranchOfficeOrganizationUnitId { get; set; }
        public decimal TotalAmount { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] Timestamp { get; set; }
    
        public BranchOfficeOrganizationUnit SourceBranchOfficeOrganizationUnit { get; set; }
        public BranchOfficeOrganizationUnit DestBranchOfficeOrganizationUnit { get; set; }
        public ICollection<OrdersRegionalAdvertisingSharing> OrdersRegionalAdvertisingSharings { get; set; }
        public OrganizationUnit SourceOrganizationUnit { get; set; }
        public OrganizationUnit DestOrganizationUnit { get; set; }
    }
}

// ReSharper enable RedundantUsingDirective
// ReSharper enable InconsistentNaming
// ReSharper enable PartialTypeWithSinglePart
// ReSharper enable RedundantNameQualifier
// ReSharper enable ConvertNullableToShortForm


