#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoubleGis.Erm.BLCore.UI.Web.Mvc.Views.Grid
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DoubleGis.Erm.BLCore.Resources.Server.Properties;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Controllers;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Models;
    using DoubleGis.Erm.BLCore.UI.Web.Mvc.Utils;
    using DoubleGis.Erm.Platform.Common;
    using DoubleGis.Erm.Platform.Model.Entities;
    using DoubleGis.Erm.Platform.Model.Entities.Enums;
    using DoubleGis.Erm.Platform.Model.Metadata.Enums;
    using DoubleGis.Erm.Platform.UI.Web.Mvc;
    using DoubleGis.Erm.Platform.UI.Web.Mvc.Utils;
    
    #line 1 "..\..\Views\Grid\View.cshtml"
    using Platform.UI.Web.Mvc.Security;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Grid\View.cshtml"
    using Settings;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Grid\View.cshtml"
    using UserProfiles;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Grid\View.cshtml"
    using ViewModels;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Grid/View.cshtml")]
    public partial class View : System.Web.Mvc.WebViewPage<Settings.ConfigurationDto.EntityViewSet>
    {
        public View()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org" +
"/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral(">\r\n<head>\r\n    <title>");

            
            #line 11 "..\..\Views\Grid\View.cshtml"
      Write(BLResources.List);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n\r\n    <meta");

WriteLiteral(" id=\"meta_IsDebug\"");

WriteLiteral(" name=\"meta_IsDebug\"");

WriteAttribute("content", Tuple.Create(" content=\"", 420), Tuple.Create("\"", 469)
            
            #line 13 "..\..\Views\Grid\View.cshtml"
, Tuple.Create(Tuple.Create("", 430), Tuple.Create<System.Object, System.Int32>(HttpContext.Current.IsDebuggingEnabled
            
            #line default
            #line hidden
, 430), false)
);

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" id=\"meta_Revision\"");

WriteLiteral(" name=\"meta_Revision\"");

WriteAttribute("content", Tuple.Create(" content=\"", 524), Tuple.Create("\"", 568)
            
            #line 14 "..\..\Views\Grid\View.cshtml"
, Tuple.Create(Tuple.Create("", 534), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 534), false)
);

WriteLiteral(" />\r\n    \r\n    <link");

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" href=\"/favicon.ico\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" href=\"/favicon.ico\"");

WriteLiteral("/>\r\n    \r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 766), Tuple.Create("\"", 828)
, Tuple.Create(Tuple.Create("", 773), Tuple.Create("/Content/ext-all.css?", 773), true)
            
            #line 19 "..\..\Views\Grid\View.cshtml"
, Tuple.Create(Tuple.Create("", 794), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 794), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 876), Tuple.Create("\"", 941)
, Tuple.Create(Tuple.Create("", 883), Tuple.Create("/Content/ext-extend.css?", 883), true)
            
            #line 20 "..\..\Views\Grid\View.cshtml"
, Tuple.Create(Tuple.Create("", 907), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 907), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 989), Tuple.Create("\"", 1052)
, Tuple.Create(Tuple.Create("", 996), Tuple.Create("/Content/DataList.css?", 996), true)
            
            #line 21 "..\..\Views\Grid\View.cshtml"
, Tuple.Create(Tuple.Create("", 1018), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 1018), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1100), Tuple.Create("\"", 1169)
, Tuple.Create(Tuple.Create("", 1107), Tuple.Create("/Content/QuickFindStyle.css?", 1107), true)
            
            #line 22 "..\..\Views\Grid\View.cshtml"
, Tuple.Create(Tuple.Create("", 1135), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 1135), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1217), Tuple.Create("\"", 1276)
, Tuple.Create(Tuple.Create("", 1224), Tuple.Create("/Content/CRM4.css?", 1224), true)
            
            #line 23 "..\..\Views\Grid\View.cshtml"
, Tuple.Create(Tuple.Create("", 1242), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 1242), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1324), Tuple.Create("\"", 1387)
, Tuple.Create(Tuple.Create("", 1331), Tuple.Create("/Content/ext-mask.css?", 1331), true)
            
            #line 24 "..\..\Views\Grid\View.cshtml"
, Tuple.Create(Tuple.Create("", 1353), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 1353), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1435), Tuple.Create("\"", 1501)
, Tuple.Create(Tuple.Create("", 1442), Tuple.Create("/Content/LookupStyle.css?", 1442), true)
            
            #line 25 "..\..\Views\Grid\View.cshtml"
, Tuple.Create(Tuple.Create("", 1467), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 1467), false)
);

WriteLiteral(" />\r\n    \r\n");

            
            #line 27 "..\..\Views\Grid\View.cshtml"
    
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\Grid\View.cshtml"
     if (HttpContext.Current.IsDebuggingEnabled)
    {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1585), Tuple.Create("\"", 1652)
, Tuple.Create(Tuple.Create("", 1591), Tuple.Create("/Scripts/ext-base-debug.js?", 1591), true)
            
            #line 29 "..\..\Views\Grid\View.cshtml"
, Tuple.Create(Tuple.Create("", 1618), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 1618), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1703), Tuple.Create("\"", 1780)
, Tuple.Create(Tuple.Create("", 1709), Tuple.Create("/Scripts/ext-all-debug-w-comments.js?", 1709), true)
            
            #line 30 "..\..\Views\Grid\View.cshtml"
, Tuple.Create(Tuple.Create("", 1746), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 1746), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

            
            #line 31 "..\..\Views\Grid\View.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1855), Tuple.Create("\"", 1916)
, Tuple.Create(Tuple.Create("", 1861), Tuple.Create("/Scripts/ext-base.js?", 1861), true)
            
            #line 34 "..\..\Views\Grid\View.cshtml"
, Tuple.Create(Tuple.Create("", 1882), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 1882), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1967), Tuple.Create("\"", 2027)
, Tuple.Create(Tuple.Create("", 1973), Tuple.Create("/Scripts/ext-all.js?", 1973), true)
            
            #line 35 "..\..\Views\Grid\View.cshtml"
, Tuple.Create(Tuple.Create("", 1993), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 1993), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

            
            #line 36 "..\..\Views\Grid\View.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2083), Tuple.Create("\"", 2225)
, Tuple.Create(Tuple.Create("", 2089), Tuple.Create("/Scripts/", 2089), true)
            
            #line 38 "..\..\Views\Grid\View.cshtml"
, Tuple.Create(Tuple.Create("", 2098), Tuple.Create<System.Object, System.Int32>("Ext.LocalizedResources." + ViewData.GetUserLocaleInfo().TwoLetterISOLanguageName + ".js"
            
            #line default
            #line hidden
, 2098), false)
, Tuple.Create(Tuple.Create("", 2190), Tuple.Create("?", 2190), true)
            
            #line 38 "..\..\Views\Grid\View.cshtml"
                                       , Tuple.Create(Tuple.Create("", 2191), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 2191), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        Ext.USER_ID = ");

            
            #line 41 "..\..\Views\Grid\View.cshtml"
                 Write(ViewData.GetUserIdentityInfo().Code);

            
            #line default
            #line hidden
WriteLiteral(";\r\n        Ext.USER_NAME = ");

            
            #line 42 "..\..\Views\Grid\View.cshtml"
                   Write(ViewData.GetUserIdentityDisplayName());

            
            #line default
            #line hidden
WriteLiteral(";\r\n        Ext.CultureInfo = ");

            
            #line 43 "..\..\Views\Grid\View.cshtml"
                     Write(Html.WriteJson(ViewData.GetUserLocaleInfo()));

            
            #line default
            #line hidden
WriteLiteral(";\r\n        Ext.CultureInfo.NumberFormatInfo.CurrencySymbol = \'");

            
            #line 44 "..\..\Views\Grid\View.cshtml"
                                                      Write(ViewData.GetErmBaseCurrencySymbol());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        Ext.CRM_URL = \'");

            
            #line 45 "..\..\Views\Grid\View.cshtml"
                  Write(ViewData.GetMsCrmSettingsUrl());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        Ext.BasicOperationsServiceRestUrl = \'");

            
            #line 46 "..\..\Views\Grid\View.cshtml"
                                        Write(ViewData.GetBasicOperationsServiceRestUrl());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n    </script>\r\n    \r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2782), Tuple.Create("\"", 2860)
, Tuple.Create(Tuple.Create("", 2788), Tuple.Create("/Scripts/DoubleGis.GlobalVariables.js?", 2788), true)
            
            #line 49 "..\..\Views\Grid\View.cshtml"
, Tuple.Create(Tuple.Create("", 2826), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 2826), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2907), Tuple.Create("\"", 2980)
, Tuple.Create(Tuple.Create("", 2913), Tuple.Create("/Scripts/Ext.Ajax.syncRequest.js?", 2913), true)
            
            #line 50 "..\..\Views\Grid\View.cshtml"
, Tuple.Create(Tuple.Create("", 2946), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 2946), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3027), Tuple.Create("\"", 3099)
, Tuple.Create(Tuple.Create("", 3033), Tuple.Create("/Scripts/Common.ErrorHandler.js?", 3033), true)
            
            #line 51 "..\..\Views\Grid\View.cshtml"
, Tuple.Create(Tuple.Create("", 3065), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 3065), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3146), Tuple.Create("\"", 3220)
, Tuple.Create(Tuple.Create("", 3152), Tuple.Create("/Scripts/DoubleGis.UI.DataList.js?", 3152), true)
            
            #line 52 "..\..\Views\Grid\View.cshtml"
, Tuple.Create(Tuple.Create("", 3186), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 3186), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        var SearchRecords = function ()
        {
            Entity.QueryParams.filterExpression = Ext.DoubleGis.Global.Helpers.BuildDataListFilter(Entity, Entity.FilterInfo, this.getValue());
            Entity.Items.Store.setBaseParam(""whereExp"", Entity.QueryParams.filterExpression);
            Entity.Items.Store.setBaseParam(""filterInput"", this.getValue());
            Entity.Items.Grid.getBottomToolbar().changePage(1);
        };
    
        Ext.onReady(function ()
            {
            var settings = ");

            
            #line 65 "..\..\Views\Grid\View.cshtml"
                      Write(Html.WriteJson(Model));

            
            #line default
            #line hidden
WriteLiteral(@";
            settings.listeners = {
                afterbuild:function () 
                {
                    var viewBox = Ext.get(""availableViews"");
                    var defaultView = this.currentSettings;
                    Ext.each(this.EntityModel.DataViews, function (item) {
                        var isDefault = defaultView && item.NameLocaleResourceId == defaultView.NameLocaleResourceId;
                        viewBox.dom.options.add(new Option(item.LocalizedName, item.NameLocaleResourceId, isDefault, isDefault));
                    });
                    viewBox.on(""change"", this.RebuildPage, this);
                },
                afterrebuild: function () {
                    Ext.DoubleGis.UI.QuikFind[""RecordFilter""].setValue("""");
                    if(this.currentSettings.Title) {
                        window.document.title = this.currentSettings.Title;
                    }
                }
            };
            window.Entity = new Ext.DoubleGis.UI.DataList(settings);
        });
    </script>
");

            
            #line 87 "..\..\Views\Grid\View.cshtml"
    
            
            #line default
            #line hidden
            
            #line 87 "..\..\Views\Grid\View.cshtml"
     foreach (var script in Model.DataViews.First().Scripts)
    {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4998), Tuple.Create("\"", 5064)
, Tuple.Create(Tuple.Create("", 5004), Tuple.Create("/Scripts/", 5004), true)
            
            #line 89 "..\..\Views\Grid\View.cshtml"
, Tuple.Create(Tuple.Create("", 5013), Tuple.Create<System.Object, System.Int32>(script.FileName
            
            #line default
            #line hidden
, 5013), false)
, Tuple.Create(Tuple.Create("", 5029), Tuple.Create("?", 5029), true)
            
            #line 89 "..\..\Views\Grid\View.cshtml"
, Tuple.Create(Tuple.Create("", 5030), Tuple.Create<System.Object, System.Int32>(SolutionInfo.ProductVersion.Build
            
            #line default
            #line hidden
, 5030), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

            
            #line 90 "..\..\Views\Grid\View.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</head>\r\n<body");

WriteLiteral(" class=\"stage\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"DataListContent\"");

WriteLiteral(" style=\"display: none\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"FilterPanel\"");

WriteLiteral(">\r\n            <table");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" border=\"0\"");

WriteLiteral(" style=\"background-color: #d6e8ff\"");

WriteLiteral(">\r\n                <tr>\r\n                    <td>\r\n                        <table" +
"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" border=\"0\"");

WriteLiteral(" cellpadding=\"0\"");

WriteLiteral(" style=\"padding-left: 5px; padding-top: 7px;\r\n                            padding" +
"-bottom: 5px;\"");

WriteLiteral(">\r\n                            <colgroup>\r\n                                <col");

WriteLiteral(" width=\"60%\"");

WriteLiteral(" />\r\n                                <col");

WriteLiteral(" width=\"20\"");

WriteLiteral(" />\r\n                                <col />\r\n                                <co" +
"l");

WriteLiteral(" width=\"40%\"");

WriteLiteral(" />\r\n                            </colgroup>\r\n                            <tr>\r\n " +
"                               <td>\r\n");

            
            #line 108 "..\..\Views\Grid\View.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 108 "..\..\Views\Grid\View.cshtml"
                                      
                                        Html.RenderPartial("QuickFindControl", new QuickFindSettings
                                        {
                                            Name = "RecordFilter",
                                            OnSearchFunction = "SearchRecords"
                                        });
                                     
            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                                <td");

WriteLiteral(" style=\"width: 20\"");

WriteLiteral(">\r\n                                    <span />\r\n                                " +
"</td>\r\n                                <td");

WriteLiteral(" style=\"font-weight: bold;\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 120 "..\..\Views\Grid\View.cshtml"
                               Write(BLResources.View);

            
            #line default
            #line hidden
WriteLiteral(":\r\n                                </td>\r\n                                <td");

WriteLiteral(" class=\"QuickFind\"");

WriteLiteral(">\r\n                                    <select");

WriteLiteral(" id=\"availableViews\"");

WriteLiteral(" class=\"inputfields\"");

WriteLiteral(" style=\"width: 100%\"");

WriteLiteral(">\r\n                                        <optgroup");

WriteLiteral(" id=\"AppSystemViews\"");

WriteAttribute("label", Tuple.Create(" label=\"", 6860), Tuple.Create("\"", 6892)
            
            #line 124 "..\..\Views\Grid\View.cshtml"
, Tuple.Create(Tuple.Create("", 6868), Tuple.Create<System.Object, System.Int32>(BLResources.SystemViews
            
            #line default
            #line hidden
, 6868), false)
);

WriteLiteral(@" />
                                    </select>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</body>
</html>
");

        }
    }
}
#pragma warning restore 1591
