#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoubleGis.Erm.BLFlex.Web.Mvc.Global.Views.CreateOrUpdate
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DoubleGis.Erm.BL.Resources.Server.Properties;
    using DoubleGis.Erm.Core;
    using DoubleGis.Erm.Core.Enums;
    
    #line 1 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
    using DoubleGis.Erm.Platform.Model.Entities;
    
    #line default
    #line hidden
    using DoubleGis.Erm.UI.Web.Mvc;
    using DoubleGis.Erm.UI.Web.Mvc.Controllers;
    using DoubleGis.Erm.UI.Web.Mvc.Models;
    
    #line 2 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
    using DoubleGis.Erm.UI.Web.Mvc.Utils;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
    using Platform.Web.Mvc.Utils;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CreateOrUpdate/CyprusContact.cshtml")]
    public partial class CyprusContact : System.Web.Mvc.WebViewPage<CyprusContactViewModel>
    {
        public CyprusContact()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
  
    Layout = "../Shared/_CardLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("CardScripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        window.InitPage = function ()\r\n        {\r\n            Card.on(\"beforeb" +
"uild\", function ()\r\n            {\r\n                if (Ext.getDom(\"Id\").value !=" +
" 0)\r\n                {\r\n                    // change owner\r\n                   " +
" this.ChangeOwner = function ()\r\n                    {\r\n                        " +
"var params = \"dialogHeight:270px; dialogWidth:650px; status:yes; scroll:no; resi" +
"zable:no; \";\r\n                        var sUrl = \"/GroupOperation/Assign/Contact" +
"\";\r\n                        var result = window.showModalDialog(sUrl, [Ext.getDo" +
"m(\"Id\").value], params);\r\n                        if (result === true)\r\n        " +
"                {\r\n                            this.refresh(true);\r\n            " +
"            }\r\n                    };\r\n\r\n                }\r\n            });\r\n   " +
"         Card.on(\"afterbuild\", function ()\r\n            {\r\n                Ext.g" +
"et(\"Gender\").on(\"change\", function (s, e)\r\n                {\r\n                  " +
"  Card.refillSalutationComboBox(e.value, null);\r\n                });\r\n\r\n        " +
"        // После загрузки страницы, выставляем значение поля \"Обращение\".\r\n     " +
"           Card.refillSalutationComboBox(Ext.get(\"Gender\").getValue(), Card.init" +
"ialSalutation);\r\n                Card.initialSalutation = null;\r\n\r\n            }" +
" /* end of afterbuild*/);\r\n\r\n            Ext.apply(this, {\r\n                addO" +
"ption: function (oListbox, text, value, isSelected)\r\n                {\r\n        " +
"            var oOption = document.createElement(\"option\");\r\n                   " +
" oOption.appendChild(document.createTextNode(text));\r\n                    oOptio" +
"n.setAttribute(\"value\", value);\r\n                    if (isSelected)\r\n          " +
"              oOption.selected = true;\r\n                    oListbox.appendChild" +
"(oOption);\r\n                },\r\n                refillSalutationComboBox: functi" +
"on (genderValue, selectedValue)\r\n                {\r\n                    var salu" +
"tationDom = Ext.getDom(\"Salutation\");\r\n                    salutationDom.length " +
"= 0;\r\n\r\n                    var response = window.Ext.Ajax.syncRequest({\r\n      " +
"                  method: \'POST\',\r\n                        url: \'/Contact/GetSal" +
"utations\',\r\n                        params: {\r\n                            gende" +
"r: genderValue\r\n                        }\r\n                    });\r\n            " +
"        if ((response.conn.status >= 200 && response.conn.status < 300) || (Ext." +
"isIE && response.conn.status == 1223))\r\n                    {\r\n                 " +
"       var result = Ext.decode(response.conn.responseText);\r\n                   " +
"     Card.addOption(salutationDom, \"\", \"\");\r\n                        for (var i " +
"= 0; i < result.length; i++)\r\n                        {\r\n                       " +
"     var isSelected = selectedValue != null ? result[i] == selectedValue : i == " +
"0;\r\n                            Card.addOption(salutationDom, result[i], result[" +
"i], isSelected);\r\n                        }\r\n                    }\r\n            " +
"        else\r\n                    {\r\n                        Card.AddNotificatio" +
"n(response.conn.responseText, \'CriticalError\', messageId);\r\n                    " +
"}\r\n                }\r\n            });\r\n\r\n            Card.initialSalutation = \'");

            
            #line 85 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
                                 Write(Model.Salutation);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        }\r\n    </script>\r\n");

});

WriteLiteral("\r\n");

DefineSection("CardBody", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 92 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
Write(Html.HiddenFor(m => m.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 93 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
Write(Html.HiddenFor(m => m.ReplicationCode));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 94 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
Write(Html.HiddenFor(m => m.FullName));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 97 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
Write(Html.HiddenFor(m => m.ClientReplicationCode));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 98 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
Write(Html.HiddenFor(m => m.ClientName));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"Tab\"");

WriteLiteral(" id=\"MainTab\"");

WriteAttribute("title", Tuple.Create(" title=\"", 3830), Tuple.Create("\"", 3866)
            
            #line 100 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
, Tuple.Create(Tuple.Create("", 3838), Tuple.Create<System.Object, System.Int32>(BLResources.GeneralTabTitle
            
            #line default
            #line hidden
, 3838), false)
);

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 102 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
       Write(Html.TemplateField(m => m.Gender, FieldFlex.twins, null, EnumResources.ResourceManager));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 103 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
       Write(Html.TemplateField(m => m.MainPhoneNumber, FieldFlex.twins));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 106 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
       Write(Html.TemplateField(m => m.Salutation, FieldFlex.twins, new Dictionary<string, object>{{"combobox", "true"}}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 107 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
       Write(Html.TemplateField(m => m.MobilePhoneNumber, FieldFlex.twins));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 110 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
       Write(Html.TemplateField(m => m.LastName, FieldFlex.twins));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 111 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
       Write(Html.TemplateField(m => m.AdditionalPhoneNumber, FieldFlex.twins));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 114 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
       Write(Html.TemplateField(m => m.FirstName, FieldFlex.twins));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 115 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
       Write(Html.TemplateField(m => m.Fax, FieldFlex.twins));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 118 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
       Write(Html.TemplateField(m => m.WorkEmail, FieldFlex.twins));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 119 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
       Write(Html.TemplateField(m => m.Im, FieldFlex.twins));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 122 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
       Write(Html.TemplateField(m => m.Client, FieldFlex.twins, new LookupSettings { EntityName = EntityName.Client, ReadOnly =  Model != null && Model.Client != null && !string.IsNullOrEmpty(Model.Client.Value) }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n");

WriteLiteral("        ");

            
            #line 124 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
   Write(Html.SectionHead("SectionHead1", @BLResources.TitleServiceInformation));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 126 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
       Write(Html.TemplateField(m => m.JobTitle, FieldFlex.twins));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 127 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
       Write(Html.TemplateField(m => m.AccountRole, FieldFlex.twins, null, EnumResources.ResourceManager));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 130 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
       Write(Html.TemplateField(m => m.Department, FieldFlex.twins));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 131 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
       Write(Html.TemplateField(m => m.IsFired, FieldFlex.twins));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 134 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
       Write(Html.TemplateField(m => m.WorkAddress, FieldFlex.lone));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 137 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
       Write(Html.TemplateField(m => m.Comment, FieldFlex.lone, new Dictionary<string, object>{{"rows", "3"}}));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n");

WriteLiteral("        ");

            
            #line 139 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
   Write(Html.SectionHead("SectionHead2", @BLResources.AdditionalTabTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"row-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 141 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
       Write(Html.TemplateField(m => m.BirthDate, FieldFlex.twins));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 142 "..\..\Views\CreateOrUpdate\CyprusContact.cshtml"
       Write(Html.TemplateField(m => m.Website , FieldFlex.twins));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

});

        }
    }
}
#pragma warning restore 1591
