//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

// ReSharper disable RedundantUsingDirective
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable ConvertNullableToShortForm

using System;
using System.Collections.Generic;
using DoubleGis.Erm.Platform.Model.Entities.Interfaces;

namespace DoubleGis.Erm.Platform.Model.Entities.Security
{
    public sealed partial class Privilege : 
        IEntity, 
        IEntityKey
    {
        public Privilege()
        {
            this.FunctionalPrivilegeDepths = new HashSet<FunctionalPrivilegeDepth>();
            this.UserEntities = new HashSet<UserEntity>();
            this.RolePrivileges = new HashSet<RolePrivilege>();
        }
    
        public long Id { get; set; }
        public Nullable<int> EntityType { get; set; }
        public int Operation { get; set; }
    
        public ICollection<FunctionalPrivilegeDepth> FunctionalPrivilegeDepths { get; set; }
        public ICollection<UserEntity> UserEntities { get; set; }
        public ICollection<RolePrivilege> RolePrivileges { get; set; }
    }
}

// ReSharper enable RedundantUsingDirective
// ReSharper enable InconsistentNaming
// ReSharper enable PartialTypeWithSinglePart
// ReSharper enable RedundantNameQualifier
// ReSharper enable ConvertNullableToShortForm


